* 测试日记。
这里是我第一次写，测试一下。
* 2017
** 2017-02 February
*** 2017-02-20 Monday
**** 写下第二次测试日记。
Entered on [2017-02-20 Mon 18:19]
**** 又一个测试的版本
***** 计划如下
1.学习org...这个东西也很多很大很复杂。。
todo必须做 还有什么时间戳啊 tags啊 感觉非常棒。
2.学习git...手头有本pdf不过可能得回头看了
3.做题。。。其实我现在有一点纠结的。
Entered on [2017-02-20 Mon 18:19]
**** 一点随感于思修课上
刚才的一瞬竟令我有些许的动摇。
我想到我由markdown的沉迷到对org的渴望，想到我几近半年不曾写日记。
遂生出数字文本于手写文本之间的选择冲突。
其实我最先想到的是哪个更能保存更有价值（宛如一个想将世间一切独吞之国王，一个想将记忆全部封存在某种球体的妄想之鱼，想将迷宫走完，将成就毕竟，将走过的路完善臻至极限...）
就像曾经我凡一论文即复制一份备份保存甚至想将我那些通信（那些可爱的）全部复制备份全部封住留存。
就像我当初似是已经知道了什么一般不住的凝视凝视意欲将某些印象永久烙刻。

啧，思绪有些走远，不过很好。主要是我所牵挂、意志常常憋的我透不过气（致密的恍惚）
那种浑浊的，压抑的宛如西夏旅馆一般的所谓意志，却在外人看来强迫痛苦扭曲恍若石入水之涟漪却只再也听不得回声。
今日英语，得在BigBang（也许是生活大爆炸吧）中看到一个机械、笨拙、满脑子知识与秩序的同类，许是因为剧而夸张，但我却极为歆羨他那样的直接了当的表达。我的意志...却因为受了太多束缚制约而变得千疮百孔......我想说的是，压抑而不得表达。最终表现出来就是反抗、爆炸、彷徨、无望。我的世界外面多了一层东西，那使我变得“理智”也同时失去了许多。


近来感觉大秦话非常有趣，怕不是中毒本性暴露。
近来喜欢一款叫做宝石TD的塔防游戏，怕不是中毒本性暴露。因为不能过关却每每都知道失误在何处知道那里可以改进的无止境的尝试。

我给沈说起我将要放弃纸质，他却反应有些激烈：“又少了一个战友，再见”
令我颇为不适亦无法适从。
其实也不是以为纸质不好。我曾经多次暗暗许愿我会坚持“写毛笔字”这一事项（当然建立在我不被强迫种种的基础上），但是就我目前的性质来说，就我目前对电脑的依赖来说，我现在需要这样的日志。

哎，开学第一天，坚持到现在还没有玩。还不错。
课程一般，天气很坏。
被子很舒服，睡觉也不错，心态不错。我感觉良好。

Entered on [2017-02-20 Mon 20:57]
**** 今日完成
如何记日记（其实并不是什么难事。）

Entered on [2017-02-20 Mon 21:22]
*** 2017-02-21 Tuesday
**** 操蛋的一天。
首先物理实验超乎寻常的严格。不过这其实没什么，物理实验还算有趣。
我就不该回宿舍学习，效率无比低下，不想多说。
外面又冷的无以复加，我感到绝望。
一个操蛋的水题到现在都没做出来，都开始怀疑编译器是不是出了问题，是不是break无法跳出循环...
冷啊。我感到毛裤之必要。
算了早睡觉吧。有些心烦意乱。主要是题233.

Entered on [2017-02-21 Tue 20:54]
  
  [[file:~/Desktop/c%2B%2B%20and%20acm/hdu2-2-2/main.cpp::printf("1")%3B][file:~/Desktop/c++ and acm/hdu2-2-2/main.cpp::printf("1");]]
**** 诶我做出来了
但是超时了。
于是去找了下题解，发现这帮人居然直接打表！居然直接记下所有要求的值然后日过去了，fkit！这不清真！
我不做了！fkit！
fkit！
明天学打表，学org，学git，学一下谷安网课吧。
今天了解了一点lisp，知道了一本scip，想去学haskell。咩哈哈。

最近是真的冷，一想到冷到无法好好学习就好烦啊。明天去图书馆（如果不下雨！！！）

Entered on [2017-02-21 Tue 22:09]
*** 2017-02-23 Thursday
**** 这里记的是昨天的内容
昨天夜里沉迷steam，忘记了写日记。
***** 汇报工作
昨天大概是知道了约瑟夫环的两种写法（？）有待查证：
kill=(kill+m-1)%n （某题解，m为第几个，n每次--）
kill=(kill+d+n-1)% n + 1 （紫书，do{...}while（a[p]==0））
然后看了几个pta的小题...大概今天能做（如果没有被体育课累垮233）

怀疑emacs+gcc的重定向好久，结果发现好像是因为死循环，今天再试试吧。

下午开了个小会，知道了科协和校队的计划，同时，加深了我的恐惧与紧张。

***** 日记
说到恐惧与紧张，我好不容易在寒假里找回了原初，却几近被打回原型。什么队里dalao小学就学py学vb啊，什么陈志老师可能会踢人啊，什么队里非常激烈啊。我一下子就紧张了起来，感觉十分害怕，感到非常慌张。
沈晚上教育我：不然你玩cs的时候别人凭什么在学py？我并不觉得咋了，这种人难道不多？
啧，颇有一种失落与愤懑积怨呢。
不过想想似乎有些道理：自己在基础上

晚上发现了某宝与steam 不可不说的联系，于是买了20+ 个游戏来。还不错，找到了好货，还找到了童年2333（孤单枪手）。
不过也因为这个晚上由于兴奋（喜+1）而有些荒废了= = 该做的事情都没怎么做。

Entered on [2017-02-23 Thu 08:59]
**** 我有一句mmp不知当讲不当讲
从体育课完了之后我就一直在怼这道水题，结果竟然是各种“0”的问题。“浮点错误”是一个神奇的东西----除了0 同余了0 。
啧啧啧。
负数+正数有时也能得0，我是真的没想到....

Entered on [2017-02-23 Thu 19:30]
**** 去除心头二患
现在C-c c可以直接调用org-capture了
现在M-w和C-w可以复制到剪切板了，这个nice到爆炸！刚才做题到时候大概有好几次都是忘记emacs不能（当时不能）向外剪切内容，啧啧啧

Entered on [2017-02-23 Thu 20:00]
  
  [[file:~/Desktop/c%2B%2B%20and%20acm/tianti/5-2/main.cpp][file:~/Desktop/c++ and acm/tianti/5-2/main.cpp]]
*** 2017-02-25 Saturday
**** 今天的和昨天的份
其实这两天啥都没干，差不多一直在和沈玩。23号是沈的生日，权当稀里糊涂的过了吧。
汇报工作的话，就是做了几个天梯上的水题。就当成复习和熟练了。。。

其实说起来事还挺多的，把键盘送出去，把图片和英文给组长，把几项奇奇怪怪的作业写完....只是懒得不想动弹。

Entered on [2017-02-25 Sat 19:07]
  
  [[file:~/Desktop/c%2B%2B%20and%20acm/tianti/5-9/main.cpp::#include%20<iostream>][file:~/Desktop/c++ and acm/tianti/5-9/main.cpp::#include <iostream>]]
*** 2017-02-26 Sunday
**** 迷之失落
早上出去转了转，把键盘寄回去修，又去羊山公园绕了半圈，也算是破了“从未出过校门”之说。东边的道路都冷清的很，感觉比羊山公园还要好玩一些——大体是因为羊山公园离主道太近，又用广告牌围起了半边吧。破坏了原有的美感与意境..总之我大概是不会再去了(\立下flag?)。
走在那种只有时不时的车辆经过的街区竟重现了过去的某种失落之情。似乎是在这种气氛中我忽然想起一件事情--明天陈雅雯过生日。
于是忽然僵住。

Entered on [2017-02-26 Sun 17:55]
*** 2017-02-27 Monday
**** 于思修课上
我竟然真的做了和思修有关的事情。
那就是看了一点逼乎上各路大神之言论。
我曾以为1984美丽新世界已然描绘出现世政治之全貌，却刚刚发现现实之中的矛盾冲突一点不比小说差多少，其情节之复杂，人物个性之鲜明与浑浊，不同角度不同方面对话题的调离、抽换、吐槽、调侃，有人洗地有人高呼有人热血上涌不顾一切。应当说诸生百态皆在其中，实在是一出大戏。可能也只有网络才能上演这样那样的离奇故事了吧。（应当说，比之西夏旅馆毫不为过吗，哈哈）

----「如何看待微博上一名男性自干五发帖控诉自己被强制结扎？」

自干五是我第一次了解的一种神奇的生物。虽然网上只有正能量的自干五介绍，我却还是觉察到了那么一丝丝的违和感。

然后就是这样一条评论，深深触动了我的心。
「我支持某项政策≠这项政策执行到我头上我已然支持。我不觉得这两者有什么矛盾的地方，也从来没幻想过自己可以不被碾过去。车轮碾我的时候，我就叫唤，不碾我的时候，我就称赞车轮。我不是精神分裂，我只是明白，这世上没有十全十美的事。」

有一些精妙的评论：
「绝育手术证明的字好看」竟有一石二鸟之感。
「我真的有一头牛」我第一时间没有反应过来。
「只要你精分，就能逻辑自洽」
「这盛世如你所愿」关键在于反差。

颇有些入迷了，竟一时忘了一会有课。上课去也。

Entered on [2017-02-27 Mon 17:41]
**** 。。回来写两句
配置好了更新不上！什么鬼！
Entered on [2017-02-27 Mon 23:37]
*** 2017-02-28 Tuesday
**** 喵喵喵？？？
今天写了一大堆都没了？？？？？wtf？？？
而且是今天的一概没有？？


Entered on [2017-02-28 Tue 22:19]
**** what the fk？
而且今天记下来的题解也都没了？？？
什么鬼啊？？？
我脑子里一片问号


Entered on [2017-02-28 Tue 22:20]
**** 我日
用git把自己覆盖了！
checkout我以为是。。干啊。。居然是一个危险至极的指令。


Entered on [2017-02-28 Tue 22:23]
**** 无奈再写一遍
题解是没了
今天只做出了一题。

训练的时候肚痛，死去活来。抖动抖动面色发黑神色扭曲恍若某种怪物变形前兆。

大概是晚饭？也可能是早上的酸梅汁？或者是中午活活把美梦作死（梦到回到学校似乎要发生什么有趣的事情的时候我却因为细节太真而疑是幻觉[大概是一块娓娓道来有头有尾有名有姓的海报板]于是想从中出来竟真的破碎出来生生把一切搅碎）？抑或是中午起床后为了保持自己的状态到下午训练的一杯咖啡？又也许是训练时过于紧张急切的心情？

总之是来的突然，来的猛烈，而且是我第一次在外所受。

虽然晚上本该（本来我该一刻就可以上床的，该死的git把我文件搞炸了，我现在蹲在地上衣衫褴褛的打字）洗衣服写作业但是却失力毫无依托毫无支撑。
而且有点饿。
睡了。本来是打算扩大夜生活的。毕竟晚上的时间好多都没了，这学期的支配时间变得极为稀缺....结果首日就遇到这样的事情。

听闻父亲得了心脏病，有些担心（似乎又不是，回头问下）。


Entered on [2017-02-28 Tue 22:24]
