* 测试日记。
这里是我第一次写，测试一下。
* 2017
** 2017-02 February
*** 2017-02-20 Monday
**** 写下第二次测试日记。
Entered on [2017-02-20 Mon 18:19]
**** 又一个测试的版本
***** 计划如下
1.学习org...这个东西也很多很大很复杂。。
todo必须做 还有什么时间戳啊 tags啊 感觉非常棒。
2.学习git...手头有本pdf不过可能得回头看了
3.做题。。。其实我现在有一点纠结的。
Entered on [2017-02-20 Mon 18:19]
**** 一点随感于思修课上
刚才的一瞬竟令我有些许的动摇。
我想到我由markdown的沉迷到对org的渴望，想到我几近半年不曾写日记。
遂生出数字文本于手写文本之间的选择冲突。
其实我最先想到的是哪个更能保存更有价值（宛如一个想将世间一切独吞之国王，一个想将记忆全部封存在某种球体的妄想之鱼，想将迷宫走完，将成就毕竟，将走过的路完善臻至极限...）
就像曾经我凡一论文即复制一份备份保存甚至想将我那些通信（那些可爱的）全部复制备份全部封住留存。
就像我当初似是已经知道了什么一般不住的凝视凝视意欲将某些印象永久烙刻。

啧，思绪有些走远，不过很好。主要是我所牵挂、意志常常憋的我透不过气（致密的恍惚）
那种浑浊的，压抑的宛如西夏旅馆一般的所谓意志，却在外人看来强迫痛苦扭曲恍若石入水之涟漪却只再也听不得回声。
今日英语，得在BigBang（也许是生活大爆炸吧）中看到一个机械、笨拙、满脑子知识与秩序的同类，许是因为剧而夸张，但我却极为歆羨他那样的直接了当的表达。我的意志...却因为受了太多束缚制约而变得千疮百孔......我想说的是，压抑而不得表达。最终表现出来就是反抗、爆炸、彷徨、无望。我的世界外面多了一层东西，那使我变得“理智”也同时失去了许多。


近来感觉大秦话非常有趣，怕不是中毒本性暴露。
近来喜欢一款叫做宝石TD的塔防游戏，怕不是中毒本性暴露。因为不能过关却每每都知道失误在何处知道那里可以改进的无止境的尝试。

我给沈说起我将要放弃纸质，他却反应有些激烈：“又少了一个战友，再见”
令我颇为不适亦无法适从。
其实也不是以为纸质不好。我曾经多次暗暗许愿我会坚持“写毛笔字”这一事项（当然建立在我不被强迫种种的基础上），但是就我目前的性质来说，就我目前对电脑的依赖来说，我现在需要这样的日志。

哎，开学第一天，坚持到现在还没有玩。还不错。
课程一般，天气很坏。
被子很舒服，睡觉也不错，心态不错。我感觉良好。

Entered on [2017-02-20 Mon 20:57]
**** 今日完成
如何记日记（其实并不是什么难事。）

Entered on [2017-02-20 Mon 21:22]
*** 2017-02-21 Tuesday
**** 操蛋的一天。
首先物理实验超乎寻常的严格。不过这其实没什么，物理实验还算有趣。
我就不该回宿舍学习，效率无比低下，不想多说。
外面又冷的无以复加，我感到绝望。
一个操蛋的水题到现在都没做出来，都开始怀疑编译器是不是出了问题，是不是break无法跳出循环...
冷啊。我感到毛裤之必要。
算了早睡觉吧。有些心烦意乱。主要是题233.

Entered on [2017-02-21 Tue 20:54]
  
  [[file:~/Desktop/c%2B%2B%20and%20acm/hdu2-2-2/main.cpp::printf("1")%3B][file:~/Desktop/c++ and acm/hdu2-2-2/main.cpp::printf("1");]]
**** 诶我做出来了
但是超时了。
于是去找了下题解，发现这帮人居然直接打表！居然直接记下所有要求的值然后日过去了，fkit！这不清真！
我不做了！fkit！
fkit！
明天学打表，学org，学git，学一下谷安网课吧。
今天了解了一点lisp，知道了一本scip，想去学haskell。咩哈哈。

最近是真的冷，一想到冷到无法好好学习就好烦啊。明天去图书馆（如果不下雨！！！）

Entered on [2017-02-21 Tue 22:09]
*** 2017-02-23 Thursday
**** 这里记的是昨天的内容
昨天夜里沉迷steam，忘记了写日记。
***** 汇报工作
昨天大概是知道了约瑟夫环的两种写法（？）有待查证：
kill=(kill+m-1)%n （某题解，m为第几个，n每次--）
kill=(kill+d+n-1)% n + 1 （紫书，do{...}while（a[p]==0））
然后看了几个pta的小题...大概今天能做（如果没有被体育课累垮233）

怀疑emacs+gcc的重定向好久，结果发现好像是因为死循环，今天再试试吧。

下午开了个小会，知道了科协和校队的计划，同时，加深了我的恐惧与紧张。

***** 日记
说到恐惧与紧张，我好不容易在寒假里找回了原初，却几近被打回原型。什么队里dalao小学就学py学vb啊，什么陈志老师可能会踢人啊，什么队里非常激烈啊。我一下子就紧张了起来，感觉十分害怕，感到非常慌张。
沈晚上教育我：不然你玩cs的时候别人凭什么在学py？我并不觉得咋了，这种人难道不多？
啧，颇有一种失落与愤懑积怨呢。
不过想想似乎有些道理：自己在基础上

晚上发现了某宝与steam 不可不说的联系，于是买了20+ 个游戏来。还不错，找到了好货，还找到了童年2333（孤单枪手）。
不过也因为这个晚上由于兴奋（喜+1）而有些荒废了= = 该做的事情都没怎么做。

Entered on [2017-02-23 Thu 08:59]
**** 我有一句mmp不知当讲不当讲
从体育课完了之后我就一直在怼这道水题，结果竟然是各种“0”的问题。“浮点错误”是一个神奇的东西----除了0 同余了0 。
啧啧啧。
负数+正数有时也能得0，我是真的没想到....

Entered on [2017-02-23 Thu 19:30]
**** 去除心头二患
现在C-c c可以直接调用org-capture了
现在M-w和C-w可以复制到剪切板了，这个nice到爆炸！刚才做题到时候大概有好几次都是忘记emacs不能（当时不能）向外剪切内容，啧啧啧

Entered on [2017-02-23 Thu 20:00]
  
  [[file:~/Desktop/c%2B%2B%20and%20acm/tianti/5-2/main.cpp][file:~/Desktop/c++ and acm/tianti/5-2/main.cpp]]
*** 2017-02-25 Saturday
**** 今天的和昨天的份
其实这两天啥都没干，差不多一直在和沈玩。23号是沈的生日，权当稀里糊涂的过了吧。
汇报工作的话，就是做了几个天梯上的水题。就当成复习和熟练了。。。

其实说起来事还挺多的，把键盘送出去，把图片和英文给组长，把几项奇奇怪怪的作业写完....只是懒得不想动弹。

Entered on [2017-02-25 Sat 19:07]
  
  [[file:~/Desktop/c%2B%2B%20and%20acm/tianti/5-9/main.cpp::#include%20<iostream>][file:~/Desktop/c++ and acm/tianti/5-9/main.cpp::#include <iostream>]]
*** 2017-02-26 Sunday
**** 迷之失落
早上出去转了转，把键盘寄回去修，又去羊山公园绕了半圈，也算是破了“从未出过校门”之说。东边的道路都冷清的很，感觉比羊山公园还要好玩一些——大体是因为羊山公园离主道太近，又用广告牌围起了半边吧。破坏了原有的美感与意境..总之我大概是不会再去了(\立下flag?)。
走在那种只有时不时的车辆经过的街区竟重现了过去的某种失落之情。似乎是在这种气氛中我忽然想起一件事情--明天陈雅雯过生日。
于是忽然僵住。

Entered on [2017-02-26 Sun 17:55]
*** 2017-02-27 Monday
**** 于思修课上
我竟然真的做了和思修有关的事情。
那就是看了一点逼乎上各路大神之言论。
我曾以为1984美丽新世界已然描绘出现世政治之全貌，却刚刚发现现实之中的矛盾冲突一点不比小说差多少，其情节之复杂，人物个性之鲜明与浑浊，不同角度不同方面对话题的调离、抽换、吐槽、调侃，有人洗地有人高呼有人热血上涌不顾一切。应当说诸生百态皆在其中，实在是一出大戏。可能也只有网络才能上演这样那样的离奇故事了吧。（应当说，比之西夏旅馆毫不为过吗，哈哈）

----「如何看待微博上一名男性自干五发帖控诉自己被强制结扎？」

自干五是我第一次了解的一种神奇的生物。虽然网上只有正能量的自干五介绍，我却还是觉察到了那么一丝丝的违和感。

然后就是这样一条评论，深深触动了我的心。
「我支持某项政策≠这项政策执行到我头上我已然支持。我不觉得这两者有什么矛盾的地方，也从来没幻想过自己可以不被碾过去。车轮碾我的时候，我就叫唤，不碾我的时候，我就称赞车轮。我不是精神分裂，我只是明白，这世上没有十全十美的事。」

有一些精妙的评论：
「绝育手术证明的字好看」竟有一石二鸟之感。
「我真的有一头牛」我第一时间没有反应过来。
「只要你精分，就能逻辑自洽」
「这盛世如你所愿」关键在于反差。

颇有些入迷了，竟一时忘了一会有课。上课去也。

Entered on [2017-02-27 Mon 17:41]
**** 。。回来写两句
配置好了更新不上！什么鬼！
Entered on [2017-02-27 Mon 23:37]
*** 2017-02-28 Tuesday
**** 喵喵喵？？？
今天写了一大堆都没了？？？？？wtf？？？
而且是今天的一概没有？？


Entered on [2017-02-28 Tue 22:19]
**** what the fk？
而且今天记下来的题解也都没了？？？
什么鬼啊？？？
我脑子里一片问号


Entered on [2017-02-28 Tue 22:20]
**** 我日
用git把自己覆盖了！
checkout我以为是。。干啊。。居然是一个危险至极的指令。


Entered on [2017-02-28 Tue 22:23]
**** 无奈再写一遍
题解是没了
今天只做出了一题。

训练的时候肚痛，死去活来。抖动抖动面色发黑神色扭曲恍若某种怪物变形前兆。

大概是晚饭？也可能是早上的酸梅汁？或者是中午活活把美梦作死（梦到回到学校似乎要发生什么有趣的事情的时候我却因为细节太真而疑是幻觉[大概是一块娓娓道来有头有尾有名有姓的海报板]于是想从中出来竟真的破碎出来生生把一切搅碎）？抑或是中午起床后为了保持自己的状态到下午训练的一杯咖啡？又也许是训练时过于紧张急切的心情？

总之是来的突然，来的猛烈，而且是我第一次在外所受。

虽然晚上本该（本来我该一刻就可以上床的，该死的git把我文件搞炸了，我现在蹲在地上衣衫褴褛的打字）洗衣服写作业但是却失力毫无依托毫无支撑。
而且有点饿。
睡了。本来是打算扩大夜生活的。毕竟晚上的时间好多都没了，这学期的支配时间变得极为稀缺....结果首日就遇到这样的事情。

听闻父亲得了心脏病，有些担心（似乎又不是，回头问下）。


Entered on [2017-02-28 Tue 22:24]
** 2017-03 March
*** 2017-03-01 Wednesday
**** 今日
并无所为。

大致了解了二分的套路。居然能用ifdef。
我觉得把周二的题做了之后就可以写点作业了...感觉再拖下去会出事情。毕竟周五还有课...

晚上上网络文学课选修。老师要我们自己演讲表达。意外的听到了许多有趣的东西。有人讲生化危机滔滔不绝几致使下面人昏睡，安利电影，讲网络暴力，有人推荐三生三世电视剧从而引出两路大神（竟还有公众号写手）前来批判一番。

母亲跟我聊天：你和勖勉的现行志向竟意外精准的与儿时所写重合，梦想成真。我亦是十分惊奇。我当上了儿时所想的“电脑科学家”虽然与当时的思路有些许偏差（当时是要大屏幕大硬盘大，大大大大大，有些羞耻）而oo画画和导演两项竟全部命中不由令人毛骨悚然。

可惜沈不曾在儿时写下这般豪言壮语（又也许是不为人知），现在再想表达似乎已经变得困难阻碍重重--不再是平铺的二维甚或是一维结构而变成三维甚至更高的螺旋层叠自我衍殖的迷宫深处。
啊，迷宫深处是一颗心脏，他们说那是活着的（印象如此深刻却也只剩下轮廓）
文化的东西啊....（思绪走远，跑出去看了好久的访谈一类的东西....）

身体还是有些虚弱。先睡了。


Entered on [2017-03-01 Wed 22:08]
  
Ended on [2017-03-01 Wed 22:50]
**** 
Entered on [2017-03-01 Wed 22:55]
**** 
Entered on [2017-03-01 Wed 22:55]
  
   Ended on [2017-03-01 Wed 22:55]
**** 
Entered on [2017-03-01 Wed 22:58]
  
   Ended on [2017-03-01 Wed 22:58]
**** 小小的修了下org 看看能不能让他记录结束时间
Entered on [2017-03-01 Wed 23:00]
  
Ended on <2017-03-01 Wed 23:00>
**** 


Entered on [2017-03-01 Wed 23:05]
  
  

 Ended on <2017-03-01 Wed 23:05>
**** 


Entered on [2017-03-01 Wed 23:07]
  
  
Ended on [2017-03-01 Wed 23:07]
**** 


Entered on [2017-03-01 Wed 23:08]
  
  
Ended on [2017-03-01 Wed 23:08]
**** 


Entered on [2017-03-01 Wed 23:08]
   
Ended on [2017-03-01 Wed 23:08]
**** 


Entered on [2017-03-01 Wed 23:10]
   
Ended on <2017-03-01 Wed>  by 孙斗南
**** 


Entered on [2017-03-01 Wed 23:12]
   
Ended on [2017-03-01 Wed 23:14]
**** 尝试着调了调org
结果失败了。
这个最后结束的这个我还是得自己来更新（C-c ./C-c !）不知道怎么更新时间戳。。。


Entered on [2017-03-01 Wed 23:16]   
Ended on [2017-03-01 Wed 23:16]
**** 


Entered on [2017-03-01 Wed 23:19]   [[file:~/Desktop/c%2B%2B%20and%20acm/DI1_lesson/3/main.cpp][file:~/Desktop/c++ and acm/DI1_lesson/3/main.cpp]]
Ended on [2017-03-01 Wed 23:19] [[file:~/Desktop/c%2B%2B%20and%20acm/DI1_lesson/3/main.cpp][file:~/Desktop/c++ and acm/DI1_lesson/3/main.cpp]]
**** 对了
今天胸口的大瘤子破了，我花了一节课去挤它。现在创口很疼，而且没挤干净。还好我抖m。
另外今天妖风阵阵据说有八级之势。
我现在肌肉习惯快出来了。。到网页上查找自动C-f，结果毫无反应= =


Entered on [2017-03-01 Wed 23:20]  
Ended on [2017-03-01 Wed 23:24]
*** 2017-03-02 Thursday
**** 日记= =
今天下午打球，打到无神。
回来后跟沈打了会Portal2，各自觉得对方智商堪忧。
晚上把steam里的卡都推了出去，并且终于算是弄好了steam...然后洗衣服。

洗衣服好累啊！
虽然和我懒总是会把未洗的衣服堆积到难以忍受的地步有关....但我还是想说，好累啊！
感觉就像是上了另一节体育一样。

感觉。。怎么明天就又要训练了呢。。我当时的二分题才做了2/5，还有⑨个练习题没有做啊啊啊......好想好想花大块的时间玩啊...
大概也只能想想了

Entered on [2017-03-02 Thu 21:48]  

Ended on [2017-03-02 Thu 22:02]
*** 2017-03-03 Friday
**** 迷之被抓
被抓来当壮丁（观众了），第三届辅导员职业能力竞赛！无fk可说。
好在带了电脑不知道能不能写几个题，我的午觉我的状态条我下午还要训练啊啊啊
会场的灯泡还炸了好可怕。校外嘉宾嘤嘤嘤。无怪乎我们被抓来，又是一场唱给不存在的群众的戏。


Entered on [2017-03-03 Fri 13:43]  

Ended on [2017-03-03 Fri 13:45]
**** boom！
一导员在演讲到热烈时候仿佛助威一般天花板的灯泡boom的炸裂破碎。
看来灯泡的心情和我的心情比较相像。哈。淦。

Entered on [2017-03-03 Fri 14:54]  

Ended on [2017-03-03 Fri 14:57]
**** 于是变成闹剧
笑的不行。联系开始之前老师强烈的要求：一定要把手机静音！一定一定！！因为全程录像！！然后，灯泡炸了。于是有了辅导员在上面演讲，扫地工默默上台打扫，不停的左右摇晃实力抢镜。

Entered on [2017-03-03 Fri 15:01]  

Ended on [2017-03-03 Fri 15:01]
*** 2017-03-05 Sunday
**** 今天和昨天的
这两天一直在玩。昨天与沈do到精疲力竭，今天与沈战斗方块到虚脱无力。
说起来这两天玩的挺开心的。dota啊，战砖啊，各种自虐小游戏啊，steam+1啊，去steamcn淘宝啊。。。几乎一直在玩。。开心是开心了，就是感觉有点怠惰。
啊，周二的题没做完，周一的练习没做，周五的题和练习都没动。
好 烦 啊。
新的一周又要来啦！淦！照我这样别人在训练时就能写完的题我要做上好几天的样子不知道什么时候才能....

我忽然进入怨妇模式了...

晚上做物理实验的时候觉得好烦，想写个计算器。。。尝试了一点就弃了，真可怕。我讨厌模拟！淦！甚至还不如做acm题= =

自己给手机膜了一下，啊不，就是强行自己换膜，虽然不是那么尽善，但是还是满足了自己的强迫症。

刚才被强行在宿舍推了一波京东白条。感觉和那些在马路边上蹲守据点搭话的营销一样，强行消耗时间（当然我也遇到过不错的交流对象，不过那次毕竟是tm夜路被搭话。。。）（只是对我而言的强行消耗时间，对于他们可能就是未来和经验？

写了一篇拉低平均值的辣鸡日记。
你看看周末舍友还曾出去玩（虽是独身一人，但是他带了相机！），沈还在娱乐之余证出不少东西写了不少blog....
总的说这一周比较的迷。精神比较萎靡，打开手机qq没有人聊天就去翻群助手，从前那种打开手机就是pdf就是vjudge的日子一去不复返了（明明上课那两天又看233）。

Entered on [2017-03-05 Sun 21:38]  

Ended on [2017-03-05 Sun 22:09]
**** 还有啊
虽然分了类但是感觉没有什么卵用的样子23333.

Entered on [2017-03-05 Sun 22:20]  

Ended on [2017-03-05 Sun 22:20]
*** 2017-03-06 Monday
**** 疲惫的日记
老杨累的生无可恋需要治愈....只可惜我也累的生无可恋....
今天明天几乎都是满课，除了今天上午能够堪堪休息一个早上。

中午没睡觉，拿着新到的螺丝刀，抱着视死如归的勇气把电脑拆了看看，结果有个螺丝本来就有些花，我一拧瞬间里面就花炸了了，再也没法拧...无奈只好把电脑装了回去。
等壁纸刀再尝试尝试。

下午回宿舍的路上后颈一凉。我起初以为下雨，但是想想雨点的大小和周围并不是湿润的地面，感觉不对，摸了一把，竟有非常实在的触感。拿到眼前一看，手指已是绿油油的....
怎么说呢，被临幸不知是幸运还是不幸。

晚上用u盘的时候才想起来找之前的u盘，早已不知被我遗忘在了什么地方。总觉得我那些在我第二天就遗弃忘记的u盘的命途真是悲哀呢。

不说了，这个点了我才刚刚完成任务，虽然又困又累，可是明天还有比赛，总还是要做个题的吧。


Entered on [2017-03-06 Mon 20:58]  

Ended on [2017-03-06 Mon 21:12]
**** 啊，好舒服
热茶好舒服。
本来想喝咖啡的，想了想还是喝了茶。

Entered on [2017-03-06 Mon 21:32]  

Ended on [2017-03-06 Mon 21:32]
*** 2017-03-08 Wednesday
**** 稍稍平复了心情，回来写日记

新的学期课明显多了起来，现在我都是在上课的时候休息（玩手机）...

昨天比赛打的我爆炸。四个树还有几个题根本就没做，最后连资格也没有拿到---其实想想也是，自己的数据结构、数学都菜的一比。
我以为还没有当时沈学了一个月的时候强绝非虚言。
于是昨天就变得非常绝望非常疯狂，也不想睡觉也不想玩什么都不想做陷入浑噩状态。


这两天喜欢逛steamcn交易区，其实节约的成本与时间消耗根本不成正比，但却就是非常喜欢非常沉迷。满足的恐怕是自己的某种强迫需要吧。和春节人们不停的蹲守红包最后根本拿不到多少钱的那种感觉似乎有些相像。

弱啊，弱啊，弱啊。
而且陷入了一种好想玩->卧槽我这么菜怎么还想着玩->不行啊果然还是好想玩->....的循环中。
大概是自己过分的贪婪了吧，在两个方面都是，太想玩也太想变强。

想不起该写啥了。

Entered on [2017-03-08 Wed 15:54]  

Ended on [2017-03-08 Wed 16:06]
*** 2017-03-09 Thursday
**** 小记
最近怕不是进入了贤者模式，啥也不想干。
无心学习无心做题....
下午开了个两个小时的年纪大会，打乱了本来的计划。
不过无妨，本来计划也很少而且执行欲望很差。

听了沈一席刺探的关于泰山学堂大佬们的进度的话，那睡醒-翻谱-学习之生活，再比较于天梯赛都菜菜的划水的我，深感无力。

下午手机因为计划问题没电了，意外的过了几个小时没有手机的生活，感觉是挺不一样的。当然也和体育课完了之后整个人亢奋进入另一种人格有些关系。
比如我发现学校里的喇叭都放置在人烟稀少的路上，在主道上根本没有....不是很懂这样的原因。
然后是今天二食堂的西红柿炒蛋。我咬个西红柿入口下去不是清爽可人的酸，竟是馥郁凝滞的咸。那种感觉就好像吃到了母亲做的菜里常常出现的没有搅开的一大坨盐。

不说了，写个二分洗洗衣服看看时间玩一玩吧。
无休止的疲惫。


Entered on [2017-03-09 Thu 17:59]  

Ended on [2017-03-09 Thu 18:10]
**** 哦对了
补充一下，学校的机子有bug= =我的freopen不能用，然后我也不会复制粘贴（win下），我也对win操作非常僵硬了（C-eC-aC-nC-p都不能用！淦！）。。。。
不过最主要还是自己的问。TAT

Entered on [2017-03-09 Thu 18:16]  

Ended on [2017-03-09 Thu 18:16]
**** 好气啊
1h前我就已经写完了。然而现在还没对，根本不知道错在哪，我拿着题解一行一行对还是找不出来。。。好绝望。

忽然停水。
体育课之后不能洗澡我有一句mmp不知当讲不当讲。

素质八连。

Entered on [2017-03-09 Thu 20:26]  

Ended on [2017-03-09 Thu 20:26]
**** 淦
还没出来。。。已经红了整整一面了。
我还没写作业，淦！

Entered on [2017-03-09 Thu 21:10]  

Ended on [2017-03-09 Thu 21:10]
**** 解决了。。。
啊。
我感觉
自己虽然智障但是好歹好歹好歹终于终于tm的搞懂了。
总算没把自己强迫死。
刚才搞出来的一瞬间我都快憋死了。
我这个情绪繁衍酝酿有点厉害。
强迫症也是日渐加剧。
不过把气撒给同学了一些2333
不然可能就炸掉了。


Entered on [2017-03-09 Thu 22:43]  

Ended on [2017-03-09 Thu 22:45]
*** 2017-03-10 Friday
**** fk
一题没做出来好绝望
主要是总是觉得卧槽自己这个题没毛病啊，怎么就是WA呢怎么就是不过。
心态不说爆炸也差不太多了。
打了字又退回去，md自己真是废。无fk说。

Entered on [2017-03-10 Fri 20:30]  

Ended on [2017-03-10 Fri 20:30]
*** 2017-03-11 Saturday
**** 昨天好像忘记写了
光顾着感概昨天训练的事了，这两天倒过的有滋有味。
比如我现在只着一条内裤站在椅子外面随时等着他们把澡堂空出来然后去抢。

说正事。
昨天去看了《Logan》，第一感觉是狗屁删减版。第二感觉是，啊，莫名的沧桑。
我不是Xmen死忠也不是金刚狼死忠，我没看过（也许看过但是却没有印象）第二部金刚狼，不过我好歹看过xmen全部（哪怕当时只是冲着超级英雄冲着超能力冲着刺激冲着爽）但是英雄迟暮，不复当年，举步维艰。博士走了，logan走了，总是觉得好缺憾。但却又是开头其实就预料的到的结果。
简单的故事，还有多处的致敬，平淡却使人泪下。
「至少还有水」
「至少还有水呢」
「原来死是这种感觉啊」

无情的工作人员在演完之后就喊「没有彩蛋」，他们不懂啊，不懂观众们就算知道没有彩蛋就算知道有些事不会发生却还会默默的坐在那里等待还是希望他还在，他们还在...
说起来我听说片方为了提高排片率居然砍了结尾滚动字幕的6分钟...加上工作人员的喊话让我不得不有些寒心---就像那些让位于娱乐让位于利益的媒体一样，令人不快。


犯懒啊。日记都不想写。

拖着拖着就拖到了今天。

昨天上午玩泰坦，中午玩dota，下午去陪着同学打了打球（却是不曾料到今天会下雨），生活竟是犹如我印象中的一样美好。
只是有时空间里会有大神发一些奇妙的说说使我意识到自己的落后与羸弱（知耻后勇...）
有时也会想起，啊，天梯赛没有过诶。明明只是上周二却是有过了一个月之久的延伸感。

今天睡了懒觉，中午起来看dota比赛，也是蛮开心的。
淦。
所以我到底是该开心还是不该。

另外老杨周五告诉我她找到了求知欲，找到了热忱，感觉那就是我刚开学的那种感觉（还有假期玩emacs2333）。
啧，现在怎么没了呢。
一身的怠惰。
还有玩性。


Entered on [2017-03-11 Sat 19:06]  

Ended on [2017-03-12 Sun 16:20]
*** 2017-03-14 Tuesday
**** 又来水日记啦
因为水了节训练...
除了一道不是图论的还会做以外，就没有会的了。

昨天没记，也没有啥。晚上科协课教dp，然而做一道dp变形做不出来。就是lcs记录路径然后递归。。。最后差不多就是照着题解写的
递归反人类！淦！（然而一般题解都会说：递归的过程就是正向的非常简单）

今天图论，被各种方法支配...spta kruskal bellmanford dijkstra...
无fk说。
“这个题只要最小生成树跑一遍就可以了”
“这个题就是个负环，有很多做法啊随便选一种就好了”
然而最可怕的还是我听都不能听清的诡异名词......
啊。
啊啊啊。

回去再写= =


Entered on [2017-03-14 Tue 21:02]  

Ended on [2017-03-14 Tue 21:02]
*** 2017-03-15 Wednesday
**** 班会
头一次知道还有班主任，以前以为只有一个辅导员，没想到还有一个班主任...
而且居然是个非常强的班主任。
教c,java,py....
意见是好的，忠告是非常及时的，再一次给我敲响了警钟，也启发了我一些东西。
真的，太好的。

迷之小さなてのひら。
忽然觉得自己还好小好年轻。

淦，我这就去学ToDo然后列计划去。


Entered on [2017-03-15 Wed 14:41]  

Ended on [2017-03-15 Wed 14:46]
**** 补充
瞎感慨了一番。
说起来就是。
1.stitp项目要早搞，在大二上，一开始就要着手
2.论文和专利能弄就弄。专利不好搞，论文。大二下？
3.不要沉迷游戏
4.中国大学mooc....休息时不要去打游戏，去看点喜欢的东西。
5.一定要变强，一定要变强。

Entered on [2017-03-15 Wed 14:48]  

Ended on [2017-03-15 Wed 14:48]
**** 回去了！
肚子有点疼。先回去了。
晚上课不去了。辣鸡选修（好像要看左耳，我的内心？？？不如打游戏呢。。浪费时间也到不了这个份上）。

我把下面那个时间戳改回去了，看的不习惯的就右上角raw\blame切模式看好了，再不济仓库首页左上角commit看更新。（别真的改啊2333）

我到各种地方搜索都是C-f，也是醉。
再看一会C-cC-c的重复配置能不能解决就走。。


Entered on [2017-03-15 Wed 16:12]  
Ended on [2017-03-15 Wed 16:23]
**** 不做人啦！
摔！还没弄好！不弄了！

Entered on [2017-03-15 Wed 16:56]  
Ended on [2017-03-15 Wed 17:00]
**** 。。。
还以为终于可以a题了，结果超时了。。。
无fk说。
计划里是做三个题的。。结果只做了两个（这个还没a），虽然知道了yasnippet这神奇的东西不过还是觉得，不是很赚。（比起左耳当然是稳赚）

跟棣文聊了聊，发现他依然保持着他的活力而我垂垂老矣，在诸多方面....

买了个一百元的手柄，这个月预算没有了（本来就被我因为发现了steamcn而花去了许多买游戏。。。）。沉迷于买游戏。。。没有前几天那么热衷了

Everything goes wrong to turn into the way of life
随到了The Letter - 啊，人品真棒。

上床玩会手机睡了。


Entered on [2017-03-15 Wed 22:59]  

Ended on [2017-03-15 Wed 23:06]
*** 2017-03-16 Thursday
**** 今日
沈：人类啊，都是一样的，需要消费，需要释放。

早上起来之后进入虚无的无事可做模式。
发现南二食堂不知道比南三高到哪里去了，不论是早餐还是中餐。
早上喝豆浆真是满满的享受。

淦昨天晚上和沈打了会游戏忘记写了。
沈进入了和我类似但不同但是他非常狂躁而我不然的空虚状态（不过今天好像恢复如初变回dalao）。
手了把卡尔随了把卡尔，打的很开心。

不过估计今天的题我就都不会了。毕竟邹...出题。
无妨啊2333，毕竟以前也是，划水...签到...然后拓展一下视野知道有啥要学的。
只是欠下的越来越多。

今天手柄到了，好激动好激动。
玩了一会手感不错，就是我没有一些act大作比较僵硬。
好开心啊。

啊。原以为这周状态会好一些的（其实就是好一些啊，好说歹说做了三道题。。虽然周四僵了，之前还是蛮不错的）

让我数一下。。
- dp 欠下几个亿
- 图论 还没开始学
- 数学几个小题题
- 唔 二分好像只差几个练习题了！终于在三周之后做完了第一次课的5个题orz。
好消息是下两周是好像会很闲的实验周。

啊不管了。
熬过晚上再说。
啊手柄到了好开心。
啊精分好爽。

Entered on [2017-03-16 Thu 21:39]  

Ended on [2017-03-17 Fri 17:13]
*** 2017-03-18 Saturday
**** 好困啊
早上本来约好去和学姐打球的，偏偏昨夜有雨，只好作罢。
只是可惜我起的好早好早。

没想到老杨也会有绝望迷茫的时候呢。

昨天上课也好绝望啊。虽然很短，但是很绝望。
图论什么的还是有点远啊= =我现在连个二分都要做好久，在知道思路的情况下...


Entered on [2017-03-18 Sat 11:09]  

Ended on [2017-03-18 Sat 11:27]
*** 2017-03-19 Sunday
**** = =
这两天差不多一直在玩吧。。
虽然今天有做一点题。。不过没做出来和没做一样= =。。。

Entered on [2017-03-19 Sun 21:45]  

Ended on [2017-03-19 Sun 21:45]
*** 2017-03-20 Monday
**** = =
我放弃了。。
写两个有序数列的新数列死活写不对，两天了还没弄好，照着题解一行一行的看也不得要领，也不想重新写，就是想知道自己哪里不对，就是想知道为什么，然后不停的错愈发烦躁。。。
蛋疼啊。

污点啊污点，和上次那个数列一样估计要以后再写了。

Entered on [2017-03-20 Mon 10:31]  
Ended on [2017-03-20 Mon 10:34]
*** 2017-03-21 Tuesday
**** 好像昨天没有写
今天讲概率和期望。第一个题我都做不出来。
数学不好。
十分绝望。

近来总是会想起：啊，这个应该记一下啊。
然后转头就忘掉了。

蚊子并不像前两天一样无时无刻光顾我了（手心都两个包仍在）

学校里开了许多奇怪的小花。

啊听课去了

Entered on [2017-03-21 Tue 20:27]  
Ended on [2017-03-21 Tue 20:38]
**** 卧槽我的emacs没了
炸了炸了炸了
什么鬼啊。。
= =迷啊。

Entered on [2017-03-21 Tue 21:14]  
Ended on
**** 啊哈哈哈哈哈
让我就用了一小会就又配置回来啦
不过yas还是没弄好，回头再说吧。
org还是得用才行。。
我想恢复hexo啊= =淦不过最近没空
明天起来把辣鸡matlab7.0配置到windows上。。然后看看能不能把yas配置好。

啊 好累，今天的概率又划水连听都没听懂，睡了

Entered on [2017-03-21 Tue 22:50]  
Ended on [2017-03-21 Tue 22:53]
*** 2017-03-22 Wednesday
**** 啊
被安利了一把好贵的伞哦
每天过的省吃俭用精打细算的似乎就是为了大手大脚的一刻。
不过还是好想攒钱，好想省下每一点钱啊。

其实对时间也是一样的啊。
设置各种emacs为的就是效率和手感啦。
不过说起来我浪费的时间真是一点不少（浪费是重点），比如各种强迫症必须做出一道题来然后一晚上啥都没干......

唔。今天下午开始下雨，下午开始上课....逃了那个讲网络文学的破课233。

这周是数学实验，就是讲matlab的使用。结果老师被迫把matlab课上成线性代数课2333。啊不过还是蛮好的，不用写作业不用这个不用那个啦。


Entered on [2017-03-22 Wed 17:54]  
Ended on [2017-03-22 Wed 18:01]
*** 2017-03-23 Thursday
**** 咩哈哈
今晚还行。
实验周的课结束了，好好的玩了玩。
明天也没什么事，睡个懒觉做两道题，然后使劲玩玩好啦（天梯赛前休整停课了。。反正除了前三节课还算能听懂从图论开始就懵逼了好吧。下节课字符串肯定也是。。）

上个周末玩都玩出了贤者模式2333。

哦对了，matlab还是蛮有趣的...不过玩的多了还是有点僵硬，是一种不自由感...翻来覆去净是那些东西（而且小数精度问题丝毫没有改观）。嗯比起c来毕竟少了些东西，也多了些东西，毕竟数学方面更强了。
而且我总是会想到切片什么的。。。
就想到抽空要学haskell啊。py也是半途而废啊。

...想啥都能想起自己欠下的账。

Entered on [2017-03-23 Thu 23:55]  
Ended on [2017-03-24 Fri 00:01]
*** 2017-03-25 Saturday
**** 日记
今天下午我和妹子联机打游戏了！23333虽然是并不熟的打崩坏认识的妹子
不过还是很开心的。

终于把数学实验（算是）写完了。

有个舍友爱好天文，今晚地球一小时活动观星到11点才回来，觉得有一爱好确实很好，能够平衡疲惫的学习的自我。我现在比较欠缺这个东西。若非要说打游戏是我的爱好总是觉得，像是明明知道自己是却还是止不住自己吃和玩的欲望的肥宅

然后有个舍友去魔都玩了。
我觉得他们都很强啊。

Entered on [2017-03-25 Sat 23:32]  
Ended on [2017-03-25 Sat 23:58]
*** 2017-03-27 Monday
**** 啊 好累
今天做电装实习。
早上因为这两天睡的太晚而没有起来。若非舍友不停的电话call我，恐怕我今天的实验就玩完了。
然后一天都在焊电阻啊什么的，中午一度被“红黄蓝绿”“红红黑棕”支配（分电阻分到怀疑自己是色弱）
说起来，组装电表什么的对于动手能力为负的苦手来说竟然并不显得多么难。虽然还是要经常向左右之旁的同学们请教，但是似乎，只是似乎，某些执着的念头没有以前强烈了。（虽然还是有时会想电烙铁什么的但那是思绪飘忽，并不会想：啊，我要是没对上怎么办，啊，我要是不小心烧坏了这个怎么办，啊...if...）
也可能是因为循规蹈矩步步为营，并无太多动手操作之要求吧。

一天都坐在没有靠背的椅子上比周末在电脑前玩一天还要累的多。
啊。

想玩游戏。想做题。想睡觉。
洗完了澡，上床了

Entered on [2017-03-27 Mon 21:25]  
Ended on [2017-03-27 Mon 22:05]
**** 哦对了
昨天就是玩啦
昨天还水了几道题

今天中午我只穿了两件单衣却感到非常热。我觉得令人绝望的夏天就要来了。
不过春天还是挺舒服的。

好了苦手这回真的要上床了。

Entered on [2017-03-27 Mon 22:07]
Ended on [2017-03-27 Mon 22:15]
**** 淦
我又回来了
我想起来那天沈给我发的山东无期的那个事，回头得好好研究研究。啧啧啧。

Entered on [2017-03-27 Mon 22:18]  
Ended on [2017-03-27 Mon 22:19]
*** 2017-03-28 Tuesday
**** 完了
动手苦手昨天晚上临睡觉犯事了。
我把手机掉到了水里，想晾一下电池，误以为是以前的手机强行把后盖拆开，拆开后发现一片陌生---它好像不是这么拆的，它好像坏掉了。我再装回去的时候发现外框都变形了。。。TAT
啊，昨天晚上我就想着无有手机的优劣就睡着了，
晚上做的梦都是和手机有关系的--跟父母通话，跟同学通话，虽然都是很奇怪的通话方式。每次故事的开头都是我醒来发现手机好了，起初我以为是梦，之后我就习惯了---已经忘却了自己是不断醒来的事实。
然后早上起来发现手机还是坏的。啊，为何不能有柯尔律治之花。

好了来列表。
***** 优点
+++++ 省去大量“辣鸡时间。
++++ 使自己不会处于不断的信息膨胀中，不再处于持续的焦虑中，可能会因此得到些许宁静
+++ 聚焦在外界事物之中
+++ 可能能改掉自己无事抬手机的习惯---这个习惯虽然是近期才有，但却已经到了入髓的地步：格式固定，看qq有没有消息、看qq群有没有什么消息并逛一逛、打开网页逛steamcn\打开max+看数据直播。
++ 使手机退居次位，mbp上升到极为重要的位置---随身携带。
  -- mbp携带率大大上升，损坏的可能性上升，我的焦虑上升
***** 缺点
---- 消息滞后（不至于失联人间）
   ++ 消息滞后，未尝不是好事。（其实我觉得失联也未尝不是好事）
---- 无法使用支付宝
---- 无法验证手机相关之事--邮箱 steam qq....等等
-- 无法打手游
   +++ 无法打手游（淦，到底是好是坏）
--- 无有方便的计算、查询之工具
--- 无法看pdf、看题（不过这学期干的确实少啊，上了头才会干这事。。）
-- 无法外卖


好了就这样吧。后天之后就差不多是放假状态了，就可以去修了嗯。
先享受这段时光吧。
我什么时候能失联呢。...我为什么会想失联呢。

日常叨叨-昨天科协的课都停了，因为我们不做题争彦大大很生气。
做题啊，做题。

Entered on [2017-03-28 Tue 06:44]  
Ended on [2017-03-28 Tue 11:52]
**** 淦 辣鸡字符串
做了半天第一个没对
真的是烦啊。。做到昏昏欲睡。

Entered on [2017-03-28 Tue 20:16]  
Ended on [2017-03-28 Tue 20:18]
*** 2017-03-31 Friday
**** 啊又要划水了
一道不会....
TAT
这两天算是放假吧。。明天上课。。比较迷的安排
之后还有清明放假。
啊，然而这两天一共没做几道题还都是水题....看了看树和dfs，感觉，还是有那么一点僵硬。还是得做一些相关的题。

唔，手机修好了，不过没有原来好用了。
嗯，以后也少玩手机啦。


Entered on [2017-03-31 Fri 19:44]  
Ended on [2017-03-31 Fri 20:00]
** 2017-04 April
*** 2017-04-04 Tuesday
**** 啊 好久没写了
写日记的频率一定程度上反应出丧志的程度。

最近其实本来应该好好学一下的。结果昨天出去玩被满街满景点的人锤了回来，今天憋在宿舍把DAC看完了，还写了点作业...
哎。

是这样的。5月中旬会有两个省赛级别的比赛，然后我本来是打算看大佬们去表演结果莫名其妙被不认识的学长拉进了组去划水...感觉自己完全配不上，树啊dp啊这种比较基础的都不行连搜索都才刚入门.....压力有些大。

结果还是把假期划过去了啊。

手机勉强算是修好了吧。对了，我昨天出去的那趟，甚至还没有我去修手机那天出去的愉快。
坐地铁让座，却被哪位鬓须见白的爷爷数落了一番，说什么年轻人不应该让座，学生啊年轻人啊都那么累，就该坐着，让他们站着云云....振振有词，夹杂着一点江苏的口音，我只能笑着点头，（一开始我以为是他认为自己并不老，听着听着觉得不对。。。）

感觉自己该去图书馆缓解缓解心情...老是处于焦虑之中，不愿学习，玩也不能得意，感觉似是回到了高考啊啊啊。

今天晚上先尽我所能的写些作业吧...明天，下午无事，看看能不能去图书馆看点书。

最近真的好热。
昨天出去玩，倒是看到好多放风筝的。想来我小的时候却是没有放过风筝。仔细看看，放风筝的大部分是老头，剩下的是一些孩子和带着孩子来的父母。想来也许在将来这些东西就变成历史变成书里的东西了吧。倒也许不会....可是我和这些东西打交道的时间长了，总是会有以后也许真的连书都没有了连童话都没有了的错觉在。转念想起那些在我原来住的那边的会展中心（其实就是广场）的台子上一堆老头在玩空竹和陀螺（空竹这个名字我在记忆里搜寻了好久好久，最后还是在网络上翻看的时候猛然间记起的），大概以后我们小时候玩的弹珠、摔板、卡片乃至悠悠四驱都会慢慢的消失在人们的视野中，消失在人们的记忆里吧。就如同我无从想象我父亲的童年诸如掏鸟吃窝窝打弹弓一样，后代们无从感触先辈的经验与时代本身，这可能就是骆以军所说的那种，活着像一支驼队的感觉吧。无可奈何，又恐惧觳觫（这两个字，是杜汇鑫不停的教我我却仍旧不会写的两个字），看着前面的倒下又继续领队向前。
没想到时隔一年我还是能想起这篇文章。
是不会多余的啊。

哦对了最近其实挺迷的。我跨进门之前还想着的事进去就忘了。一周前是父亲的生日，我从那天就记得要写个啥或者什么，转眼忘了，第二天想起来转眼又忘了...如是反复直到今日。
就像我明明记得有好多东西要记的...

Entered on [2017-04-04 Tue 21:28]  
Ended on [2017-04-04 Tue 22:39]
*** 2017-04-05 Wednesday
**** 啊好疼好难受
胳膊疼。。。
是那种时断时续的疼，有的时候我都会忘记或者以为它好了。
可能是晚上凉到了或者是压住的时间太久...我不知道...

晚上想了想还是去上了那个网络文学的选修，发现还是好水啊。任凭它吹的天花乱坠还是怎样我可能都不会去看吧....
而且会有迷之优越感= =

下午看了点bfs，胳膊疼的看不进去，就4点多去喝了碗馄饨，然而并没有好转...

晚上支持我写作业的动力恐怕就是ギリギリ愛了。虽是过期之毒不过还是很有用的。
一会看看白书睡觉了...

Entered on [2017-04-05 Wed 21:54]  
Ended on [2017-04-05 Wed 22:03]
*** 2017-04-10 Monday
**** 都已经忘记上次是什么时候了
赶紧趁着多余的零散时间写一写。

上周的状态还好，将将做了几个题。
周五周六又是一通玩，昨天倒是比赛做了好久的题，也是补了不少的东西...什么背包啊，快速幂啊，好多东西都忘的差不多了。
明天又有预选，估计是过不去了要划水了hhh。
比我想象中的来的快啊。我以为怎么着也要到四月中下旬的。

这几天南京骤然变冷，还止不住的下雨。我又减缓了更换衣橱衣服的计划。

两天前又拾起了好久好久以前，我疯狂的痴迷的猎命师。犹记得在那个手机还不是触屏的年代，我在（去哪里的已经记不清了的）火车上日日夜夜看猎命师，一遍又一遍，母亲担忧又愤恨的说我，我依然如故...
单从猎命师这一文来说，我绝不否认他的功力和想象力。只是九把刀这个唬烂的作家的风格竟是有几分与骆的神似。这样却也能解释当时看西夏旅馆时对语言的执迷与熟稔...

这恐怕也是丧志吧。
新的学期真的是丧志了好多。闲暇本就已经被压缩还让我这样的挥霍...

大学可能就是这样的彷徨吧。一往无前的追求自己想要的，对我这种没有千军万马没有无惧只有优柔寡断这种情绪格的宿主来说，可能还是有些困难吧。（也可能是自己想要的太多然后迷失了方向hhh）

哦对了，说来可笑，昨天卡在快速幂的一道题和一道叫“小学生都会”的题上，眼睁睁瞧着别人都a过了自己死活不能过然后心态爆炸就不想做了。
就这样吧，我去吃饭一会上课讲昨天的题了。

Entered on [2017-04-10 Mon 17:12]  
Ended on [2017-04-10 Mon 17:20]
*** 2017-04-13 Thursday
**** 哎....
周一上课也是好多都没听懂，概率与统计确实不好...

周二就迷一样都出了好多期望题，我们就签了个到差点做出另一道（向下取整写为四舍五入..害得学长疯了一样都怀疑算法..明明是题目没写完整嘛）然后错失了去湘潭（淦，居然是湘潭，我也是今天写日记的时候才忽然想到，淦，居然是湘潭）打ccpc的机会。
啊，这么说两个省赛级别的玩意都没选上啊。天梯也没选上，蓝桥杯都没报名...这段时间...好气。

还是继续开搜索的好。
周日周二连续两天搞得我昏头涨脑，生无可恋。

昨天被迫去搞了会access和sql...毫无进展。只是感觉他们没那么难...
好啦我再去学一会就要去上课了。

Entered on [2017-04-13 Thu 08:43]  
Ended on [2017-04-13 Thu 08:51]
**** .....
ctmd辣鸡学校oj，我写%lld就算错，写%I64d就对了。
而且i还要大写...让我这种从来没写过i64d的情可以堪

Entered on [2017-04-13 Thu 09:00]  
Ended on
**** .....
然后不出所料的，小学生都会的那个题也是lld的问题。
5555555 无怪乎心态爆炸
（懒得切到acm里去记了）求逆序： if(x&1)r+=1<<(15-i); x>>=1;(i=0:15)
开心 上课去

Entered on [2017-04-13 Thu 09:18]  
Ended on [2017-04-13 Thu 09:20]
**** 今天
今天奇热，下午上体育的时候好多人都身着了短衣短裤。

不过今天从下床始我就止不住的涌上疲惫。走在去体育场的路上感觉身体的能量在一点一点的蒸发。
体育课上练习上手发球，两边互相扔球。就几轮的扔球我就已经脱力了。
体育课最后还要跑5圈。跟着大部队慢跑3圈再以自己节奏跑2圈。我死命跟上了前三圈，第四圈进入龟速慢跑状态。我的身体已经几乎失去了平衡感，如果低头看自己的影子便有向前倾倒的趋势。我却在这种极度乏力的状态下意识十分清醒，就像晚上睡觉时偶尔会出现的明明身体已经想睡到了极点脑子却异常兴奋。（我好想写就像千年一败的最后一战回光返照道心归一，清晰的感触到周围的一切的佐佐木小次郎）那个时候我感觉我可以想出一些绝望的美妙比喻或修辞法，只是我的胸口和身体发出的撕心裂肺的哀嚎不停的把我的意识游移回现实。
之后拖着烂泥一样的身躯，我缓缓走回宿舍。。

回到宿舍就是回到了娱乐的世界。
身体已经说不出话来。
脑子也不想转。
被迫的写了会作业和c语言的作业（啊，c++果然和c不同，也果然和acm不同。acm用到c++的可能只有模版和stl容器一类的吧，其他的c++那些面向对象的特性一点都没有用到hhh）
啊。
啊。。

不知道老杨在今天的什么时候提出那个好久以前我看到却一笑而过的问题：如果有一天只能靠烧书取暖，你会先烧什么书？
许是因为太久不看书，心境的变化，我竟觉得这个问题毫无意义...换做以前准是心中构想出一套既能装逼还能讲出门道的书单；或是按照骆以军那样构想出两个人，相互在末日中幸存烧书，互相似乎有默契似乎在比对似乎是接龙的一本一本的...看着燎烟淹没自己与对方；又或者是像圣徒看着每一本被烧的书心中感同身受的灼烧着痛苦着，甚至说不定会在一片绝望中自裁也不愿伤害剩余的书；也可能是一份极度绝望毁掉世间最美好的一面的清单与书的死法......
但现在不会。现在我只会去想，啊，有好多书啊，啊，有好多书我还没有看啊。我只会去想，“信息爆炸”，如果把那些论文、媒体、网文，如果把那些自媒体全部算进在内...
只会去根据最近的经历（看了九把刀的猎命师）想到：啊，还有这么多唬烂豪洨瞎搞鬼扯乱写的作家，有那么多稀奇古怪的摆在热销平台却毫无价值的书，有那么多利用人性写的乱七八糟没有营养的书（比如什么超现实！不可思议balabala；你不得不知道的balabala你应该balabala；冷知识；灵异事件精选...我只是说一下我还有印象那天和小陈一起去新华书店看到的诸多乱象）怎么可能烧的完嘛的我渐渐退化为一个平凡的无志青年。（不过总比江丰会想到烧本子好得多）

不行了我再怎么兴奋也撑不下去了，虽然明天的c++实验内容没写完...明天再说吧。这已经接近两周的校队停课怎么样也要好好的享受享受....（或者是给自己更多的....折磨...自杀之路嘛2333..）

Entered on [2017-04-13 Thu 18:25]  
Ended on [2017-04-14 Fri 00:07]
*** 2017-04-18 Tuesday
**** 啊 摸鱼了好久...
不训练也不自己做题感觉自己天天鬼混摸鱼。（算下来我好像除了有一阵研究了下搜索这两个个月来没做啥..）
周末的时候电脑让我玩坏了送去修了...月预算爆炸。

我大概就是那种，即便没有烦恼也会自寻烦恼的人吧...
摸鱼都不能好好摸。
一定要找个理由，最棒的理由就是：我学了好久啦 我学累啦。然而现在没理由的怠惰摸鱼就会很难受，摸鱼之余随时感到不适与烦躁。
花钱也是啊。
这种非常矛盾的心情却让我想起了一点干系都没有的周一在台上高谈道德的思修老师。然后就想起了那些奇形怪状的电车难题。不过那就是另一个很有趣的话题了（关于为何会出现，为何会恶搞，为何如此邪恶...）。

校赛大概要爆炸了吧。这段时间我何止是没状态...简直就是...大脑中回路全部如车祸现场扭曲混乱起乩。
啊，对，还有那之后的期中。

周末的时候校庆活动...先于图书馆前的空地上看看不到的演出，听听不进去的演讲，然后...跑跑不下来的步。
说起来他们居然还把那个上了春晚的老红军请过来了...哎..那么大年纪也是不容易..
我根本就没跑下来啊哈哈。
连跑带歇再而衰三而竭的我后来就一直在走了..心想下午还要去找修电脑的..不过身体是愈发的向一个标准死宅的方向前进了，无体力无力量无韧性无忍受能力...

猎命师有点烂尾啊...臆想中的超级混战确是发生了不过义经死的太快..还有一些不科学的强的什么美杜莎（全场无区别石化..）塞壬什么的（控制阿不思什么的...过分啊）结果都被个百手人屠莫名其妙的干了。看的很不爽啊。
其实我觉得在大决战的时候就有点僵硬了...因为太想顾及全盘而丧失了主线，因为太想完满而把人物稀薄。因为太急着想结尾把前面好端端的坑强行填满...
前面的铺垫真的很棒啊，干，为什么要烂尾！好好写啊！
干啊，根本不是有点啊！我tm很不想说但还是要说啊！
从时间区就烂了啊，烂了啊，烂了！
早要烂就不要把前面写的非常有趣啊！
睛明变成打酱油的，雷力为了使人类的分量更重强行强，牟庆打了酱油，诸猎命师脸谱化变成放技能的法师，凯因斯莫名其妙的变成了极致白烂变态，伤心拔刀强行参战，上官主角光环笼罩，到后面人物没有了心理描写，一点都没有了，前面的铺垫一点用的没有，只剩下流水账一样的打斗，我只想说你tm写了个...
童年的回忆画上了不完满的句号，这样很不爽啊！

算了算了，今天最好上课（虽然我满心不情愿，但是在不训练我要废了），然后回点血吧。感觉自己摸鱼要把自己摸死了。

Entered on [2017-04-18 Tue 16:01]  
Ended on [2017-04-18 Tue 16:50]
**** ...
哇的一声哭了出来
成了一道题没做出来唯一一个被零封的。

Entered on [2017-04-18 Tue 20:32]  
Ended on [2017-04-18 Tue 20:33]
*** 2017-04-22 Saturday
**** 啊明天要比赛考试啦
好紧张啊好紧张啊。因为没有复习没有准备啊。

感觉自己在队里就是蹭的。。那么多东西不会也不去补。今天做二分还差点没做出来（我觉得好多时候我还是认不出二分）（vijos的数据真是没话说的恶心）

就像我对沈说的：明天比赛再沮丧一下 然后稍稍振奋精神再学两天 然后继续进入无主神游状态。

今天又找了好多泽野的歌...说不上来吧，可能坦克打多了，习惯了腔调。

周五去修电脑，中午出去转了转，从浮桥走到了鸡鸣寺，骑自行车回浮桥的时候还在七拐八转的胡同里迷了路。穿着短袖（后来我发现我那一天的上衣都是反穿的）短裤，凉风拂过，林间大道般的马路，倒是感觉很好。

拐到鸡鸣寺路口有个老头叫住我，要和我聊天。说是聊天其实是给我相面。我倒是没经历过，也就甚是配合的演了演。
他从脸型，鼻梁，嘴唇（不知道他有没有从我反穿的衣服那看到什么）进行种种推测...不过居然多为恭维之言，什么有能力，不与人争什么的，然后提出要看手相，并要收钱。他说，他们祖传看这个，原先有一所工作室，但是因为写字楼太贵，迫不得已就下午出来，上午在网上给人看...
比较有趣的是在他提出每一点的时候他都要加一句“我这样说你还明白？”，仿佛我的人生命相都已经注定甚至即使发生过的也应该按照他所说的那样，要我明白。
我跟他说我很好斗。他先是微微圆斡：好斗是纠缠到底分出胜负，继而说我一定不是好斗的，在我一再的坚持下变为我相较于那种暴烈之人算不得好斗。
感觉当时应该让他算一算看一看我的手相的。哈哈。

我到现在还是不很会拒绝别人，一般都会找一些看似非常好的理由：比如如果有人推销，我会拒绝以穷；如果有人推荐班，我会说我有竞赛我很忙；上次去修电脑，他推荐我再装个机，我觉得他给的配置并不好，而且他有些过于急切的想让我装机（我找了理由之后后来更明显），我就不想装，却不是直接拒绝，而是佯扮出十分委屈家里人不给钱的样子（演技倒是进步不小）。

睡觉啦，等待明天等待我的灭亡了。

Entered on [2017-04-22 Sat 23:36]  
Ended on [2017-04-23 Sun 00:06]
*** 2017-04-23 Sunday
**** 啊。
闲下来写日记。舍友都睡了，游戏我也玩过了（半个小时轻松愉快），考试也考崩了，比赛也比完了。

比赛...怎么说呢，水的题是水，不水的题干脆没法做，然后剩一两道恶心的题拖时间= =...
不过这个扎气球挺像回事，做出个题就放个气球，倒是挺正式。我说事先为啥要找志愿者，原来就是分发气球的。。。
就是。。学校的这个气球。。会炸。。做着题注意集中的时候突然boooooooooooooooooom来一下，简直不要太sweeeeeeeeet。而且听它爆炸的声音，竟然非常结实和强劲，好像在说他的质量非常好一样...
嗯。还有就是比的时间好长啊，我也没带吃的（我也没法像旁边的心乾dalao一样吃物无声），然后有耳机却没有歌可以听也是好烦啊（什么时候比赛的时候可以听歌啊啊啊），全程都是我脑子在以一种奇怪的方式循环我上午听的几首曲子，说真的没有我就要死了啊。
说起听歌。。听完东离的配乐忽然好像看东离啊。（说起来斩服我也是先听的歌后入的番..听歌入番..）
最后只做出4题= =有个题我训练的时候做过但是我就是死活想不起来怎么做了。。倒是能想起那天那时候我在神游。
嘛。感觉还好啦。正常发挥吧，虽然j题有点迷，c题没记住。

然后晚上考高数，血崩。刚看的笔记本的题就记不得，刚看的公式就记不得。。可能是内存满了吧= =

去学科楼的路上开了一片小花，好棒的。

上周四复又听到老杨和江丰的声音，感觉十分的幸福（我大概是有声音控的病吧..讲真从老杨的哼歌我就表现出了异乎于常的兴奋与幸福..）（甚至可以说从..到..）。彷佛两人依然在我左右...就是听的感觉老杨好累（所以我也不能犯懒啊，大家都在努力都在奋斗）。

帮杰哥dalao改了改程序，感觉工程好烦（也可能是我没有下决心踏进去）。

ThreeFiveNineFour!词好曲好!意外收获!(我昨天当时是去找BL∞dy f的，顺便收了一波泽野2333）

今天脑子不太好用了，记不得还想写啥了
晚安。

Entered on [2017-04-23 Sun 23:46]  
Ended on [2017-04-24 Mon 00:36]
*** 2017-04-26 Wednesday
**** 啊。。怎么这么晚了
本来是一个美好的，没课的（其实有但是压根不想去的辣鸡网络文学）下午，怎么就没了呢....睡了一觉，起来疯狂改程序，中间打了半个小时游戏，吃了个饭，写了会英语作文，然后中间的中间玩玩手机...一个下午啊，活生生的一个下午啊。

这两天一直忙着帮杰哥做程序orz...c语言做一些界面之类的东西是真的僵硬啊，它太不灵活了，我做个能刷新的计时器需要多线程+5个全局变量控制两者关系...我的天，头疼死我了。原来用的sleep根本行不通，辣鸡c就没法动态的处理东西（就比如获取一个10s后的状态...）...多线程根本学不通，刷新屏幕也是强行设置坐标printf覆盖，简直了...做了足两天，差不多把他那个程序重新写了一遍，把结构逻辑都改了一遍（话说用switch做重复工作很反人类，明明一个数组就能解决orz）
哎，都是泪。主要是辛苦，还有就是要思维上各种绕，绕过无法实现的地方，绕这绕那...感觉底层真tm，真tm。（其实我想的是一身抱负无处施展，转念想自己现在还没啥抱负233）

前两天把于柳惹到了orz（再再之前还用差不多蠢的方式惹了小染）...就复又想起那个棣文很久以前问我的一个问题：怎样才能变得自私？我无言以对。现在想想这家伙在志愿者协里混的风生水起不亦乐乎倒也是不错。（咳跑题跑题）从来不会从对方的角度考虑问题甚至根本不会考虑对方的想法感受就口无遮拦的提出自己的观点意见（虽然我很想狡辩说自己是很替对方着急才..）
于柳：体会不到别人的感受挺好的。说起来好笑，我很在意别人看我的眼光却体会不到别人的感受，再具体了说就是自私吧，就是自私。方方面面。
哪里好了啊。纯粹的利己，纯粹的计算，天天活在对未来的计算、期望、判断里。吃完饭拿过小票来加起来看看是否属实，逛超市完全是精打细算，走在路上脑子里全是接下来的安排，渐渐丧失了感性的好多东西，完全看不到好啊。（我现在做的这件事值它所占用的时间吗？甚至明天下午杰哥请吃饭我也有不想去因为它耽误时间...从这个角度可以解释我的很多行为嗯，就从一纯自私利己的角度出发，你们不能理解的地方可能就能迎刃而解）
想来哪怕是不让可可玩水吃彩蛋也都有这样的一部分在内：我只是从客观上分析，从“本可以”上讲，完全弃父母的感受可可的感受于不顾（当然我还是觉得惯的有点过，惯的有点过。虽然我现在感觉如果是自己的话可能也会惯着他...但是从非主导的旁观者的角度...）。
所以我情商就是好低的......可能有时会敏感但大部分时候神经都是大条的...

写着写着不想写了...（不要聊了、我不知道要说什么也没什么想说的，真的是心痛）


Entered on [2017-04-26 Wed 19:45]  
Ended on [2017-04-26 Wed 20:41]
** 2017-05 May
*** 2017-05-04 Thursday
**** 

Entered on [2017-05-04 Thu 22:12]  
Ended on
**** wtf？？
我的org出问题吗？？感觉好怪。。。
能写就好回头再修吧。。。

这几天好累orz，以后回家要慎重（并没有像原先说的那样在家里好好休息...，坚决不坐车，坚决不坐夜车。
总之...这周可能把上周的疲惫遗传了下来，完全不在mode，每天困倦困倦困倦，大概只有打游戏、睡觉、洗澡的时候提得起精神...
我需要..好好休息那么几天...md好烦..这几天都没怎么做题（好像做了几个暴力和二分，跟没做一样2333），今天下午好容易没事了，又让我打了一下午坦克= =（不过打坦克很爽啦，尤其是看着数据从绿转紫转橙真的好爽）

啊，五一的回头再写啦，现在不想动。。明天下午大概能多学一会。。


Entered on [2017-05-04 Thu 22:14]  
Ended on [2017-05-04 Thu 22:29]
*** 2017-05-07 Sunday
**** 丧志

Entered on [2017-05-07 Sun 21:51]  
Ended on
**** 丧志至极！
等到我休息足够了。。精神充沛了再回来写吧。。

Entered on [2017-05-07 Sun 21:53]  
Ended on [2017-05-07 Sun 21:54]
