* 测试日记。
这里是我第一次写，测试一下。
* 2017
** 2017-02 February
*** 2017-02-20 Monday
**** 写下第二次测试日记。
Entered on [2017-02-20 Mon 18:19]
**** 又一个测试的版本
***** 计划如下
1.学习org...这个东西也很多很大很复杂。。
todo必须做 还有什么时间戳啊 tags啊 感觉非常棒。
2.学习git...手头有本pdf不过可能得回头看了
3.做题。。。其实我现在有一点纠结的。
Entered on [2017-02-20 Mon 18:19]
**** 一点随感于思修课上
刚才的一瞬竟令我有些许的动摇。
我想到我由markdown的沉迷到对org的渴望，想到我几近半年不曾写日记。
遂生出数字文本于手写文本之间的选择冲突。
其实我最先想到的是哪个更能保存更有价值（宛如一个想将世间一切独吞之国王，一个想将记忆全部封存在某种球体的妄想之鱼，想将迷宫走完，将成就毕竟，将走过的路完善臻至极限...）
就像曾经我凡一论文即复制一份备份保存甚至想将我那些通信（那些可爱的）全部复制备份全部封住留存。
就像我当初似是已经知道了什么一般不住的凝视凝视意欲将某些印象永久烙刻。

啧，思绪有些走远，不过很好。主要是我所牵挂、意志常常憋的我透不过气（致密的恍惚）
那种浑浊的，压抑的宛如西夏旅馆一般的所谓意志，却在外人看来强迫痛苦扭曲恍若石入水之涟漪却只再也听不得回声。
今日英语，得在BigBang（也许是生活大爆炸吧）中看到一个机械、笨拙、满脑子知识与秩序的同类，许是因为剧而夸张，但我却极为歆羨他那样的直接了当的表达。我的意志...却因为受了太多束缚制约而变得千疮百孔......我想说的是，压抑而不得表达。最终表现出来就是反抗、爆炸、彷徨、无望。我的世界外面多了一层东西，那使我变得“理智”也同时失去了许多。


近来感觉大秦话非常有趣，怕不是中毒本性暴露。
近来喜欢一款叫做宝石TD的塔防游戏，怕不是中毒本性暴露。因为不能过关却每每都知道失误在何处知道那里可以改进的无止境的尝试。

我给沈说起我将要放弃纸质，他却反应有些激烈：“又少了一个战友，再见”
令我颇为不适亦无法适从。
其实也不是以为纸质不好。我曾经多次暗暗许愿我会坚持“写毛笔字”这一事项（当然建立在我不被强迫种种的基础上），但是就我目前的性质来说，就我目前对电脑的依赖来说，我现在需要这样的日志。

哎，开学第一天，坚持到现在还没有玩。还不错。
课程一般，天气很坏。
被子很舒服，睡觉也不错，心态不错。我感觉良好。

Entered on [2017-02-20 Mon 20:57]
**** 今日完成
如何记日记（其实并不是什么难事。）

Entered on [2017-02-20 Mon 21:22]
*** 2017-02-21 Tuesday
**** 操蛋的一天。
首先物理实验超乎寻常的严格。不过这其实没什么，物理实验还算有趣。
我就不该回宿舍学习，效率无比低下，不想多说。
外面又冷的无以复加，我感到绝望。
一个操蛋的水题到现在都没做出来，都开始怀疑编译器是不是出了问题，是不是break无法跳出循环...
冷啊。我感到毛裤之必要。
算了早睡觉吧。有些心烦意乱。主要是题233.

Entered on [2017-02-21 Tue 20:54]
  
  [[file:~/Desktop/c%2B%2B%20and%20acm/hdu2-2-2/main.cpp::printf("1")%3B][file:~/Desktop/c++ and acm/hdu2-2-2/main.cpp::printf("1");]]
**** 诶我做出来了
但是超时了。
于是去找了下题解，发现这帮人居然直接打表！居然直接记下所有要求的值然后日过去了，fkit！这不清真！
我不做了！fkit！
fkit！
明天学打表，学org，学git，学一下谷安网课吧。
今天了解了一点lisp，知道了一本scip，想去学haskell。咩哈哈。

最近是真的冷，一想到冷到无法好好学习就好烦啊。明天去图书馆（如果不下雨！！！）

Entered on [2017-02-21 Tue 22:09]
*** 2017-02-23 Thursday
**** 这里记的是昨天的内容
昨天夜里沉迷steam，忘记了写日记。
***** 汇报工作
昨天大概是知道了约瑟夫环的两种写法（？）有待查证：
kill=(kill+m-1)%n （某题解，m为第几个，n每次--）
kill=(kill+d+n-1)% n + 1 （紫书，do{...}while（a[p]==0））
然后看了几个pta的小题...大概今天能做（如果没有被体育课累垮233）

怀疑emacs+gcc的重定向好久，结果发现好像是因为死循环，今天再试试吧。

下午开了个小会，知道了科协和校队的计划，同时，加深了我的恐惧与紧张。

***** 日记
说到恐惧与紧张，我好不容易在寒假里找回了原初，却几近被打回原型。什么队里dalao小学就学py学vb啊，什么陈志老师可能会踢人啊，什么队里非常激烈啊。我一下子就紧张了起来，感觉十分害怕，感到非常慌张。
沈晚上教育我：不然你玩cs的时候别人凭什么在学py？我并不觉得咋了，这种人难道不多？
啧，颇有一种失落与愤懑积怨呢。
不过想想似乎有些道理：自己在基础上

晚上发现了某宝与steam 不可不说的联系，于是买了20+ 个游戏来。还不错，找到了好货，还找到了童年2333（孤单枪手）。
不过也因为这个晚上由于兴奋（喜+1）而有些荒废了= = 该做的事情都没怎么做。

Entered on [2017-02-23 Thu 08:59]
**** 我有一句mmp不知当讲不当讲
从体育课完了之后我就一直在怼这道水题，结果竟然是各种“0”的问题。“浮点错误”是一个神奇的东西----除了0 同余了0 。
啧啧啧。
负数+正数有时也能得0，我是真的没想到....

Entered on [2017-02-23 Thu 19:30]
**** 去除心头二患
现在C-c c可以直接调用org-capture了
现在M-w和C-w可以复制到剪切板了，这个nice到爆炸！刚才做题到时候大概有好几次都是忘记emacs不能（当时不能）向外剪切内容，啧啧啧

Entered on [2017-02-23 Thu 20:00]
  
  [[file:~/Desktop/c%2B%2B%20and%20acm/tianti/5-2/main.cpp][file:~/Desktop/c++ and acm/tianti/5-2/main.cpp]]
*** 2017-02-25 Saturday
**** 今天的和昨天的份
其实这两天啥都没干，差不多一直在和沈玩。23号是沈的生日，权当稀里糊涂的过了吧。
汇报工作的话，就是做了几个天梯上的水题。就当成复习和熟练了。。。

其实说起来事还挺多的，把键盘送出去，把图片和英文给组长，把几项奇奇怪怪的作业写完....只是懒得不想动弹。

Entered on [2017-02-25 Sat 19:07]
  
  [[file:~/Desktop/c%2B%2B%20and%20acm/tianti/5-9/main.cpp::#include%20<iostream>][file:~/Desktop/c++ and acm/tianti/5-9/main.cpp::#include <iostream>]]
*** 2017-02-26 Sunday
**** 迷之失落
早上出去转了转，把键盘寄回去修，又去羊山公园绕了半圈，也算是破了“从未出过校门”之说。东边的道路都冷清的很，感觉比羊山公园还要好玩一些——大体是因为羊山公园离主道太近，又用广告牌围起了半边吧。破坏了原有的美感与意境..总之我大概是不会再去了(\立下flag?)。
走在那种只有时不时的车辆经过的街区竟重现了过去的某种失落之情。似乎是在这种气氛中我忽然想起一件事情--明天陈雅雯过生日。
于是忽然僵住。

Entered on [2017-02-26 Sun 17:55]
*** 2017-02-27 Monday
**** 于思修课上
我竟然真的做了和思修有关的事情。
那就是看了一点逼乎上各路大神之言论。
我曾以为1984美丽新世界已然描绘出现世政治之全貌，却刚刚发现现实之中的矛盾冲突一点不比小说差多少，其情节之复杂，人物个性之鲜明与浑浊，不同角度不同方面对话题的调离、抽换、吐槽、调侃，有人洗地有人高呼有人热血上涌不顾一切。应当说诸生百态皆在其中，实在是一出大戏。可能也只有网络才能上演这样那样的离奇故事了吧。（应当说，比之西夏旅馆毫不为过吗，哈哈）

----「如何看待微博上一名男性自干五发帖控诉自己被强制结扎？」

自干五是我第一次了解的一种神奇的生物。虽然网上只有正能量的自干五介绍，我却还是觉察到了那么一丝丝的违和感。

然后就是这样一条评论，深深触动了我的心。
「我支持某项政策≠这项政策执行到我头上我已然支持。我不觉得这两者有什么矛盾的地方，也从来没幻想过自己可以不被碾过去。车轮碾我的时候，我就叫唤，不碾我的时候，我就称赞车轮。我不是精神分裂，我只是明白，这世上没有十全十美的事。」

有一些精妙的评论：
「绝育手术证明的字好看」竟有一石二鸟之感。
「我真的有一头牛」我第一时间没有反应过来。
「只要你精分，就能逻辑自洽」
「这盛世如你所愿」关键在于反差。

颇有些入迷了，竟一时忘了一会有课。上课去也。

Entered on [2017-02-27 Mon 17:41]
**** 。。回来写两句
配置好了更新不上！什么鬼！
Entered on [2017-02-27 Mon 23:37]
*** 2017-02-28 Tuesday
**** 喵喵喵？？？
今天写了一大堆都没了？？？？？wtf？？？
而且是今天的一概没有？？


Entered on [2017-02-28 Tue 22:19]
**** what the fk？
而且今天记下来的题解也都没了？？？
什么鬼啊？？？
我脑子里一片问号


Entered on [2017-02-28 Tue 22:20]
**** 我日
用git把自己覆盖了！
checkout我以为是。。干啊。。居然是一个危险至极的指令。


Entered on [2017-02-28 Tue 22:23]
**** 无奈再写一遍
题解是没了
今天只做出了一题。

训练的时候肚痛，死去活来。抖动抖动面色发黑神色扭曲恍若某种怪物变形前兆。

大概是晚饭？也可能是早上的酸梅汁？或者是中午活活把美梦作死（梦到回到学校似乎要发生什么有趣的事情的时候我却因为细节太真而疑是幻觉[大概是一块娓娓道来有头有尾有名有姓的海报板]于是想从中出来竟真的破碎出来生生把一切搅碎）？抑或是中午起床后为了保持自己的状态到下午训练的一杯咖啡？又也许是训练时过于紧张急切的心情？

总之是来的突然，来的猛烈，而且是我第一次在外所受。

虽然晚上本该（本来我该一刻就可以上床的，该死的git把我文件搞炸了，我现在蹲在地上衣衫褴褛的打字）洗衣服写作业但是却失力毫无依托毫无支撑。
而且有点饿。
睡了。本来是打算扩大夜生活的。毕竟晚上的时间好多都没了，这学期的支配时间变得极为稀缺....结果首日就遇到这样的事情。

听闻父亲得了心脏病，有些担心（似乎又不是，回头问下）。


Entered on [2017-02-28 Tue 22:24]
** 2017-03 March
*** 2017-03-01 Wednesday
**** 今日
并无所为。

大致了解了二分的套路。居然能用ifdef。
我觉得把周二的题做了之后就可以写点作业了...感觉再拖下去会出事情。毕竟周五还有课...

晚上上网络文学课选修。老师要我们自己演讲表达。意外的听到了许多有趣的东西。有人讲生化危机滔滔不绝几致使下面人昏睡，安利电影，讲网络暴力，有人推荐三生三世电视剧从而引出两路大神（竟还有公众号写手）前来批判一番。

母亲跟我聊天：你和勖勉的现行志向竟意外精准的与儿时所写重合，梦想成真。我亦是十分惊奇。我当上了儿时所想的“电脑科学家”虽然与当时的思路有些许偏差（当时是要大屏幕大硬盘大，大大大大大，有些羞耻）而oo画画和导演两项竟全部命中不由令人毛骨悚然。

可惜沈不曾在儿时写下这般豪言壮语（又也许是不为人知），现在再想表达似乎已经变得困难阻碍重重--不再是平铺的二维甚或是一维结构而变成三维甚至更高的螺旋层叠自我衍殖的迷宫深处。
啊，迷宫深处是一颗心脏，他们说那是活着的（印象如此深刻却也只剩下轮廓）
文化的东西啊....（思绪走远，跑出去看了好久的访谈一类的东西....）

身体还是有些虚弱。先睡了。


Entered on [2017-03-01 Wed 22:08]
  
Ended on [2017-03-01 Wed 22:50]
**** 
Entered on [2017-03-01 Wed 22:55]
**** 
Entered on [2017-03-01 Wed 22:55]
  
   Ended on [2017-03-01 Wed 22:55]
**** 
Entered on [2017-03-01 Wed 22:58]
  
   Ended on [2017-03-01 Wed 22:58]
**** 小小的修了下org 看看能不能让他记录结束时间
Entered on [2017-03-01 Wed 23:00]
  
Ended on <2017-03-01 Wed 23:00>
**** 


Entered on [2017-03-01 Wed 23:05]
  
  

 Ended on <2017-03-01 Wed 23:05>
**** 


Entered on [2017-03-01 Wed 23:07]
  
  
Ended on [2017-03-01 Wed 23:07]
**** 


Entered on [2017-03-01 Wed 23:08]
  
  
Ended on [2017-03-01 Wed 23:08]
**** 


Entered on [2017-03-01 Wed 23:08]
   
Ended on [2017-03-01 Wed 23:08]
**** 


Entered on [2017-03-01 Wed 23:10]
   
Ended on <2017-03-01 Wed>  by 孙斗南
**** 


Entered on [2017-03-01 Wed 23:12]
   
Ended on [2017-03-01 Wed 23:14]
**** 尝试着调了调org
结果失败了。
这个最后结束的这个我还是得自己来更新（C-c ./C-c !）不知道怎么更新时间戳。。。


Entered on [2017-03-01 Wed 23:16]   
Ended on [2017-03-01 Wed 23:16]
**** 


Entered on [2017-03-01 Wed 23:19]   [[file:~/Desktop/c%2B%2B%20and%20acm/DI1_lesson/3/main.cpp][file:~/Desktop/c++ and acm/DI1_lesson/3/main.cpp]]
Ended on [2017-03-01 Wed 23:19] [[file:~/Desktop/c%2B%2B%20and%20acm/DI1_lesson/3/main.cpp][file:~/Desktop/c++ and acm/DI1_lesson/3/main.cpp]]
**** 对了
今天胸口的大瘤子破了，我花了一节课去挤它。现在创口很疼，而且没挤干净。还好我抖m。
另外今天妖风阵阵据说有八级之势。
我现在肌肉习惯快出来了。。到网页上查找自动C-f，结果毫无反应= =


Entered on [2017-03-01 Wed 23:20]  
Ended on [2017-03-01 Wed 23:24]
*** 2017-03-02 Thursday
**** 日记= =
今天下午打球，打到无神。
回来后跟沈打了会Portal2，各自觉得对方智商堪忧。
晚上把steam里的卡都推了出去，并且终于算是弄好了steam...然后洗衣服。

洗衣服好累啊！
虽然和我懒总是会把未洗的衣服堆积到难以忍受的地步有关....但我还是想说，好累啊！
感觉就像是上了另一节体育一样。

感觉。。怎么明天就又要训练了呢。。我当时的二分题才做了2/5，还有⑨个练习题没有做啊啊啊......好想好想花大块的时间玩啊...
大概也只能想想了

Entered on [2017-03-02 Thu 21:48]  

Ended on [2017-03-02 Thu 22:02]
*** 2017-03-03 Friday
**** 迷之被抓
被抓来当壮丁（观众了），第三届辅导员职业能力竞赛！无fk可说。
好在带了电脑不知道能不能写几个题，我的午觉我的状态条我下午还要训练啊啊啊
会场的灯泡还炸了好可怕。校外嘉宾嘤嘤嘤。无怪乎我们被抓来，又是一场唱给不存在的群众的戏。


Entered on [2017-03-03 Fri 13:43]  

Ended on [2017-03-03 Fri 13:45]
**** boom！
一导员在演讲到热烈时候仿佛助威一般天花板的灯泡boom的炸裂破碎。
看来灯泡的心情和我的心情比较相像。哈。淦。

Entered on [2017-03-03 Fri 14:54]  

Ended on [2017-03-03 Fri 14:57]
**** 于是变成闹剧
笑的不行。联系开始之前老师强烈的要求：一定要把手机静音！一定一定！！因为全程录像！！然后，灯泡炸了。于是有了辅导员在上面演讲，扫地工默默上台打扫，不停的左右摇晃实力抢镜。

Entered on [2017-03-03 Fri 15:01]  

Ended on [2017-03-03 Fri 15:01]
*** 2017-03-05 Sunday
**** 今天和昨天的
这两天一直在玩。昨天与沈do到精疲力竭，今天与沈战斗方块到虚脱无力。
说起来这两天玩的挺开心的。dota啊，战砖啊，各种自虐小游戏啊，steam+1啊，去steamcn淘宝啊。。。几乎一直在玩。。开心是开心了，就是感觉有点怠惰。
啊，周二的题没做完，周一的练习没做，周五的题和练习都没动。
好 烦 啊。
新的一周又要来啦！淦！照我这样别人在训练时就能写完的题我要做上好几天的样子不知道什么时候才能....

我忽然进入怨妇模式了...

晚上做物理实验的时候觉得好烦，想写个计算器。。。尝试了一点就弃了，真可怕。我讨厌模拟！淦！甚至还不如做acm题= =

自己给手机膜了一下，啊不，就是强行自己换膜，虽然不是那么尽善，但是还是满足了自己的强迫症。

刚才被强行在宿舍推了一波京东白条。感觉和那些在马路边上蹲守据点搭话的营销一样，强行消耗时间（当然我也遇到过不错的交流对象，不过那次毕竟是tm夜路被搭话。。。）（只是对我而言的强行消耗时间，对于他们可能就是未来和经验？

写了一篇拉低平均值的辣鸡日记。
你看看周末舍友还曾出去玩（虽是独身一人，但是他带了相机！），沈还在娱乐之余证出不少东西写了不少blog....
总的说这一周比较的迷。精神比较萎靡，打开手机qq没有人聊天就去翻群助手，从前那种打开手机就是pdf就是vjudge的日子一去不复返了（明明上课那两天又看233）。

Entered on [2017-03-05 Sun 21:38]  

Ended on [2017-03-05 Sun 22:09]
**** 还有啊
虽然分了类但是感觉没有什么卵用的样子23333.

Entered on [2017-03-05 Sun 22:20]  

Ended on [2017-03-05 Sun 22:20]
*** 2017-03-06 Monday
**** 疲惫的日记
老杨累的生无可恋需要治愈....只可惜我也累的生无可恋....
今天明天几乎都是满课，除了今天上午能够堪堪休息一个早上。

中午没睡觉，拿着新到的螺丝刀，抱着视死如归的勇气把电脑拆了看看，结果有个螺丝本来就有些花，我一拧瞬间里面就花炸了了，再也没法拧...无奈只好把电脑装了回去。
等壁纸刀再尝试尝试。

下午回宿舍的路上后颈一凉。我起初以为下雨，但是想想雨点的大小和周围并不是湿润的地面，感觉不对，摸了一把，竟有非常实在的触感。拿到眼前一看，手指已是绿油油的....
怎么说呢，被临幸不知是幸运还是不幸。

晚上用u盘的时候才想起来找之前的u盘，早已不知被我遗忘在了什么地方。总觉得我那些在我第二天就遗弃忘记的u盘的命途真是悲哀呢。

不说了，这个点了我才刚刚完成任务，虽然又困又累，可是明天还有比赛，总还是要做个题的吧。


Entered on [2017-03-06 Mon 20:58]  

Ended on [2017-03-06 Mon 21:12]
**** 啊，好舒服
热茶好舒服。
本来想喝咖啡的，想了想还是喝了茶。

Entered on [2017-03-06 Mon 21:32]  

Ended on [2017-03-06 Mon 21:32]
*** 2017-03-08 Wednesday
**** 稍稍平复了心情，回来写日记

新的学期课明显多了起来，现在我都是在上课的时候休息（玩手机）...

昨天比赛打的我爆炸。四个树还有几个题根本就没做，最后连资格也没有拿到---其实想想也是，自己的数据结构、数学都菜的一比。
我以为还没有当时沈学了一个月的时候强绝非虚言。
于是昨天就变得非常绝望非常疯狂，也不想睡觉也不想玩什么都不想做陷入浑噩状态。


这两天喜欢逛steamcn交易区，其实节约的成本与时间消耗根本不成正比，但却就是非常喜欢非常沉迷。满足的恐怕是自己的某种强迫需要吧。和春节人们不停的蹲守红包最后根本拿不到多少钱的那种感觉似乎有些相像。

弱啊，弱啊，弱啊。
而且陷入了一种好想玩->卧槽我这么菜怎么还想着玩->不行啊果然还是好想玩->....的循环中。
大概是自己过分的贪婪了吧，在两个方面都是，太想玩也太想变强。

想不起该写啥了。

Entered on [2017-03-08 Wed 15:54]  

Ended on [2017-03-08 Wed 16:06]
*** 2017-03-09 Thursday
**** 小记
最近怕不是进入了贤者模式，啥也不想干。
无心学习无心做题....
下午开了个两个小时的年纪大会，打乱了本来的计划。
不过无妨，本来计划也很少而且执行欲望很差。

听了沈一席刺探的关于泰山学堂大佬们的进度的话，那睡醒-翻谱-学习之生活，再比较于天梯赛都菜菜的划水的我，深感无力。

下午手机因为计划问题没电了，意外的过了几个小时没有手机的生活，感觉是挺不一样的。当然也和体育课完了之后整个人亢奋进入另一种人格有些关系。
比如我发现学校里的喇叭都放置在人烟稀少的路上，在主道上根本没有....不是很懂这样的原因。
然后是今天二食堂的西红柿炒蛋。我咬个西红柿入口下去不是清爽可人的酸，竟是馥郁凝滞的咸。那种感觉就好像吃到了母亲做的菜里常常出现的没有搅开的一大坨盐。

不说了，写个二分洗洗衣服看看时间玩一玩吧。
无休止的疲惫。


Entered on [2017-03-09 Thu 17:59]  

Ended on [2017-03-09 Thu 18:10]
**** 哦对了
补充一下，学校的机子有bug= =我的freopen不能用，然后我也不会复制粘贴（win下），我也对win操作非常僵硬了（C-eC-aC-nC-p都不能用！淦！）。。。。
不过最主要还是自己的问。TAT

Entered on [2017-03-09 Thu 18:16]  

Ended on [2017-03-09 Thu 18:16]
**** 好气啊
1h前我就已经写完了。然而现在还没对，根本不知道错在哪，我拿着题解一行一行对还是找不出来。。。好绝望。

忽然停水。
体育课之后不能洗澡我有一句mmp不知当讲不当讲。

素质八连。

Entered on [2017-03-09 Thu 20:26]  

Ended on [2017-03-09 Thu 20:26]
**** 淦
还没出来。。。已经红了整整一面了。
我还没写作业，淦！

Entered on [2017-03-09 Thu 21:10]  

Ended on [2017-03-09 Thu 21:10]
**** 解决了。。。
啊。
我感觉
自己虽然智障但是好歹好歹好歹终于终于tm的搞懂了。
总算没把自己强迫死。
刚才搞出来的一瞬间我都快憋死了。
我这个情绪繁衍酝酿有点厉害。
强迫症也是日渐加剧。
不过把气撒给同学了一些2333
不然可能就炸掉了。


Entered on [2017-03-09 Thu 22:43]  

Ended on [2017-03-09 Thu 22:45]
*** 2017-03-10 Friday
**** fk
一题没做出来好绝望
主要是总是觉得卧槽自己这个题没毛病啊，怎么就是WA呢怎么就是不过。
心态不说爆炸也差不太多了。
打了字又退回去，md自己真是废。无fk说。

Entered on [2017-03-10 Fri 20:30]  

Ended on [2017-03-10 Fri 20:30]
*** 2017-03-11 Saturday
**** 昨天好像忘记写了
光顾着感概昨天训练的事了，这两天倒过的有滋有味。
比如我现在只着一条内裤站在椅子外面随时等着他们把澡堂空出来然后去抢。

说正事。
昨天去看了《Logan》，第一感觉是狗屁删减版。第二感觉是，啊，莫名的沧桑。
我不是Xmen死忠也不是金刚狼死忠，我没看过（也许看过但是却没有印象）第二部金刚狼，不过我好歹看过xmen全部（哪怕当时只是冲着超级英雄冲着超能力冲着刺激冲着爽）但是英雄迟暮，不复当年，举步维艰。博士走了，logan走了，总是觉得好缺憾。但却又是开头其实就预料的到的结果。
简单的故事，还有多处的致敬，平淡却使人泪下。
「至少还有水」
「至少还有水呢」
「原来死是这种感觉啊」

无情的工作人员在演完之后就喊「没有彩蛋」，他们不懂啊，不懂观众们就算知道没有彩蛋就算知道有些事不会发生却还会默默的坐在那里等待还是希望他还在，他们还在...
说起来我听说片方为了提高排片率居然砍了结尾滚动字幕的6分钟...加上工作人员的喊话让我不得不有些寒心---就像那些让位于娱乐让位于利益的媒体一样，令人不快。


犯懒啊。日记都不想写。

拖着拖着就拖到了今天。

昨天上午玩泰坦，中午玩dota，下午去陪着同学打了打球（却是不曾料到今天会下雨），生活竟是犹如我印象中的一样美好。
只是有时空间里会有大神发一些奇妙的说说使我意识到自己的落后与羸弱（知耻后勇...）
有时也会想起，啊，天梯赛没有过诶。明明只是上周二却是有过了一个月之久的延伸感。

今天睡了懒觉，中午起来看dota比赛，也是蛮开心的。
淦。
所以我到底是该开心还是不该。

另外老杨周五告诉我她找到了求知欲，找到了热忱，感觉那就是我刚开学的那种感觉（还有假期玩emacs2333）。
啧，现在怎么没了呢。
一身的怠惰。
还有玩性。


Entered on [2017-03-11 Sat 19:06]  

Ended on [2017-03-12 Sun 16:20]
*** 2017-03-14 Tuesday
**** 又来水日记啦
因为水了节训练...
除了一道不是图论的还会做以外，就没有会的了。

昨天没记，也没有啥。晚上科协课教dp，然而做一道dp变形做不出来。就是lcs记录路径然后递归。。。最后差不多就是照着题解写的
递归反人类！淦！（然而一般题解都会说：递归的过程就是正向的非常简单）

今天图论，被各种方法支配...spta kruskal bellmanford dijkstra...
无fk说。
“这个题只要最小生成树跑一遍就可以了”
“这个题就是个负环，有很多做法啊随便选一种就好了”
然而最可怕的还是我听都不能听清的诡异名词......
啊。
啊啊啊。

回去再写= =


Entered on [2017-03-14 Tue 21:02]  

Ended on [2017-03-14 Tue 21:02]
*** 2017-03-15 Wednesday
**** 班会
头一次知道还有班主任，以前以为只有一个辅导员，没想到还有一个班主任...
而且居然是个非常强的班主任。
教c,java,py....
意见是好的，忠告是非常及时的，再一次给我敲响了警钟，也启发了我一些东西。
真的，太好的。

迷之小さなてのひら。
忽然觉得自己还好小好年轻。

淦，我这就去学ToDo然后列计划去。


Entered on [2017-03-15 Wed 14:41]  

Ended on [2017-03-15 Wed 14:46]
**** 补充
瞎感慨了一番。
说起来就是。
1.stitp项目要早搞，在大二上，一开始就要着手
2.论文和专利能弄就弄。专利不好搞，论文。大二下？
3.不要沉迷游戏
4.中国大学mooc....休息时不要去打游戏，去看点喜欢的东西。
5.一定要变强，一定要变强。

Entered on [2017-03-15 Wed 14:48]  

Ended on [2017-03-15 Wed 14:48]
**** 回去了！
肚子有点疼。先回去了。
晚上课不去了。辣鸡选修（好像要看左耳，我的内心？？？不如打游戏呢。。浪费时间也到不了这个份上）。

我把下面那个时间戳改回去了，看的不习惯的就右上角raw\blame切模式看好了，再不济仓库首页左上角commit看更新。（别真的改啊2333）

我到各种地方搜索都是C-f，也是醉。
再看一会C-cC-c的重复配置能不能解决就走。。


Entered on [2017-03-15 Wed 16:12]  
Ended on [2017-03-15 Wed 16:23]
**** 不做人啦！
摔！还没弄好！不弄了！

Entered on [2017-03-15 Wed 16:56]  
Ended on [2017-03-15 Wed 17:00]
**** 。。。
还以为终于可以a题了，结果超时了。。。
无fk说。
计划里是做三个题的。。结果只做了两个（这个还没a），虽然知道了yasnippet这神奇的东西不过还是觉得，不是很赚。（比起左耳当然是稳赚）

跟棣文聊了聊，发现他依然保持着他的活力而我垂垂老矣，在诸多方面....

买了个一百元的手柄，这个月预算没有了（本来就被我因为发现了steamcn而花去了许多买游戏。。。）。沉迷于买游戏。。。没有前几天那么热衷了

Everything goes wrong to turn into the way of life
随到了The Letter - 啊，人品真棒。

上床玩会手机睡了。


Entered on [2017-03-15 Wed 22:59]  

Ended on [2017-03-15 Wed 23:06]
*** 2017-03-16 Thursday
**** 今日
沈：人类啊，都是一样的，需要消费，需要释放。

早上起来之后进入虚无的无事可做模式。
发现南二食堂不知道比南三高到哪里去了，不论是早餐还是中餐。
早上喝豆浆真是满满的享受。

淦昨天晚上和沈打了会游戏忘记写了。
沈进入了和我类似但不同但是他非常狂躁而我不然的空虚状态（不过今天好像恢复如初变回dalao）。
手了把卡尔随了把卡尔，打的很开心。

不过估计今天的题我就都不会了。毕竟邹...出题。
无妨啊2333，毕竟以前也是，划水...签到...然后拓展一下视野知道有啥要学的。
只是欠下的越来越多。

今天手柄到了，好激动好激动。
玩了一会手感不错，就是我没有一些act大作比较僵硬。
好开心啊。

啊。原以为这周状态会好一些的（其实就是好一些啊，好说歹说做了三道题。。虽然周四僵了，之前还是蛮不错的）

让我数一下。。
- dp 欠下几个亿
- 图论 还没开始学
- 数学几个小题题
- 唔 二分好像只差几个练习题了！终于在三周之后做完了第一次课的5个题orz。
好消息是下两周是好像会很闲的实验周。

啊不管了。
熬过晚上再说。
啊手柄到了好开心。
啊精分好爽。

Entered on [2017-03-16 Thu 21:39]  

Ended on [2017-03-17 Fri 17:13]
*** 2017-03-18 Saturday
**** 好困啊
早上本来约好去和学姐打球的，偏偏昨夜有雨，只好作罢。
只是可惜我起的好早好早。

没想到老杨也会有绝望迷茫的时候呢。

昨天上课也好绝望啊。虽然很短，但是很绝望。
图论什么的还是有点远啊= =我现在连个二分都要做好久，在知道思路的情况下...


Entered on [2017-03-18 Sat 11:09]  

Ended on [2017-03-18 Sat 11:27]
*** 2017-03-19 Sunday
**** = =
这两天差不多一直在玩吧。。
虽然今天有做一点题。。不过没做出来和没做一样= =。。。

Entered on [2017-03-19 Sun 21:45]  

Ended on [2017-03-19 Sun 21:45]
*** 2017-03-20 Monday
**** = =
我放弃了。。
写两个有序数列的新数列死活写不对，两天了还没弄好，照着题解一行一行的看也不得要领，也不想重新写，就是想知道自己哪里不对，就是想知道为什么，然后不停的错愈发烦躁。。。
蛋疼啊。

污点啊污点，和上次那个数列一样估计要以后再写了。

Entered on [2017-03-20 Mon 10:31]  
Ended on [2017-03-20 Mon 10:34]
*** 2017-03-21 Tuesday
**** 好像昨天没有写
今天讲概率和期望。第一个题我都做不出来。
数学不好。
十分绝望。

近来总是会想起：啊，这个应该记一下啊。
然后转头就忘掉了。

蚊子并不像前两天一样无时无刻光顾我了（手心都两个包仍在）

学校里开了许多奇怪的小花。

啊听课去了

Entered on [2017-03-21 Tue 20:27]  
Ended on [2017-03-21 Tue 20:38]
**** 卧槽我的emacs没了
炸了炸了炸了
什么鬼啊。。
= =迷啊。

Entered on [2017-03-21 Tue 21:14]  
Ended on
**** 啊哈哈哈哈哈
让我就用了一小会就又配置回来啦
不过yas还是没弄好，回头再说吧。
org还是得用才行。。
我想恢复hexo啊= =淦不过最近没空
明天起来把辣鸡matlab7.0配置到windows上。。然后看看能不能把yas配置好。

啊 好累，今天的概率又划水连听都没听懂，睡了

Entered on [2017-03-21 Tue 22:50]  
Ended on [2017-03-21 Tue 22:53]
*** 2017-03-22 Wednesday
**** 啊
被安利了一把好贵的伞哦
每天过的省吃俭用精打细算的似乎就是为了大手大脚的一刻。
不过还是好想攒钱，好想省下每一点钱啊。

其实对时间也是一样的啊。
设置各种emacs为的就是效率和手感啦。
不过说起来我浪费的时间真是一点不少（浪费是重点），比如各种强迫症必须做出一道题来然后一晚上啥都没干......

唔。今天下午开始下雨，下午开始上课....逃了那个讲网络文学的破课233。

这周是数学实验，就是讲matlab的使用。结果老师被迫把matlab课上成线性代数课2333。啊不过还是蛮好的，不用写作业不用这个不用那个啦。


Entered on [2017-03-22 Wed 17:54]  
Ended on [2017-03-22 Wed 18:01]
*** 2017-03-23 Thursday
**** 咩哈哈
今晚还行。
实验周的课结束了，好好的玩了玩。
明天也没什么事，睡个懒觉做两道题，然后使劲玩玩好啦（天梯赛前休整停课了。。反正除了前三节课还算能听懂从图论开始就懵逼了好吧。下节课字符串肯定也是。。）

上个周末玩都玩出了贤者模式2333。

哦对了，matlab还是蛮有趣的...不过玩的多了还是有点僵硬，是一种不自由感...翻来覆去净是那些东西（而且小数精度问题丝毫没有改观）。嗯比起c来毕竟少了些东西，也多了些东西，毕竟数学方面更强了。
而且我总是会想到切片什么的。。。
就想到抽空要学haskell啊。py也是半途而废啊。

...想啥都能想起自己欠下的账。

Entered on [2017-03-23 Thu 23:55]  
Ended on [2017-03-24 Fri 00:01]
*** 2017-03-25 Saturday
**** 日记
今天下午我和妹子联机打游戏了！23333虽然是并不熟的打崩坏认识的妹子
不过还是很开心的。

终于把数学实验（算是）写完了。

有个舍友爱好天文，今晚地球一小时活动观星到11点才回来，觉得有一爱好确实很好，能够平衡疲惫的学习的自我。我现在比较欠缺这个东西。若非要说打游戏是我的爱好总是觉得，像是明明知道自己是却还是止不住自己吃和玩的欲望的肥宅

然后有个舍友去魔都玩了。
我觉得他们都很强啊。

Entered on [2017-03-25 Sat 23:32]  
Ended on [2017-03-25 Sat 23:58]
*** 2017-03-27 Monday
**** 啊 好累
今天做电装实习。
早上因为这两天睡的太晚而没有起来。若非舍友不停的电话call我，恐怕我今天的实验就玩完了。
然后一天都在焊电阻啊什么的，中午一度被“红黄蓝绿”“红红黑棕”支配（分电阻分到怀疑自己是色弱）
说起来，组装电表什么的对于动手能力为负的苦手来说竟然并不显得多么难。虽然还是要经常向左右之旁的同学们请教，但是似乎，只是似乎，某些执着的念头没有以前强烈了。（虽然还是有时会想电烙铁什么的但那是思绪飘忽，并不会想：啊，我要是没对上怎么办，啊，我要是不小心烧坏了这个怎么办，啊...if...）
也可能是因为循规蹈矩步步为营，并无太多动手操作之要求吧。

一天都坐在没有靠背的椅子上比周末在电脑前玩一天还要累的多。
啊。

想玩游戏。想做题。想睡觉。
洗完了澡，上床了

Entered on [2017-03-27 Mon 21:25]  
Ended on [2017-03-27 Mon 22:05]
**** 哦对了
昨天就是玩啦
昨天还水了几道题

今天中午我只穿了两件单衣却感到非常热。我觉得令人绝望的夏天就要来了。
不过春天还是挺舒服的。

好了苦手这回真的要上床了。

Entered on [2017-03-27 Mon 22:07]
Ended on [2017-03-27 Mon 22:15]
