* 测试日记。
这里是我第一次写，测试一下。
* 2017
** 2017-02 February
*** 2017-02-20 Monday
**** 写下第二次测试日记。
Entered on [2017-02-20 Mon 18:19]
**** 又一个测试的版本
***** 计划如下
1.学习org...这个东西也很多很大很复杂。。
todo必须做 还有什么时间戳啊 tags啊 感觉非常棒。
2.学习git...手头有本pdf不过可能得回头看了
3.做题。。。其实我现在有一点纠结的。
Entered on [2017-02-20 Mon 18:19]
**** 一点随感于思修课上
刚才的一瞬竟令我有些许的动摇。
我想到我由markdown的沉迷到对org的渴望，想到我几近半年不曾写日记。
遂生出数字文本于手写文本之间的选择冲突。
其实我最先想到的是哪个更能保存更有价值（宛如一个想将世间一切独吞之国王，一个想将记忆全部封存在某种球体的妄想之鱼，想将迷宫走完，将成就毕竟，将走过的路完善臻至极限...）
就像曾经我凡一论文即复制一份备份保存甚至想将我那些通信（那些可爱的）全部复制备份全部封住留存。
就像我当初似是已经知道了什么一般不住的凝视凝视意欲将某些印象永久烙刻。

啧，思绪有些走远，不过很好。主要是我所牵挂、意志常常憋的我透不过气（致密的恍惚）
那种浑浊的，压抑的宛如西夏旅馆一般的所谓意志，却在外人看来强迫痛苦扭曲恍若石入水之涟漪却只再也听不得回声。
今日英语，得在BigBang（也许是生活大爆炸吧）中看到一个机械、笨拙、满脑子知识与秩序的同类，许是因为剧而夸张，但我却极为歆羨他那样的直接了当的表达。我的意志...却因为受了太多束缚制约而变得千疮百孔......我想说的是，压抑而不得表达。最终表现出来就是反抗、爆炸、彷徨、无望。我的世界外面多了一层东西，那使我变得“理智”也同时失去了许多。


近来感觉大秦话非常有趣，怕不是中毒本性暴露。
近来喜欢一款叫做宝石TD的塔防游戏，怕不是中毒本性暴露。因为不能过关却每每都知道失误在何处知道那里可以改进的无止境的尝试。

我给沈说起我将要放弃纸质，他却反应有些激烈：“又少了一个战友，再见”
令我颇为不适亦无法适从。
其实也不是以为纸质不好。我曾经多次暗暗许愿我会坚持“写毛笔字”这一事项（当然建立在我不被强迫种种的基础上），但是就我目前的性质来说，就我目前对电脑的依赖来说，我现在需要这样的日志。

哎，开学第一天，坚持到现在还没有玩。还不错。
课程一般，天气很坏。
被子很舒服，睡觉也不错，心态不错。我感觉良好。

Entered on [2017-02-20 Mon 20:57]
**** 今日完成
如何记日记（其实并不是什么难事。）

Entered on [2017-02-20 Mon 21:22]
*** 2017-02-21 Tuesday
**** 操蛋的一天。
首先物理实验超乎寻常的严格。不过这其实没什么，物理实验还算有趣。
我就不该回宿舍学习，效率无比低下，不想多说。
外面又冷的无以复加，我感到绝望。
一个操蛋的水题到现在都没做出来，都开始怀疑编译器是不是出了问题，是不是break无法跳出循环...
冷啊。我感到毛裤之必要。
算了早睡觉吧。有些心烦意乱。主要是题233.

Entered on [2017-02-21 Tue 20:54]
  
  [[file:~/Desktop/c%2B%2B%20and%20acm/hdu2-2-2/main.cpp::printf("1")%3B][file:~/Desktop/c++ and acm/hdu2-2-2/main.cpp::printf("1");]]
**** 诶我做出来了
但是超时了。
于是去找了下题解，发现这帮人居然直接打表！居然直接记下所有要求的值然后日过去了，fkit！这不清真！
我不做了！fkit！
fkit！
明天学打表，学org，学git，学一下谷安网课吧。
今天了解了一点lisp，知道了一本scip，想去学haskell。咩哈哈。

最近是真的冷，一想到冷到无法好好学习就好烦啊。明天去图书馆（如果不下雨！！！）

Entered on [2017-02-21 Tue 22:09]
*** 2017-02-23 Thursday
**** 这里记的是昨天的内容
昨天夜里沉迷steam，忘记了写日记。
***** 汇报工作
昨天大概是知道了约瑟夫环的两种写法（？）有待查证：
kill=(kill+m-1)%n （某题解，m为第几个，n每次--）
kill=(kill+d+n-1)% n + 1 （紫书，do{...}while（a[p]==0））
然后看了几个pta的小题...大概今天能做（如果没有被体育课累垮233）

怀疑emacs+gcc的重定向好久，结果发现好像是因为死循环，今天再试试吧。

下午开了个小会，知道了科协和校队的计划，同时，加深了我的恐惧与紧张。

***** 日记
说到恐惧与紧张，我好不容易在寒假里找回了原初，却几近被打回原型。什么队里dalao小学就学py学vb啊，什么陈志老师可能会踢人啊，什么队里非常激烈啊。我一下子就紧张了起来，感觉十分害怕，感到非常慌张。
沈晚上教育我：不然你玩cs的时候别人凭什么在学py？我并不觉得咋了，这种人难道不多？
啧，颇有一种失落与愤懑积怨呢。
不过想想似乎有些道理：自己在基础上

晚上发现了某宝与steam 不可不说的联系，于是买了20+ 个游戏来。还不错，找到了好货，还找到了童年2333（孤单枪手）。
不过也因为这个晚上由于兴奋（喜+1）而有些荒废了= = 该做的事情都没怎么做。

Entered on [2017-02-23 Thu 08:59]
**** 我有一句mmp不知当讲不当讲
从体育课完了之后我就一直在怼这道水题，结果竟然是各种“0”的问题。“浮点错误”是一个神奇的东西----除了0 同余了0 。
啧啧啧。
负数+正数有时也能得0，我是真的没想到....

Entered on [2017-02-23 Thu 19:30]
**** 去除心头二患
现在C-c c可以直接调用org-capture了
现在M-w和C-w可以复制到剪切板了，这个nice到爆炸！刚才做题到时候大概有好几次都是忘记emacs不能（当时不能）向外剪切内容，啧啧啧

Entered on [2017-02-23 Thu 20:00]
  
  [[file:~/Desktop/c%2B%2B%20and%20acm/tianti/5-2/main.cpp][file:~/Desktop/c++ and acm/tianti/5-2/main.cpp]]
*** 2017-02-25 Saturday
**** 今天的和昨天的份
其实这两天啥都没干，差不多一直在和沈玩。23号是沈的生日，权当稀里糊涂的过了吧。
汇报工作的话，就是做了几个天梯上的水题。就当成复习和熟练了。。。

其实说起来事还挺多的，把键盘送出去，把图片和英文给组长，把几项奇奇怪怪的作业写完....只是懒得不想动弹。

Entered on [2017-02-25 Sat 19:07]
  
  [[file:~/Desktop/c%2B%2B%20and%20acm/tianti/5-9/main.cpp::#include%20<iostream>][file:~/Desktop/c++ and acm/tianti/5-9/main.cpp::#include <iostream>]]
*** 2017-02-26 Sunday
**** 迷之失落
早上出去转了转，把键盘寄回去修，又去羊山公园绕了半圈，也算是破了“从未出过校门”之说。东边的道路都冷清的很，感觉比羊山公园还要好玩一些——大体是因为羊山公园离主道太近，又用广告牌围起了半边吧。破坏了原有的美感与意境..总之我大概是不会再去了(\立下flag?)。
走在那种只有时不时的车辆经过的街区竟重现了过去的某种失落之情。似乎是在这种气氛中我忽然想起一件事情--明天陈雅雯过生日。
于是忽然僵住。

Entered on [2017-02-26 Sun 17:55]
*** 2017-02-27 Monday
**** 于思修课上
我竟然真的做了和思修有关的事情。
那就是看了一点逼乎上各路大神之言论。
我曾以为1984美丽新世界已然描绘出现世政治之全貌，却刚刚发现现实之中的矛盾冲突一点不比小说差多少，其情节之复杂，人物个性之鲜明与浑浊，不同角度不同方面对话题的调离、抽换、吐槽、调侃，有人洗地有人高呼有人热血上涌不顾一切。应当说诸生百态皆在其中，实在是一出大戏。可能也只有网络才能上演这样那样的离奇故事了吧。（应当说，比之西夏旅馆毫不为过吗，哈哈）

----「如何看待微博上一名男性自干五发帖控诉自己被强制结扎？」

自干五是我第一次了解的一种神奇的生物。虽然网上只有正能量的自干五介绍，我却还是觉察到了那么一丝丝的违和感。

然后就是这样一条评论，深深触动了我的心。
「我支持某项政策≠这项政策执行到我头上我已然支持。我不觉得这两者有什么矛盾的地方，也从来没幻想过自己可以不被碾过去。车轮碾我的时候，我就叫唤，不碾我的时候，我就称赞车轮。我不是精神分裂，我只是明白，这世上没有十全十美的事。」

有一些精妙的评论：
「绝育手术证明的字好看」竟有一石二鸟之感。
「我真的有一头牛」我第一时间没有反应过来。
「只要你精分，就能逻辑自洽」
「这盛世如你所愿」关键在于反差。

颇有些入迷了，竟一时忘了一会有课。上课去也。

Entered on [2017-02-27 Mon 17:41]
**** 。。回来写两句
配置好了更新不上！什么鬼！
Entered on [2017-02-27 Mon 23:37]
*** 2017-02-28 Tuesday
**** 喵喵喵？？？
今天写了一大堆都没了？？？？？wtf？？？
而且是今天的一概没有？？


Entered on [2017-02-28 Tue 22:19]
**** what the fk？
而且今天记下来的题解也都没了？？？
什么鬼啊？？？
我脑子里一片问号


Entered on [2017-02-28 Tue 22:20]
**** 我日
用git把自己覆盖了！
checkout我以为是。。干啊。。居然是一个危险至极的指令。


Entered on [2017-02-28 Tue 22:23]
**** 无奈再写一遍
题解是没了
今天只做出了一题。

训练的时候肚痛，死去活来。抖动抖动面色发黑神色扭曲恍若某种怪物变形前兆。

大概是晚饭？也可能是早上的酸梅汁？或者是中午活活把美梦作死（梦到回到学校似乎要发生什么有趣的事情的时候我却因为细节太真而疑是幻觉[大概是一块娓娓道来有头有尾有名有姓的海报板]于是想从中出来竟真的破碎出来生生把一切搅碎）？抑或是中午起床后为了保持自己的状态到下午训练的一杯咖啡？又也许是训练时过于紧张急切的心情？

总之是来的突然，来的猛烈，而且是我第一次在外所受。

虽然晚上本该（本来我该一刻就可以上床的，该死的git把我文件搞炸了，我现在蹲在地上衣衫褴褛的打字）洗衣服写作业但是却失力毫无依托毫无支撑。
而且有点饿。
睡了。本来是打算扩大夜生活的。毕竟晚上的时间好多都没了，这学期的支配时间变得极为稀缺....结果首日就遇到这样的事情。

听闻父亲得了心脏病，有些担心（似乎又不是，回头问下）。


Entered on [2017-02-28 Tue 22:24]
** 2017-03 March
*** 2017-03-01 Wednesday
**** 今日
并无所为。

大致了解了二分的套路。居然能用ifdef。
我觉得把周二的题做了之后就可以写点作业了...感觉再拖下去会出事情。毕竟周五还有课...

晚上上网络文学课选修。老师要我们自己演讲表达。意外的听到了许多有趣的东西。有人讲生化危机滔滔不绝几致使下面人昏睡，安利电影，讲网络暴力，有人推荐三生三世电视剧从而引出两路大神（竟还有公众号写手）前来批判一番。

母亲跟我聊天：你和勖勉的现行志向竟意外精准的与儿时所写重合，梦想成真。我亦是十分惊奇。我当上了儿时所想的“电脑科学家”虽然与当时的思路有些许偏差（当时是要大屏幕大硬盘大，大大大大大，有些羞耻）而oo画画和导演两项竟全部命中不由令人毛骨悚然。

可惜沈不曾在儿时写下这般豪言壮语（又也许是不为人知），现在再想表达似乎已经变得困难阻碍重重--不再是平铺的二维甚或是一维结构而变成三维甚至更高的螺旋层叠自我衍殖的迷宫深处。
啊，迷宫深处是一颗心脏，他们说那是活着的（印象如此深刻却也只剩下轮廓）
文化的东西啊....（思绪走远，跑出去看了好久的访谈一类的东西....）

身体还是有些虚弱。先睡了。


Entered on [2017-03-01 Wed 22:08]
  
Ended on [2017-03-01 Wed 22:50]
**** 
Entered on [2017-03-01 Wed 22:55]
**** 
Entered on [2017-03-01 Wed 22:55]
  
   Ended on [2017-03-01 Wed 22:55]
**** 
Entered on [2017-03-01 Wed 22:58]
  
   Ended on [2017-03-01 Wed 22:58]
**** 小小的修了下org 看看能不能让他记录结束时间
Entered on [2017-03-01 Wed 23:00]
  
Ended on <2017-03-01 Wed 23:00>
**** 


Entered on [2017-03-01 Wed 23:05]
  
  

 Ended on <2017-03-01 Wed 23:05>
**** 


Entered on [2017-03-01 Wed 23:07]
  
  
Ended on [2017-03-01 Wed 23:07]
**** 


Entered on [2017-03-01 Wed 23:08]
  
  
Ended on [2017-03-01 Wed 23:08]
**** 


Entered on [2017-03-01 Wed 23:08]
   
Ended on [2017-03-01 Wed 23:08]
**** 


Entered on [2017-03-01 Wed 23:10]
   
Ended on <2017-03-01 Wed>  by 孙斗南
**** 


Entered on [2017-03-01 Wed 23:12]
   
Ended on [2017-03-01 Wed 23:14]
**** 尝试着调了调org
结果失败了。
这个最后结束的这个我还是得自己来更新（C-c ./C-c !）不知道怎么更新时间戳。。。


Entered on [2017-03-01 Wed 23:16]   
Ended on [2017-03-01 Wed 23:16]
**** 


Entered on [2017-03-01 Wed 23:19]   [[file:~/Desktop/c%2B%2B%20and%20acm/DI1_lesson/3/main.cpp][file:~/Desktop/c++ and acm/DI1_lesson/3/main.cpp]]
Ended on [2017-03-01 Wed 23:19] [[file:~/Desktop/c%2B%2B%20and%20acm/DI1_lesson/3/main.cpp][file:~/Desktop/c++ and acm/DI1_lesson/3/main.cpp]]
**** 对了
今天胸口的大瘤子破了，我花了一节课去挤它。现在创口很疼，而且没挤干净。还好我抖m。
另外今天妖风阵阵据说有八级之势。
我现在肌肉习惯快出来了。。到网页上查找自动C-f，结果毫无反应= =


Entered on [2017-03-01 Wed 23:20]  
Ended on [2017-03-01 Wed 23:24]
*** 2017-03-02 Thursday
**** 日记= =
今天下午打球，打到无神。
回来后跟沈打了会Portal2，各自觉得对方智商堪忧。
晚上把steam里的卡都推了出去，并且终于算是弄好了steam...然后洗衣服。

洗衣服好累啊！
虽然和我懒总是会把未洗的衣服堆积到难以忍受的地步有关....但我还是想说，好累啊！
感觉就像是上了另一节体育一样。

感觉。。怎么明天就又要训练了呢。。我当时的二分题才做了2/5，还有⑨个练习题没有做啊啊啊......好想好想花大块的时间玩啊...
大概也只能想想了

Entered on [2017-03-02 Thu 21:48]  

Ended on [2017-03-02 Thu 22:02]
*** 2017-03-03 Friday
**** 迷之被抓
被抓来当壮丁（观众了），第三届辅导员职业能力竞赛！无fk可说。
好在带了电脑不知道能不能写几个题，我的午觉我的状态条我下午还要训练啊啊啊
会场的灯泡还炸了好可怕。校外嘉宾嘤嘤嘤。无怪乎我们被抓来，又是一场唱给不存在的群众的戏。


Entered on [2017-03-03 Fri 13:43]  

Ended on [2017-03-03 Fri 13:45]
**** boom！
一导员在演讲到热烈时候仿佛助威一般天花板的灯泡boom的炸裂破碎。
看来灯泡的心情和我的心情比较相像。哈。淦。

Entered on [2017-03-03 Fri 14:54]  

Ended on [2017-03-03 Fri 14:57]
**** 于是变成闹剧
笑的不行。联系开始之前老师强烈的要求：一定要把手机静音！一定一定！！因为全程录像！！然后，灯泡炸了。于是有了辅导员在上面演讲，扫地工默默上台打扫，不停的左右摇晃实力抢镜。

Entered on [2017-03-03 Fri 15:01]  

Ended on [2017-03-03 Fri 15:01]
*** 2017-03-05 Sunday
**** 今天和昨天的
这两天一直在玩。昨天与沈do到精疲力竭，今天与沈战斗方块到虚脱无力。
说起来这两天玩的挺开心的。dota啊，战砖啊，各种自虐小游戏啊，steam+1啊，去steamcn淘宝啊。。。几乎一直在玩。。开心是开心了，就是感觉有点怠惰。
啊，周二的题没做完，周一的练习没做，周五的题和练习都没动。
好 烦 啊。
新的一周又要来啦！淦！照我这样别人在训练时就能写完的题我要做上好几天的样子不知道什么时候才能....

我忽然进入怨妇模式了...

晚上做物理实验的时候觉得好烦，想写个计算器。。。尝试了一点就弃了，真可怕。我讨厌模拟！淦！甚至还不如做acm题= =

自己给手机膜了一下，啊不，就是强行自己换膜，虽然不是那么尽善，但是还是满足了自己的强迫症。

刚才被强行在宿舍推了一波京东白条。感觉和那些在马路边上蹲守据点搭话的营销一样，强行消耗时间（当然我也遇到过不错的交流对象，不过那次毕竟是tm夜路被搭话。。。）（只是对我而言的强行消耗时间，对于他们可能就是未来和经验？

写了一篇拉低平均值的辣鸡日记。
你看看周末舍友还曾出去玩（虽是独身一人，但是他带了相机！），沈还在娱乐之余证出不少东西写了不少blog....
总的说这一周比较的迷。精神比较萎靡，打开手机qq没有人聊天就去翻群助手，从前那种打开手机就是pdf就是vjudge的日子一去不复返了（明明上课那两天又看233）。

Entered on [2017-03-05 Sun 21:38]  

Ended on [2017-03-05 Sun 22:09]
**** 还有啊
虽然分了类但是感觉没有什么卵用的样子23333.

Entered on [2017-03-05 Sun 22:20]  

Ended on [2017-03-05 Sun 22:20]
*** 2017-03-06 Monday
**** 疲惫的日记
老杨累的生无可恋需要治愈....只可惜我也累的生无可恋....
今天明天几乎都是满课，除了今天上午能够堪堪休息一个早上。

中午没睡觉，拿着新到的螺丝刀，抱着视死如归的勇气把电脑拆了看看，结果有个螺丝本来就有些花，我一拧瞬间里面就花炸了了，再也没法拧...无奈只好把电脑装了回去。
等壁纸刀再尝试尝试。

下午回宿舍的路上后颈一凉。我起初以为下雨，但是想想雨点的大小和周围并不是湿润的地面，感觉不对，摸了一把，竟有非常实在的触感。拿到眼前一看，手指已是绿油油的....
怎么说呢，被临幸不知是幸运还是不幸。

晚上用u盘的时候才想起来找之前的u盘，早已不知被我遗忘在了什么地方。总觉得我那些在我第二天就遗弃忘记的u盘的命途真是悲哀呢。

不说了，这个点了我才刚刚完成任务，虽然又困又累，可是明天还有比赛，总还是要做个题的吧。


Entered on [2017-03-06 Mon 20:58]  

Ended on [2017-03-06 Mon 21:12]
**** 啊，好舒服
热茶好舒服。
本来想喝咖啡的，想了想还是喝了茶。

Entered on [2017-03-06 Mon 21:32]  

Ended on [2017-03-06 Mon 21:32]
*** 2017-03-08 Wednesday
**** 稍稍平复了心情，回来写日记

新的学期课明显多了起来，现在我都是在上课的时候休息（玩手机）...

昨天比赛打的我爆炸。四个树还有几个题根本就没做，最后连资格也没有拿到---其实想想也是，自己的数据结构、数学都菜的一比。
我以为还没有当时沈学了一个月的时候强绝非虚言。
于是昨天就变得非常绝望非常疯狂，也不想睡觉也不想玩什么都不想做陷入浑噩状态。


这两天喜欢逛steamcn交易区，其实节约的成本与时间消耗根本不成正比，但却就是非常喜欢非常沉迷。满足的恐怕是自己的某种强迫需要吧。和春节人们不停的蹲守红包最后根本拿不到多少钱的那种感觉似乎有些相像。

弱啊，弱啊，弱啊。
而且陷入了一种好想玩->卧槽我这么菜怎么还想着玩->不行啊果然还是好想玩->....的循环中。
大概是自己过分的贪婪了吧，在两个方面都是，太想玩也太想变强。

想不起该写啥了。

Entered on [2017-03-08 Wed 15:54]  

Ended on [2017-03-08 Wed 16:06]
*** 2017-03-09 Thursday
**** 小记
最近怕不是进入了贤者模式，啥也不想干。
无心学习无心做题....
下午开了个两个小时的年纪大会，打乱了本来的计划。
不过无妨，本来计划也很少而且执行欲望很差。

听了沈一席刺探的关于泰山学堂大佬们的进度的话，那睡醒-翻谱-学习之生活，再比较于天梯赛都菜菜的划水的我，深感无力。

下午手机因为计划问题没电了，意外的过了几个小时没有手机的生活，感觉是挺不一样的。当然也和体育课完了之后整个人亢奋进入另一种人格有些关系。
比如我发现学校里的喇叭都放置在人烟稀少的路上，在主道上根本没有....不是很懂这样的原因。
然后是今天二食堂的西红柿炒蛋。我咬个西红柿入口下去不是清爽可人的酸，竟是馥郁凝滞的咸。那种感觉就好像吃到了母亲做的菜里常常出现的没有搅开的一大坨盐。

不说了，写个二分洗洗衣服看看时间玩一玩吧。
无休止的疲惫。


Entered on [2017-03-09 Thu 17:59]  

Ended on [2017-03-09 Thu 18:10]
**** 哦对了
补充一下，学校的机子有bug= =我的freopen不能用，然后我也不会复制粘贴（win下），我也对win操作非常僵硬了（C-eC-aC-nC-p都不能用！淦！）。。。。
不过最主要还是自己的问。TAT

Entered on [2017-03-09 Thu 18:16]  

Ended on [2017-03-09 Thu 18:16]
**** 好气啊
1h前我就已经写完了。然而现在还没对，根本不知道错在哪，我拿着题解一行一行对还是找不出来。。。好绝望。

忽然停水。
体育课之后不能洗澡我有一句mmp不知当讲不当讲。

素质八连。

Entered on [2017-03-09 Thu 20:26]  

Ended on [2017-03-09 Thu 20:26]
**** 淦
还没出来。。。已经红了整整一面了。
我还没写作业，淦！

Entered on [2017-03-09 Thu 21:10]  

Ended on [2017-03-09 Thu 21:10]
**** 解决了。。。
啊。
我感觉
自己虽然智障但是好歹好歹好歹终于终于tm的搞懂了。
总算没把自己强迫死。
刚才搞出来的一瞬间我都快憋死了。
我这个情绪繁衍酝酿有点厉害。
强迫症也是日渐加剧。
不过把气撒给同学了一些2333
不然可能就炸掉了。


Entered on [2017-03-09 Thu 22:43]  

Ended on [2017-03-09 Thu 22:45]
*** 2017-03-10 Friday
**** fk
一题没做出来好绝望
主要是总是觉得卧槽自己这个题没毛病啊，怎么就是WA呢怎么就是不过。
心态不说爆炸也差不太多了。
打了字又退回去，md自己真是废。无fk说。

Entered on [2017-03-10 Fri 20:30]  

Ended on [2017-03-10 Fri 20:30]
*** 2017-03-11 Saturday
**** 昨天好像忘记写了
光顾着感概昨天训练的事了，这两天倒过的有滋有味。
比如我现在只着一条内裤站在椅子外面随时等着他们把澡堂空出来然后去抢。

说正事。
昨天去看了《Logan》，第一感觉是狗屁删减版。第二感觉是，啊，莫名的沧桑。
我不是Xmen死忠也不是金刚狼死忠，我没看过（也许看过但是却没有印象）第二部金刚狼，不过我好歹看过xmen全部（哪怕当时只是冲着超级英雄冲着超能力冲着刺激冲着爽）但是英雄迟暮，不复当年，举步维艰。博士走了，logan走了，总是觉得好缺憾。但却又是开头其实就预料的到的结果。
简单的故事，还有多处的致敬，平淡却使人泪下。
「至少还有水」
「至少还有水呢」
「原来死是这种感觉啊」

无情的工作人员在演完之后就喊「没有彩蛋」，他们不懂啊，不懂观众们就算知道没有彩蛋就算知道有些事不会发生却还会默默的坐在那里等待还是希望他还在，他们还在...
说起来我听说片方为了提高排片率居然砍了结尾滚动字幕的6分钟...加上工作人员的喊话让我不得不有些寒心---就像那些让位于娱乐让位于利益的媒体一样，令人不快。


犯懒啊。日记都不想写。

拖着拖着就拖到了今天。

昨天上午玩泰坦，中午玩dota，下午去陪着同学打了打球（却是不曾料到今天会下雨），生活竟是犹如我印象中的一样美好。
只是有时空间里会有大神发一些奇妙的说说使我意识到自己的落后与羸弱（知耻后勇...）
有时也会想起，啊，天梯赛没有过诶。明明只是上周二却是有过了一个月之久的延伸感。

今天睡了懒觉，中午起来看dota比赛，也是蛮开心的。
淦。
所以我到底是该开心还是不该。

另外老杨周五告诉我她找到了求知欲，找到了热忱，感觉那就是我刚开学的那种感觉（还有假期玩emacs2333）。
啧，现在怎么没了呢。
一身的怠惰。
还有玩性。


Entered on [2017-03-11 Sat 19:06]  

Ended on [2017-03-12 Sun 16:20]
*** 2017-03-14 Tuesday
**** 又来水日记啦
因为水了节训练...
除了一道不是图论的还会做以外，就没有会的了。

昨天没记，也没有啥。晚上科协课教dp，然而做一道dp变形做不出来。就是lcs记录路径然后递归。。。最后差不多就是照着题解写的
递归反人类！淦！（然而一般题解都会说：递归的过程就是正向的非常简单）

今天图论，被各种方法支配...spta kruskal bellmanford dijkstra...
无fk说。
“这个题只要最小生成树跑一遍就可以了”
“这个题就是个负环，有很多做法啊随便选一种就好了”
然而最可怕的还是我听都不能听清的诡异名词......
啊。
啊啊啊。

回去再写= =


Entered on [2017-03-14 Tue 21:02]  

Ended on [2017-03-14 Tue 21:02]
*** 2017-03-15 Wednesday
**** 班会
头一次知道还有班主任，以前以为只有一个辅导员，没想到还有一个班主任...
而且居然是个非常强的班主任。
教c,java,py....
意见是好的，忠告是非常及时的，再一次给我敲响了警钟，也启发了我一些东西。
真的，太好的。

迷之小さなてのひら。
忽然觉得自己还好小好年轻。

淦，我这就去学ToDo然后列计划去。


Entered on [2017-03-15 Wed 14:41]  

Ended on [2017-03-15 Wed 14:46]
**** 补充
瞎感慨了一番。
说起来就是。
1.stitp项目要早搞，在大二上，一开始就要着手
2.论文和专利能弄就弄。专利不好搞，论文。大二下？
3.不要沉迷游戏
4.中国大学mooc....休息时不要去打游戏，去看点喜欢的东西。
5.一定要变强，一定要变强。

Entered on [2017-03-15 Wed 14:48]  

Ended on [2017-03-15 Wed 14:48]
**** 回去了！
肚子有点疼。先回去了。
晚上课不去了。辣鸡选修（好像要看左耳，我的内心？？？不如打游戏呢。。浪费时间也到不了这个份上）。

我把下面那个时间戳改回去了，看的不习惯的就右上角raw\blame切模式看好了，再不济仓库首页左上角commit看更新。（别真的改啊2333）

我到各种地方搜索都是C-f，也是醉。
再看一会C-cC-c的重复配置能不能解决就走。。


Entered on [2017-03-15 Wed 16:12]  
Ended on [2017-03-15 Wed 16:23]
**** 不做人啦！
摔！还没弄好！不弄了！

Entered on [2017-03-15 Wed 16:56]  
Ended on [2017-03-15 Wed 17:00]
**** 。。。
还以为终于可以a题了，结果超时了。。。
无fk说。
计划里是做三个题的。。结果只做了两个（这个还没a），虽然知道了yasnippet这神奇的东西不过还是觉得，不是很赚。（比起左耳当然是稳赚）

跟棣文聊了聊，发现他依然保持着他的活力而我垂垂老矣，在诸多方面....

买了个一百元的手柄，这个月预算没有了（本来就被我因为发现了steamcn而花去了许多买游戏。。。）。沉迷于买游戏。。。没有前几天那么热衷了

Everything goes wrong to turn into the way of life
随到了The Letter - 啊，人品真棒。

上床玩会手机睡了。


Entered on [2017-03-15 Wed 22:59]  

Ended on [2017-03-15 Wed 23:06]
*** 2017-03-16 Thursday
**** 今日
沈：人类啊，都是一样的，需要消费，需要释放。

早上起来之后进入虚无的无事可做模式。
发现南二食堂不知道比南三高到哪里去了，不论是早餐还是中餐。
早上喝豆浆真是满满的享受。

淦昨天晚上和沈打了会游戏忘记写了。
沈进入了和我类似但不同但是他非常狂躁而我不然的空虚状态（不过今天好像恢复如初变回dalao）。
手了把卡尔随了把卡尔，打的很开心。

不过估计今天的题我就都不会了。毕竟邹...出题。
无妨啊2333，毕竟以前也是，划水...签到...然后拓展一下视野知道有啥要学的。
只是欠下的越来越多。

n今天手柄到了，好激动好激动。
玩了一会手感不错，就是我没有一些act大作比较僵硬。
好开心啊。

啊。原以为这周状态会好一些的（其实就是好一些啊，好说歹说做了三道题。。虽然周四僵了，之前还是蛮不错的）

让我数一下。。
- dp 欠下几个亿
- 图论 还没开始学
- 数学几个小题题
- 唔 二分好像只差几个练习题了！终于在三周之后做完了第一次课的5个题orz。
好消息是下两周是好像会很闲的实验周。

啊不管了。
熬过晚上再说。
啊手柄到了好开心。
啊精分好爽。

Entered on [2017-03-16 Thu 21:39]  

Ended on [2017-03-17 Fri 17:13]
*** 2017-03-18 Saturday
**** 好困啊
早上本来约好去和学姐打球的，偏偏昨夜有雨，只好作罢。
只是可惜我起的好早好早。

没想到老杨也会有绝望迷茫的时候呢。

昨天上课也好绝望啊。虽然很短，但是很绝望。
图论什么的还是有点远啊= =我现在连个二分都要做好久，在知道思路的情况下...


Entered on [2017-03-18 Sat 11:09]  

Ended on [2017-03-18 Sat 11:27]
*** 2017-03-19 Sunday
**** = =
这两天差不多一直在玩吧。。
虽然今天有做一点题。。不过没做出来和没做一样= =。。。

Entered on [2017-03-19 Sun 21:45]  

Ended on [2017-03-19 Sun 21:45]
*** 2017-03-20 Monday
**** = =
我放弃了。。
写两个有序数列的新数列死活写不对，两天了还没弄好，照着题解一行一行的看也不得要领，也不想重新写，就是想知道自己哪里不对，就是想知道为什么，然后不停的错愈发烦躁。。。
蛋疼啊。

污点啊污点，和上次那个数列一样估计要以后再写了。

Entered on [2017-03-20 Mon 10:31]  
Ended on [2017-03-20 Mon 10:34]
*** 2017-03-21 Tuesday
**** 好像昨天没有写
今天讲概率和期望。第一个题我都做不出来。
数学不好。
十分绝望。

近来总是会想起：啊，这个应该记一下啊。
然后转头就忘掉了。

蚊子并不像前两天一样无时无刻光顾我了（手心都两个包仍在）

学校里开了许多奇怪的小花。

啊听课去了

Entered on [2017-03-21 Tue 20:27]  
Ended on [2017-03-21 Tue 20:38]
**** 卧槽我的emacs没了
炸了炸了炸了
什么鬼啊。。
= =迷啊。

Entered on [2017-03-21 Tue 21:14]  
Ended on
**** 啊哈哈哈哈哈
让我就用了一小会就又配置回来啦
不过yas还是没弄好，回头再说吧。
org还是得用才行。。
我想恢复hexo啊= =淦不过最近没空
明天起来把辣鸡matlab7.0配置到windows上。。然后看看能不能把yas配置好。

啊 好累，今天的概率又划水连听都没听懂，睡了

Entered on [2017-03-21 Tue 22:50]  
Ended on [2017-03-21 Tue 22:53]
*** 2017-03-22 Wednesday
**** 啊
被安利了一把好贵的伞哦
每天过的省吃俭用精打细算的似乎就是为了大手大脚的一刻。
不过还是好想攒钱，好想省下每一点钱啊。

其实对时间也是一样的啊。
设置各种emacs为的就是效率和手感啦。
不过说起来我浪费的时间真是一点不少（浪费是重点），比如各种强迫症必须做出一道题来然后一晚上啥都没干......

唔。今天下午开始下雨，下午开始上课....逃了那个讲网络文学的破课233。

这周是数学实验，就是讲matlab的使用。结果老师被迫把matlab课上成线性代数课2333。啊不过还是蛮好的，不用写作业不用这个不用那个啦。


Entered on [2017-03-22 Wed 17:54]  
Ended on [2017-03-22 Wed 18:01]
*** 2017-03-23 Thursday
**** 咩哈哈
今晚还行。
实验周的课结束了，好好的玩了玩。
明天也没什么事，睡个懒觉做两道题，然后使劲玩玩好啦（天梯赛前休整停课了。。反正除了前三节课还算能听懂从图论开始就懵逼了好吧。下节课字符串肯定也是。。）

上个周末玩都玩出了贤者模式2333。

哦对了，matlab还是蛮有趣的...不过玩的多了还是有点僵硬，是一种不自由感...翻来覆去净是那些东西（而且小数精度问题丝毫没有改观）。嗯比起c来毕竟少了些东西，也多了些东西，毕竟数学方面更强了。
而且我总是会想到切片什么的。。。
就想到抽空要学haskell啊。py也是半途而废啊。

...想啥都能想起自己欠下的账。

Entered on [2017-03-23 Thu 23:55]  
Ended on [2017-03-24 Fri 00:01]
*** 2017-03-25 Saturday
**** 日记
今天下午我和妹子联机打游戏了！23333虽然是并不熟的打崩坏认识的妹子
不过还是很开心的。

终于把数学实验（算是）写完了。

有个舍友爱好天文，今晚地球一小时活动观星到11点才回来，觉得有一爱好确实很好，能够平衡疲惫的学习的自我。我现在比较欠缺这个东西。若非要说打游戏是我的爱好总是觉得，像是明明知道自己是却还是止不住自己吃和玩的欲望的肥宅

然后有个舍友去魔都玩了。
我觉得他们都很强啊。

Entered on [2017-03-25 Sat 23:32]  
Ended on [2017-03-25 Sat 23:58]
*** 2017-03-27 Monday
**** 啊 好累
今天做电装实习。
早上因为这两天睡的太晚而没有起来。若非舍友不停的电话call我，恐怕我今天的实验就玩完了。
然后一天都在焊电阻啊什么的，中午一度被“红黄蓝绿”“红红黑棕”支配（分电阻分到怀疑自己是色弱）
说起来，组装电表什么的对于动手能力为负的苦手来说竟然并不显得多么难。虽然还是要经常向左右之旁的同学们请教，但是似乎，只是似乎，某些执着的念头没有以前强烈了。（虽然还是有时会想电烙铁什么的但那是思绪飘忽，并不会想：啊，我要是没对上怎么办，啊，我要是不小心烧坏了这个怎么办，啊...if...）
也可能是因为循规蹈矩步步为营，并无太多动手操作之要求吧。

一天都坐在没有靠背的椅子上比周末在电脑前玩一天还要累的多。
啊。

想玩游戏。想做题。想睡觉。
洗完了澡，上床了

Entered on [2017-03-27 Mon 21:25]  
Ended on [2017-03-27 Mon 22:05]
**** 哦对了
昨天就是玩啦
昨天还水了几道题

今天中午我只穿了两件单衣却感到非常热。我觉得令人绝望的夏天就要来了。
不过春天还是挺舒服的。

好了苦手这回真的要上床了。

Entered on [2017-03-27 Mon 22:07]
Ended on [2017-03-27 Mon 22:15]
**** 淦
我又回来了
我想起来那天沈给我发的山东无期的那个事，回头得好好研究研究。啧啧啧。

Entered on [2017-03-27 Mon 22:18]  
Ended on [2017-03-27 Mon 22:19]
*** 2017-03-28 Tuesday
**** 完了
动手苦手昨天晚上临睡觉犯事了。
我把手机掉到了水里，想晾一下电池，误以为是以前的手机强行把后盖拆开，拆开后发现一片陌生---它好像不是这么拆的，它好像坏掉了。我再装回去的时候发现外框都变形了。。。TAT
啊，昨天晚上我就想着无有手机的优劣就睡着了，
晚上做的梦都是和手机有关系的--跟父母通话，跟同学通话，虽然都是很奇怪的通话方式。每次故事的开头都是我醒来发现手机好了，起初我以为是梦，之后我就习惯了---已经忘却了自己是不断醒来的事实。
然后早上起来发现手机还是坏的。啊，为何不能有柯尔律治之花。

好了来列表。
***** 优点
+++++ 省去大量“辣鸡时间。
++++ 使自己不会处于不断的信息膨胀中，不再处于持续的焦虑中，可能会因此得到些许宁静
+++ 聚焦在外界事物之中
+++ 可能能改掉自己无事抬手机的习惯---这个习惯虽然是近期才有，但却已经到了入髓的地步：格式固定，看qq有没有消息、看qq群有没有什么消息并逛一逛、打开网页逛steamcn\打开max+看数据直播。
++ 使手机退居次位，mbp上升到极为重要的位置---随身携带。
  -- mbp携带率大大上升，损坏的可能性上升，我的焦虑上升
***** 缺点
---- 消息滞后（不至于失联人间）
   ++ 消息滞后，未尝不是好事。（其实我觉得失联也未尝不是好事）
---- 无法使用支付宝
---- 无法验证手机相关之事--邮箱 steam qq....等等
-- 无法打手游
   +++ 无法打手游（淦，到底是好是坏）
--- 无有方便的计算、查询之工具
--- 无法看pdf、看题（不过这学期干的确实少啊，上了头才会干这事。。）
-- 无法外卖


好了就这样吧。后天之后就差不多是放假状态了，就可以去修了嗯。
先享受这段时光吧。
我什么时候能失联呢。...我为什么会想失联呢。

日常叨叨-昨天科协的课都停了，因为我们不做题争彦大大很生气。
做题啊，做题。

Entered on [2017-03-28 Tue 06:44]  
Ended on [2017-03-28 Tue 11:52]
**** 淦 辣鸡字符串
做了半天第一个没对
真的是烦啊。。做到昏昏欲睡。

Entered on [2017-03-28 Tue 20:16]  
Ended on [2017-03-28 Tue 20:18]
*** 2017-03-31 Friday
**** 啊又要划水了
一道不会....
TAT
这两天算是放假吧。。明天上课。。比较迷的安排
之后还有清明放假。
啊，然而这两天一共没做几道题还都是水题....看了看树和dfs，感觉，还是有那么一点僵硬。还是得做一些相关的题。

唔，手机修好了，不过没有原来好用了。
嗯，以后也少玩手机啦。


Entered on [2017-03-31 Fri 19:44]  
Ended on [2017-03-31 Fri 20:00]
** 2017-04 April
*** 2017-04-04 Tuesday
**** 啊 好久没写了
写日记的频率一定程度上反应出丧志的程度。

最近其实本来应该好好学一下的。结果昨天出去玩被满街满景点的人锤了回来，今天憋在宿舍把DAC看完了，还写了点作业...
哎。

是这样的。5月中旬会有两个省赛级别的比赛，然后我本来是打算看大佬们去表演结果莫名其妙被不认识的学长拉进了组去划水...感觉自己完全配不上，树啊dp啊这种比较基础的都不行连搜索都才刚入门.....压力有些大。

结果还是把假期划过去了啊。

手机勉强算是修好了吧。对了，我昨天出去的那趟，甚至还没有我去修手机那天出去的愉快。
坐地铁让座，却被哪位鬓须见白的爷爷数落了一番，说什么年轻人不应该让座，学生啊年轻人啊都那么累，就该坐着，让他们站着云云....振振有词，夹杂着一点江苏的口音，我只能笑着点头，（一开始我以为是他认为自己并不老，听着听着觉得不对。。。）

感觉自己该去图书馆缓解缓解心情...老是处于焦虑之中，不愿学习，玩也不能得意，感觉似是回到了高考啊啊啊。

今天晚上先尽我所能的写些作业吧...明天，下午无事，看看能不能去图书馆看点书。

最近真的好热。
昨天出去玩，倒是看到好多放风筝的。想来我小的时候却是没有放过风筝。仔细看看，放风筝的大部分是老头，剩下的是一些孩子和带着孩子来的父母。想来也许在将来这些东西就变成历史变成书里的东西了吧。倒也许不会....可是我和这些东西打交道的时间长了，总是会有以后也许真的连书都没有了连童话都没有了的错觉在。转念想起那些在我原来住的那边的会展中心（其实就是广场）的台子上一堆老头在玩空竹和陀螺（空竹这个名字我在记忆里搜寻了好久好久，最后还是在网络上翻看的时候猛然间记起的），大概以后我们小时候玩的弹珠、摔板、卡片乃至悠悠四驱都会慢慢的消失在人们的视野中，消失在人们的记忆里吧。就如同我无从想象我父亲的童年诸如掏鸟吃窝窝打弹弓一样，后代们无从感触先辈的经验与时代本身，这可能就是骆以军所说的那种，活着像一支驼队的感觉吧。无可奈何，又恐惧觳觫（这两个字，是杜汇鑫不停的教我我却仍旧不会写的两个字），看着前面的倒下又继续领队向前。
没想到时隔一年我还是能想起这篇文章。
是不会多余的啊。

哦对了最近其实挺迷的。我跨进门之前还想着的事进去就忘了。一周前是父亲的生日，我从那天就记得要写个啥或者什么，转眼忘了，第二天想起来转眼又忘了...如是反复直到今日。
就像我明明记得有好多东西要记的...

Entered on [2017-04-04 Tue 21:28]  
Ended on [2017-04-04 Tue 22:39]
*** 2017-04-05 Wednesday
**** 啊好疼好难受
胳膊疼。。。
是那种时断时续的疼，有的时候我都会忘记或者以为它好了。
可能是晚上凉到了或者是压住的时间太久...我不知道...

晚上想了想还是去上了那个网络文学的选修，发现还是好水啊。任凭它吹的天花乱坠还是怎样我可能都不会去看吧....
而且会有迷之优越感= =

下午看了点bfs，胳膊疼的看不进去，就4点多去喝了碗馄饨，然而并没有好转...

晚上支持我写作业的动力恐怕就是ギリギリ愛了。虽是过期之毒不过还是很有用的。
一会看看白书睡觉了...

Entered on [2017-04-05 Wed 21:54]  
Ended on [2017-04-05 Wed 22:03]
*** 2017-04-10 Monday
**** 都已经忘记上次是什么时候了
赶紧趁着多余的零散时间写一写。

上周的状态还好，将将做了几个题。
周五周六又是一通玩，昨天倒是比赛做了好久的题，也是补了不少的东西...什么背包啊，快速幂啊，好多东西都忘的差不多了。
明天又有预选，估计是过不去了要划水了hhh。
比我想象中的来的快啊。我以为怎么着也要到四月中下旬的。

这几天南京骤然变冷，还止不住的下雨。我又减缓了更换衣橱衣服的计划。

两天前又拾起了好久好久以前，我疯狂的痴迷的猎命师。犹记得在那个手机还不是触屏的年代，我在（去哪里的已经记不清了的）火车上日日夜夜看猎命师，一遍又一遍，母亲担忧又愤恨的说我，我依然如故...
单从猎命师这一文来说，我绝不否认他的功力和想象力。只是九把刀这个唬烂的作家的风格竟是有几分与骆的神似。这样却也能解释当时看西夏旅馆时对语言的执迷与熟稔...

这恐怕也是丧志吧。
新的学期真的是丧志了好多。闲暇本就已经被压缩还让我这样的挥霍...

大学可能就是这样的彷徨吧。一往无前的追求自己想要的，对我这种没有千军万马没有无惧只有优柔寡断这种情绪格的宿主来说，可能还是有些困难吧。（也可能是自己想要的太多然后迷失了方向hhh）

哦对了，说来可笑，昨天卡在快速幂的一道题和一道叫“小学生都会”的题上，眼睁睁瞧着别人都a过了自己死活不能过然后心态爆炸就不想做了。
就这样吧，我去吃饭一会上课讲昨天的题了。

Entered on [2017-04-10 Mon 17:12]  
Ended on [2017-04-10 Mon 17:20]
*** 2017-04-13 Thursday
**** 哎....
周一上课也是好多都没听懂，概率与统计确实不好...

周二就迷一样都出了好多期望题，我们就签了个到差点做出另一道（向下取整写为四舍五入..害得学长疯了一样都怀疑算法..明明是题目没写完整嘛）然后错失了去湘潭（淦，居然是湘潭，我也是今天写日记的时候才忽然想到，淦，居然是湘潭）打ccpc的机会。
啊，这么说两个省赛级别的玩意都没选上啊。天梯也没选上，蓝桥杯都没报名...这段时间...好气。

还是继续开搜索的好。
周日周二连续两天搞得我昏头涨脑，生无可恋。

昨天被迫去搞了会access和sql...毫无进展。只是感觉他们没那么难...
好啦我再去学一会就要去上课了。

Entered on [2017-04-13 Thu 08:43]  
Ended on [2017-04-13 Thu 08:51]
**** .....
ctmd辣鸡学校oj，我写%lld就算错，写%I64d就对了。
而且i还要大写...让我这种从来没写过i64d的情可以堪

Entered on [2017-04-13 Thu 09:00]  
Ended on
**** .....
然后不出所料的，小学生都会的那个题也是lld的问题。
5555555 无怪乎心态爆炸
（懒得切到acm里去记了）求逆序： if(x&1)r+=1<<(15-i); x>>=1;(i=0:15)
开心 上课去

Entered on [2017-04-13 Thu 09:18]  
Ended on [2017-04-13 Thu 09:20]
**** 今天
今天奇热，下午上体育的时候好多人都身着了短衣短裤。

不过今天从下床始我就止不住的涌上疲惫。走在去体育场的路上感觉身体的能量在一点一点的蒸发。
体育课上练习上手发球，两边互相扔球。就几轮的扔球我就已经脱力了。
体育课最后还要跑5圈。跟着大部队慢跑3圈再以自己节奏跑2圈。我死命跟上了前三圈，第四圈进入龟速慢跑状态。我的身体已经几乎失去了平衡感，如果低头看自己的影子便有向前倾倒的趋势。我却在这种极度乏力的状态下意识十分清醒，就像晚上睡觉时偶尔会出现的明明身体已经想睡到了极点脑子却异常兴奋。（我好想写就像千年一败的最后一战回光返照道心归一，清晰的感触到周围的一切的佐佐木小次郎）那个时候我感觉我可以想出一些绝望的美妙比喻或修辞法，只是我的胸口和身体发出的撕心裂肺的哀嚎不停的把我的意识游移回现实。
之后拖着烂泥一样的身躯，我缓缓走回宿舍。。

回到宿舍就是回到了娱乐的世界。
身体已经说不出话来。
脑子也不想转。
被迫的写了会作业和c语言的作业（啊，c++果然和c不同，也果然和acm不同。acm用到c++的可能只有模版和stl容器一类的吧，其他的c++那些面向对象的特性一点都没有用到hhh）
啊。
啊。。

不知道老杨在今天的什么时候提出那个好久以前我看到却一笑而过的问题：如果有一天只能靠烧书取暖，你会先烧什么书？
许是因为太久不看书，心境的变化，我竟觉得这个问题毫无意义...换做以前准是心中构想出一套既能装逼还能讲出门道的书单；或是按照骆以军那样构想出两个人，相互在末日中幸存烧书，互相似乎有默契似乎在比对似乎是接龙的一本一本的...看着燎烟淹没自己与对方；又或者是像圣徒看着每一本被烧的书心中感同身受的灼烧着痛苦着，甚至说不定会在一片绝望中自裁也不愿伤害剩余的书；也可能是一份极度绝望毁掉世间最美好的一面的清单与书的死法......
但现在不会。现在我只会去想，啊，有好多书啊，啊，有好多书我还没有看啊。我只会去想，“信息爆炸”，如果把那些论文、媒体、网文，如果把那些自媒体全部算进在内...
只会去根据最近的经历（看了九把刀的猎命师）想到：啊，还有这么多唬烂豪洨瞎搞鬼扯乱写的作家，有那么多稀奇古怪的摆在热销平台却毫无价值的书，有那么多利用人性写的乱七八糟没有营养的书（比如什么超现实！不可思议balabala；你不得不知道的balabala你应该balabala；冷知识；灵异事件精选...我只是说一下我还有印象那天和小陈一起去新华书店看到的诸多乱象）怎么可能烧的完嘛的我渐渐退化为一个平凡的无志青年。（不过总比江丰会想到烧本子好得多）

不行了我再怎么兴奋也撑不下去了，虽然明天的c++实验内容没写完...明天再说吧。这已经接近两周的校队停课怎么样也要好好的享受享受....（或者是给自己更多的....折磨...自杀之路嘛2333..）

Entered on [2017-04-13 Thu 18:25]  
Ended on [2017-04-14 Fri 00:07]
*** 2017-04-18 Tuesday
**** 啊 摸鱼了好久...
不训练也不自己做题感觉自己天天鬼混摸鱼。（算下来我好像除了有一阵研究了下搜索这两个个月来没做啥..）
周末的时候电脑让我玩坏了送去修了...月预算爆炸。

我大概就是那种，即便没有烦恼也会自寻烦恼的人吧...
摸鱼都不能好好摸。
一定要找个理由，最棒的理由就是：我学了好久啦 我学累啦。然而现在没理由的怠惰摸鱼就会很难受，摸鱼之余随时感到不适与烦躁。
花钱也是啊。
这种非常矛盾的心情却让我想起了一点干系都没有的周一在台上高谈道德的思修老师。然后就想起了那些奇形怪状的电车难题。不过那就是另一个很有趣的话题了（关于为何会出现，为何会恶搞，为何如此邪恶...）。

校赛大概要爆炸了吧。这段时间我何止是没状态...简直就是...大脑中回路全部如车祸现场扭曲混乱起乩。
啊，对，还有那之后的期中。

周末的时候校庆活动...先于图书馆前的空地上看看不到的演出，听听不进去的演讲，然后...跑跑不下来的步。
说起来他们居然还把那个上了春晚的老红军请过来了...哎..那么大年纪也是不容易..
我根本就没跑下来啊哈哈。
连跑带歇再而衰三而竭的我后来就一直在走了..心想下午还要去找修电脑的..不过身体是愈发的向一个标准死宅的方向前进了，无体力无力量无韧性无忍受能力...

猎命师有点烂尾啊...臆想中的超级混战确是发生了不过义经死的太快..还有一些不科学的强的什么美杜莎（全场无区别石化..）塞壬什么的（控制阿不思什么的...过分啊）结果都被个百手人屠莫名其妙的干了。看的很不爽啊。
其实我觉得在大决战的时候就有点僵硬了...因为太想顾及全盘而丧失了主线，因为太想完满而把人物稀薄。因为太急着想结尾把前面好端端的坑强行填满...
前面的铺垫真的很棒啊，干，为什么要烂尾！好好写啊！
干啊，根本不是有点啊！我tm很不想说但还是要说啊！
从时间区就烂了啊，烂了啊，烂了！
早要烂就不要把前面写的非常有趣啊！
睛明变成打酱油的，雷力为了使人类的分量更重强行强，牟庆打了酱油，诸猎命师脸谱化变成放技能的法师，凯因斯莫名其妙的变成了极致白烂变态，伤心拔刀强行参战，上官主角光环笼罩，到后面人物没有了心理描写，一点都没有了，前面的铺垫一点用的没有，只剩下流水账一样的打斗，我只想说你tm写了个...
童年的回忆画上了不完满的句号，这样很不爽啊！

算了算了，今天最好上课（虽然我满心不情愿，但是在不训练我要废了），然后回点血吧。感觉自己摸鱼要把自己摸死了。

Entered on [2017-04-18 Tue 16:01]  
Ended on [2017-04-18 Tue 16:50]
**** ...
哇的一声哭了出来
成了一道题没做出来唯一一个被零封的。

Entered on [2017-04-18 Tue 20:32]  
Ended on [2017-04-18 Tue 20:33]
*** 2017-04-22 Saturday
**** 啊明天要比赛考试啦
好紧张啊好紧张啊。因为没有复习没有准备啊。

感觉自己在队里就是蹭的。。那么多东西不会也不去补。今天做二分还差点没做出来（我觉得好多时候我还是认不出二分）（vijos的数据真是没话说的恶心）

就像我对沈说的：明天比赛再沮丧一下 然后稍稍振奋精神再学两天 然后继续进入无主神游状态。

今天又找了好多泽野的歌...说不上来吧，可能坦克打多了，习惯了腔调。

周五去修电脑，中午出去转了转，从浮桥走到了鸡鸣寺，骑自行车回浮桥的时候还在七拐八转的胡同里迷了路。穿着短袖（后来我发现我那一天的上衣都是反穿的）短裤，凉风拂过，林间大道般的马路，倒是感觉很好。

拐到鸡鸣寺路口有个老头叫住我，要和我聊天。说是聊天其实是给我相面。我倒是没经历过，也就甚是配合的演了演。
他从脸型，鼻梁，嘴唇（不知道他有没有从我反穿的衣服那看到什么）进行种种推测...不过居然多为恭维之言，什么有能力，不与人争什么的，然后提出要看手相，并要收钱。他说，他们祖传看这个，原先有一所工作室，但是因为写字楼太贵，迫不得已就下午出来，上午在网上给人看...
比较有趣的是在他提出每一点的时候他都要加一句“我这样说你还明白？”，仿佛我的人生命相都已经注定甚至即使发生过的也应该按照他所说的那样，要我明白。
我跟他说我很好斗。他先是微微圆斡：好斗是纠缠到底分出胜负，继而说我一定不是好斗的，在我一再的坚持下变为我相较于那种暴烈之人算不得好斗。
感觉当时应该让他算一算看一看我的手相的。哈哈。

我到现在还是不很会拒绝别人，一般都会找一些看似非常好的理由：比如如果有人推销，我会拒绝以穷；如果有人推荐班，我会说我有竞赛我很忙；上次去修电脑，他推荐我再装个机，我觉得他给的配置并不好，而且他有些过于急切的想让我装机（我找了理由之后后来更明显），我就不想装，却不是直接拒绝，而是佯扮出十分委屈家里人不给钱的样子（演技倒是进步不小）。

睡觉啦，等待明天等待我的灭亡了。

Entered on [2017-04-22 Sat 23:36]  
Ended on [2017-04-23 Sun 00:06]
*** 2017-04-23 Sunday
**** 啊。
闲下来写日记。舍友都睡了，游戏我也玩过了（半个小时轻松愉快），考试也考崩了，比赛也比完了。

比赛...怎么说呢，水的题是水，不水的题干脆没法做，然后剩一两道恶心的题拖时间= =...
不过这个扎气球挺像回事，做出个题就放个气球，倒是挺正式。我说事先为啥要找志愿者，原来就是分发气球的。。。
就是。。学校的这个气球。。会炸。。做着题注意集中的时候突然boooooooooooooooooom来一下，简直不要太sweeeeeeeeet。而且听它爆炸的声音，竟然非常结实和强劲，好像在说他的质量非常好一样...
嗯。还有就是比的时间好长啊，我也没带吃的（我也没法像旁边的心乾dalao一样吃物无声），然后有耳机却没有歌可以听也是好烦啊（什么时候比赛的时候可以听歌啊啊啊），全程都是我脑子在以一种奇怪的方式循环我上午听的几首曲子，说真的没有我就要死了啊。
说起听歌。。听完东离的配乐忽然好像看东离啊。（说起来斩服我也是先听的歌后入的番..听歌入番..）
最后只做出4题= =有个题我训练的时候做过但是我就是死活想不起来怎么做了。。倒是能想起那天那时候我在神游。
嘛。感觉还好啦。正常发挥吧，虽然j题有点迷，c题没记住。

然后晚上考高数，血崩。刚看的笔记本的题就记不得，刚看的公式就记不得。。可能是内存满了吧= =

去学科楼的路上开了一片小花，好棒的。

上周四复又听到老杨和江丰的声音，感觉十分的幸福（我大概是有声音控的病吧..讲真从老杨的哼歌我就表现出了异乎于常的兴奋与幸福..）（甚至可以说从..到..）。彷佛两人依然在我左右...就是听的感觉老杨好累（所以我也不能犯懒啊，大家都在努力都在奋斗）。

帮杰哥dalao改了改程序，感觉工程好烦（也可能是我没有下决心踏进去）。

ThreeFiveNineFour!词好曲好!意外收获!(我昨天当时是去找BL∞dy f的，顺便收了一波泽野2333）

今天脑子不太好用了，记不得还想写啥了
晚安。

Entered on [2017-04-23 Sun 23:46]  
Ended on [2017-04-24 Mon 00:36]
*** 2017-04-26 Wednesday
**** 啊。。怎么这么晚了
本来是一个美好的，没课的（其实有但是压根不想去的辣鸡网络文学）下午，怎么就没了呢....睡了一觉，起来疯狂改程序，中间打了半个小时游戏，吃了个饭，写了会英语作文，然后中间的中间玩玩手机...一个下午啊，活生生的一个下午啊。

这两天一直忙着帮杰哥做程序orz...c语言做一些界面之类的东西是真的僵硬啊，它太不灵活了，我做个能刷新的计时器需要多线程+5个全局变量控制两者关系...我的天，头疼死我了。原来用的sleep根本行不通，辣鸡c就没法动态的处理东西（就比如获取一个10s后的状态...）...多线程根本学不通，刷新屏幕也是强行设置坐标printf覆盖，简直了...做了足两天，差不多把他那个程序重新写了一遍，把结构逻辑都改了一遍（话说用switch做重复工作很反人类，明明一个数组就能解决orz）
哎，都是泪。主要是辛苦，还有就是要思维上各种绕，绕过无法实现的地方，绕这绕那...感觉底层真tm，真tm。（其实我想的是一身抱负无处施展，转念想自己现在还没啥抱负233）

前两天把于柳惹到了orz（再再之前还用差不多蠢的方式惹了小染）...就复又想起那个棣文很久以前问我的一个问题：怎样才能变得自私？我无言以对。现在想想这家伙在志愿者协里混的风生水起不亦乐乎倒也是不错。（咳跑题跑题）从来不会从对方的角度考虑问题甚至根本不会考虑对方的想法感受就口无遮拦的提出自己的观点意见（虽然我很想狡辩说自己是很替对方着急才..）
于柳：体会不到别人的感受挺好的。说起来好笑，我很在意别人看我的眼光却体会不到别人的感受，再具体了说就是自私吧，就是自私。方方面面。
哪里好了啊。纯粹的利己，纯粹的计算，天天活在对未来的计算、期望、判断里。吃完饭拿过小票来加起来看看是否属实，逛超市完全是精打细算，走在路上脑子里全是接下来的安排，渐渐丧失了感性的好多东西，完全看不到好啊。（我现在做的这件事值它所占用的时间吗？甚至明天下午杰哥请吃饭我也有不想去因为它耽误时间...从这个角度可以解释我的很多行为嗯，就从一纯自私利己的角度出发，你们不能理解的地方可能就能迎刃而解）
想来哪怕是不让可可玩水吃彩蛋也都有这样的一部分在内：我只是从客观上分析，从“本可以”上讲，完全弃父母的感受可可的感受于不顾（当然我还是觉得惯的有点过，惯的有点过。虽然我现在感觉如果是自己的话可能也会惯着他...但是从非主导的旁观者的角度...）。
所以我情商就是好低的......可能有时会敏感但大部分时候神经都是大条的...

写着写着不想写了...（不要聊了、我不知道要说什么也没什么想说的，真的是心痛）


Entered on [2017-04-26 Wed 19:45]  
Ended on [2017-04-26 Wed 20:41]
** 2017-05 May
*** 2017-05-04 Thursday
**** 

Entered on [2017-05-04 Thu 22:12]  
Ended on
**** wtf？？
我的org出问题吗？？感觉好怪。。。
能写就好回头再修吧。。。

这几天好累orz，以后回家要慎重（并没有像原先说的那样在家里好好休息...，坚决不坐车，坚决不坐夜车。
总之...这周可能把上周的疲惫遗传了下来，完全不在mode，每天困倦困倦困倦，大概只有打游戏、睡觉、洗澡的时候提得起精神...
我需要..好好休息那么几天...md好烦..这几天都没怎么做题（好像做了几个暴力和二分，跟没做一样2333），今天下午好容易没事了，又让我打了一下午坦克= =（不过打坦克很爽啦，尤其是看着数据从绿转紫转橙真的好爽）

啊，五一的回头再写啦，现在不想动。。明天下午大概能多学一会。。


Entered on [2017-05-04 Thu 22:14]  
Ended on [2017-05-04 Thu 22:29]
*** 2017-05-07 Sunday
**** 丧志

Entered on [2017-05-07 Sun 21:51]  
Ended on
**** 丧志至极！
等到我休息足够了。。精神充沛了再回来写吧。。

Entered on [2017-05-07 Sun 21:53]  
Ended on [2017-05-07 Sun 21:54]
*** 2017-05-10 Wednesday
**** 趁着听讲座写写日记...
上次去上选修课老师都没去...如果要我说的话老师可能也犯了和我们蕾丝都五月病然后彷徨痛苦承受不住下方无人听课的空虚场景。

昨天上课一道都不会...有并查集，区间dp，区间第k小，然后两个智商压制的什么数学题、被掩藏了的完全背包...
//淦。我还是回去，学我的可怜的搜索吧。

这个讲座好像很有意思的样子...orz每学期固定要听一次讲座，这次居然是讲网络政治，不是什么经济啊..军邮啊..核心价值观解读啊。是网络啊，网络。

五一回去蛮开心的...看到可可，父母奶奶都过的滋滋润润，想着一些零零碎碎的生活琐事，诸如谁家谁家怎么怎么样啊，地里又怎么怎么样啊，狗需要驱虫啊，要开垦后院啊....
就挺好的。
可可终于不再是单字单词的蹦了，原来都是用指、用摇头点头来传达其意图，现在已经会用语言来表达了...怎么说呢，因为我是两个多月没见他所以感觉特别突然，很别扭也很好玩。也越来越像一个坏小了。
就是做夜车好累啊。
好累啊。
半夜两点停在高速路里的服务区里，离家只有十公里却出不去。最后也没有知会车的人一声就自己离开了，不知道车上的人会怎么样。我特别在意这种“之后会发生什么事”然后自己把之后会发生的事情推测一番（就好像下围棋一样全部计算一遍，然而事实的综合复杂因素太多，无法得出最佳判断，事情也不会几乎照着剧本发展，但我总会，不由自主的，有这样一个判断。而且事情如果与计算有所出入还会大为光火...总体上弊大于利吧..它跟我的杞人忧天和价值代换和自私和控制欲等特性不谋而合）

今天到了30度，昨天才20度....这一下子就差了个天与地。
周五下雨，我又走那条从学科楼回来的那条路。蛙声大作，而且在我途径之时毫无畏惧继续聒噪。我很生气啊，就在粼粼微光的细雨中蹲在草地之间伺候欲寻得声音源头捉一只（天知道是什么，癞蛤蟆？牛蛙？青蛙？）出来泄愤。
然而最后拿一根棍拨来拨去，什么也没找到，只有周围的呱声此起彼伏，只得悻悻离开。

淦，辣鸡讲座，不愧是马院讲毛概的老师，能把人催眠。
md认真听了听还有诡辩...讲道理全靠诡辩。
不如放个纪录片。

想写啥都忘记了...- -

感觉现在陷入了上学期想不到都颓废之中...从三月的入坑steamcn，之后的四月痴迷dota比赛，五月开始重拾坦克...最近的日记越来越少，皆可看出我已经游移在了一种堕落的路上...
渐渐变成反面教材。


Entered on [2017-05-10 Wed 17:31]  
Ended on [2017-05-10 Wed 18:54]
*** 2017-05-15 Monday
**** 感冒了好难受
感冒了嘤嘤嘤。
大概就是四天之前嗓子忽然很难受，两天后嗓子不难受了，开始流脓一样的鼻子，然后昨天开始就是疯狂咳嗽鼻子淌水...

其实还好...除了精神有点萎靡（我跟同学说半个我感冒死了其实夸大其词，顶多四分之一），然后止不住的咳嗽和流鼻子有时打喷嚏...后者做起事来就习惯性的无视了，擦鼻子什么的都已经变成机械反应。

令人振奋的是我居然，我居然开始学习了。大概是因为感冒所以感觉做什么都无所谓，于是就学了学习。

最近看高中的奥数书，感觉好难，已经想放弃了...不过还是在强忍着看。
主要是图论数论要补...组合数学感觉不用补了，方向偏了...我看了那期概率和期望的题，感觉很迷。有的是玄学题，有的是矩阵快速幂，有的是方程组高斯消元...反正就是...没啥固定的玩意。

紫书也开始迷了...不给全代码然后要“完全理解本题所有细节”，然后一点图论没提过的就直接DAG欧拉什么的，过分啊。

唔...就上来吐了吐槽。

昨天母亲节也没做啥orz...不过母亲每天都挺快乐...

哦对了今天听了个大神的讲座...感觉暴力模仿大神不可取。大神大二铜奖省二省一然后...“及时止损”...（我是觉得dalao继续搞下去肯定飞起）去搞项目，大三就去了intel，然后又去了谷歌，还去了小米实习...我擦这tm怎么取？？这tm怎么取？？
get到的就是要技术过硬，要“及时止损”（皇叔的意思是功利的看是要这样，然而他喜欢acm就搞了一整个大学2333不过皇叔感觉好自信，气场无限大好吧），要学精一门语言并渐渐延伸（你面向对象会一个c++，面向过程会一个c，应用学pyjava，思维学haskelllisp，亦是皇叔原话。c和c++的好处是靠近底层，靠近汇编。好像是应该先学汇编，然后再学语言时便能通畅），要明白自己想要的是啥。

然后周末玩了beholder还没开始玩就感觉要被压抑死了....什么破游戏啊！淦！这这这算什么类啊！

同学们都去打比赛了啊，我自己也要...努力赶上啊orz。

啊啊，早睡觉了。也不早了


Entered on [2017-05-15 Mon 22:40]  
Ended on [2017-05-15 Mon 23:24]
*** 2017-05-16 Tuesday
**** 啊啊啊
没参加蓝桥杯被老师嗦了。大概是组里最菜也最闲啥都不干的一个。哦对天梯赛也没参加orz。。。天梯赛。。说起来就是那个树全都挂的那个预选...
省赛是概率挂的那个预选...

然后他们在这讨论住宿和行程分组，什么十人一队啦，一队一个宾馆（要住四个宾馆233）

哇，说着说着就说到奖金了，什么去年蓝桥杯的奖金（还有前年的）都没发啦，今年天梯赛的奖状到了拿着奖状去那那那领奖金啦

....挥之不去的压迫感啊。


最近可能因为感冒的原因，做了许多奇奇怪怪的梦。


最近比特币病毒风行，不由得有些后怕。

发现这篇没发出去，尴尬。

Entered on [2017-05-16 Tue 21:16]  
Ended on [2017-05-19 Fri 21:04]
*** 2017-05-20 Saturday
**** 额。
我又开始研究org的gtd了。。以前是浅尝辄止——主要是没有实践下去，所以就没有什么收获也没有学到...这次不知道会不会好一些。

我成功的把我mac上的所有用的到的acm的东西都git上了，开心的不得了不得了。

昨天下午比赛划了水深受打击。晚上把git整好之后开心的陪着小染他们玩了两个h游戏，然后继续做题，然后被一个10^5*10^5爆int给难了30m......我感觉我做的水题是不够的，好多东西都没有到一种生理反应的地步：时间上100n^3 1000n^2 10000nlogn ，7位常数就已经是边缘了。int 9位，int 9位，int 9位。

今天好多啦，休息得当，作息适宜（虽然昨晚还是修了点仙），上午把论文写完（发泄了我对网文的不满2333），不过是能够非常真切的感觉到，自己不太会写东西了。写的慢，还出奇的烂。那感觉就像是有时候自己写了很丑陋的代码再回头去看的时候不忍卒读甚至会不能理解语句含义一样，很难受。中午小睡一觉起来，收拾了收拾（然后发现没发收拾），花了20m拖了拖地，然后去听回归的dalao们的交流会（科协25周年纪念 520）。

然后吧。就是觉得自己实在是太菜了....看了份要学的东西，我差不多是只学了3%的样子吧= =。。反正就忽然很绝望。而除了acm还有辣么多东西要学...所以我先从gtd搞起，然后最大化每天时间吧...

这两天..没怎么玩...想想自己steam里大概100个等着我玩的好游戏，还有愿望单里将近200个游戏...一时十分痛苦。

舍友开着窗户（虽然是没看到但是还是觉得）开空调真是无fk说。
还有开空调吃外卖也是挺...orz

去研究(不不不，去玩了去玩了！我的精神有点不好了都）z了拜拜拜拜

Entered on [2017-05-20 Sat 19:07]  
Ended on [2017-05-20 Sat 19:28]
*** 2017-05-21 Sunday
**** 虚惊一场虚惊一场
我以为我的capture又崩了。
是我加了个C-c a的快捷map的调用，结果emacs就疯狂出错。。。不是很懂lisp= =上网也查不懂...还好只是昨天改的不然我就找不到问题所在了。。。。。。

Entered on [2017-05-21 Sun 14:40]  
Ended on [2017-05-21 Sun 14:42]
**** = =
以前是因为懒和贪玩所以不写日记
这两天是因为忙所以没写日记。。。。。

可恨的520过去啦。好是悲伤啊。好是悲伤啊。

竟只有为数不多的慰藉可以依存了。

Entered on [2017-05-21 Sun 22:53]  
Ended on [2017-05-21 Sun 21:55]
*** 2017-05-25 Thursday
**** 写日记啦
最近发生了很多事情啊，可是都没空写。。
比如柯洁的人机大战。三番已经输了两局了。联系谷歌的io大会所说，现在的时代是人工智能的时代。（这句话换在去年的我大概关注点会在现在的时代是vr的时代2333）
比如人机大战忽然被封，据沈哥冷静的分析，是在防民。（其实挺对的，比起上面，下面更混乱更难整治）
比如wings事件，ehome事件。
比如“美国的空气都是自由的”

然而两耳不闻窗外事，做题！


Entered on [2017-05-25 Thu 20:03]  
Ended on [2017-05-25 Thu 20:37]
*** 2017-05-28 Sunday
**** 放假啦
补了一天动漫。。看完了青驱...
怎么说呢...嗯。后面有点脱线，故事就跟三体到了后期一样飞了，想表达的内容被想讲完一个故事的强烈欲望给掩盖了。

捕梦网诶。
我觉得蠢是没法洗也没法治的。

啊假期只有两天了。。我觉得玩一天写一天作业就过去了QAQ...
不甘心啊，不甘心啊。
想做的事太多了。
最近有在好好做题，每天3h几乎没有拉下。终于能做dfs模版题了..不过还是得补。dp的话是想补的，就是补起来差距太大。感觉lcs什么的跟四大dp不是一个层次的。数学也是半途而废因为实在是补不动......先做搜索，先做搜索，这样安慰自己道。
游戏的话，这周也是就玩了玩战砖，和手游。我卸了max+，因为最近忙（回归正轨）所以也没太大的steam买游戏的欲望，总感觉把自己的那些游戏玩了的话就要花好久，大概丧志一年才能玩完吧...我哪来这么多时间丧志...所以..想来夏促可能要被我pass了。
想看动漫，想看黑魂剪辑，想看史丹利，想看机核，想看允星河。（所以我不上b站，诱惑太多）

嗯...最近热的过分。我早上被热醒开窗开门之后就没再睡着。不过中午还是补回来啦，算起来能有8小时多hhhh

听说家里又买了块地，还带着不少树，不知道等我回去能不能看得到。

Entered on [2017-05-28 Sun 23:37]  
Ended on [2017-05-28 Sun 23:57]
** 2017-06 June
*** 2017-06-02 Friday
**** 啊啊，最后还是起来了啊。
万般不情愿，还是坐在了这里。
我的眼睛都还没有完全睁开，我的身体的各个部位都在呼号，但我无能为力。
这种强制性的失眠简直就像是日蚀，一点一点剥夺了视界和对身体的掌控，只剩下惊惶和各个部位的阵痛。
什么啊，我居然在这种当口纠结用词，难道不应该抓紧写完赶快睡觉吗。
大概是想通过这个途径来熬过这个可怕的夜晚吧。

昨天和老杨聊了许多，心中舒畅不少。聊了些关于汤圆先生之类的种种话题，说起来是我把一些我积存的垃圾倾倒给了老杨。被夸赞善良还是心中暗暗欣喜的。
买了许多奇怪的书，却都来不及阅读。努力想跟上时代却发现根本就没有那样的基础。
哦，倒是看了篇克苏鲁的神话，那感觉真是超级不舒服的。一种粘稠的，失去向度的恐惧弥散其中令人作呕。
昨天其实是浑浑噩噩度过的。本来想做一道题，却被题解的操作吓了一跳。然后作业也没动，课也没怎么听。。
从我不停的找沈哥（新外号沈脖子）和小染聊天就能窥得一二...好状态真是不持久啊。翻看一下gtd，上一周的3h全部完成，甚是吓人。放了个小假就有点迷啦，诶嘿嘿...
还好还好啦，紫书我想做却是有心无力，总感觉二叉树与我不合，怕是要有一番争斗。白书的最开始的阶段原先觉得很难极难现在终于可以接受了。每个时期都能找到一点事情做，那就还好吧。
更正一下，那已经是前天的事情了。只是我犹活在梦里。


今天的话，本来是挺开心的一天的，虽然还是浑浑噩噩的，没有上一周的清醒，但是我有足够的理由把责任推脱给该死的天气上。闷、潮、热。不知道下午的体育是怎么开始的，但是一开始的时候确实是一种煎熬。以至于我一度把它当作一种修行活动看待。但是活动开了除了许多汗又补充了些水分后，好像也就没那么热了。正当我兴致勃勃与人打球之时，悲剧就发生了。可能是身体太热太累，但精神上浑然不知，我竟在一次救球之后重心不稳趔趄向一旁。（犹觉得「热累叠乘重压，失去平衡」的说法很是精确）之后就是无限苦痛的崴脚生活。
说来奇怪，我的脚刚崴的时候并不痛，就跟剧烈运动后并无太大感受，第二天会产生爆炸式反应一样，我自己去了医务室，去超市买了瓶饮料，去食堂买了饭，拖着身子移上了六楼，并没有太大的痛楚。冷敷过之后，疼痛就没有停止过，一刻也没有。就拿现在来说，无论是承重，还是只是单单把拖鞋穿上，都会有剧痛的风险。
只有失去了才会知道珍惜。这样无谓的话吃过无数次也不会真切的明白。
我现在，相当于少了一只脚，不方便的很。但是只要，只要可以，我也会忍耐剧痛，去使用我崴了的右脚。因为我能感受到，我的左脚承受了太多，它在震颤在发抖，我生怕它也会随我的右脚而去，那个时候我就真的孤家寡人了。上下床，走路，我都在考虑着左脚的承受范围。。。
说起刚才我起来，是因为我因为持续的疼痛而不能入睡，终于到了一点我摸完手机，睡着了那么一个小时。起来的时候是两点，是热起来的。舍友似乎还在深层睡眠里睡的正酣。而去还伴随着强烈的上厕所的欲望。无奈我忍痛下来，蠕动着撑开门，单腿跳的上了厕所（上厕所的承重的痛苦也是极其可怕的，好在没有人，我可以借用可以借用的一切，也可以叫出来。又开始冷敷我的脚。

疼痛并不使我清醒，反而把我的脑子搅和的一团糟。想到还有好几天，我已经不知道如何安排这样的时间了。是大把的好时光。

写到这已经没有什么好写的了，感觉一切成空，如梦幻泡影。而又似乎唯有当下的痛苦是真切的。

如果能心无挂碍的，简简单单的过上几天感觉也挺不错的。

对了，学校里有着大片大片的荒地，分布在学校的各种边缘角落。比如北体育场东边就有一大片空地，上面长满了一种很小的，齐腰的，白色的小花。这里一提，枉我狂号西坡，其实不过别人安插的但是却有一种寄托挂念象征的东西罢了。父亲的西坡生活还是丰富而多彩的。不知道原先就忙不过来的几块地现在又收了一片王国的现在会是什么样子。

祝可可六一快乐！其实我觉得这小子天天六一根本没啥好过的。六一这种节日吧，感觉更像是给大一点的小孩还有更大大的像我这样大的小孩的一种节日（抛开那些沉重的不谈，那是大人的事），一个念想，一个在逐年变换形状的念想。

啊，好想睡觉。
我从十点躺在床上，到现在不能寐，你问我是一种怎样的体验？
怕是就跟现在我的左脚的心情一样吧。

Entered on [2017-06-02 Fri 02:20]  
Ended on [2017-06-02 Fri 03:24]
*** 2017-06-07 Wednesday
**** 写日记啦
被沈哥强迫来写日记了。。（6.7
刚刚第一次去打cf.....一开始好怕，签到题都做的好慢思路不转。结果就是签到题之外都没做。。（也不能说是结果了，菜摆在那里

呃，上次脚崴了之后是不是就没再写啊。那是我的不好啦...这几天找了个“脚崴”的理由疯狂摸鱼，摸的我都不好意思了。补了钢炼03版...那可是51集啊！啧啧啧...现在等价交换的概念深得我心hhh

入了日呆包...加上前两天买的几个，夏促预算疯狂下降。

被沈脖子教育：「多看点以前那种书，哪怕攥在手里也安心的多，反正我是这样」
倒是说了句了不得的话啊。
这就是心境之差啊。我只能靠强行入魔来压制摆脱自己的那些欲望。怠惰的啊，贪玩的啊，占有的啊...也许每天向沈哥发各种各样奇怪的新闻传说魔幻毒性的东西就是因为羡慕吧。哈哈。

....忽然发现cf可以看别人的代码，就去看了看。。然后感觉很累就上床睡觉了2333一时都忘记了自己还在写日记。(6.8

最近倒也没什么新鲜事，每天还是在怠惰的边缘游移。可能一旦进入了那种地域就很难克制吧，最近一直会犯困，会犯懒。明明到了复习的时候却听不进课不想复习啥都不想干。有的时候还会想到是不是我的脚因为养伤吸收了我的精力？2333还是很佩服那些dalao天天修仙到2点多，还能6点起床，每天4小时睡眠生龙活虎，学起来简直不是人。最近又拾起了老毛病，看小说。虽然自己勉强能压制住，但是因为脚伤路上没有小黄车的时候走的奇慢，不由就会看然后就会起瘾...
woc怎么觉得最近婆婆妈妈的，还是一直就这样啊...
只学acm总觉得偏专一隅，不能接触那些东西不是太甘心。可是acm自己又菜的抠脚还进步很慢2333大概只能看暑假了吧。

这一阵没事就跟小染聊天，发现很是有趣。还能了解到棱镜的相对的面的各种故事。
比如女生之间的明争暗斗啊（事后问了下老杨更是被这些奇奇怪怪的关系什么的彻底折服，女生真是可怕的生物）不去搞别人就会被别人搞啊，什么朋友分好多种啊，什么活得好累啊，balabala

然后后来想写啥就记不得了...(6.13





.....




中间这么多天都没写hhh，我的懒惰还有我对自己的容忍已经达到了一个新的高度。
今天去了南京博物院，说实话，感觉不错但并不惊艳。我一如年幼之时那般，只对春秋之前的那些东西感兴趣。再向后的话可能就是唐宋的那些玩玩意意了。然而这边古代是楚国，东西没有想象中那么丰富，而之后的整个重心也是明清。啧，不太对胃口吧。我当然会不由自主的拿山东省博来对比，相较而言，我觉得山东省博显得比较简单。而且可能是因为位置的关系，山东省博的人更少，味道更妙一些。当然我不是说人多了不好，但是...当然更不能否认的是我有某些维护的心理在作祟。
不过比较有意思的是里面有民国馆，有数字馆。民国馆仿了些建筑，仿了些配置，仿了些气氛。能让商业和古风两相结合却不至于招人反感，挺有意思。
数字馆嘛...我本人是持反对意见的，可能与我一贯的保守风格有关。我觉得博物馆博物馆嘛，就是要有那种庄严肃穆的气氛，就是要有那种余味绕梁的感觉，追思历史感受过去，你搞个数字形节目，（大致有那么几个节目：电影，流动投影，小游戏，没了）把气氛破坏殆尽，而且从头到尾一个实物都没有，显得很空虚。不过偏偏有不少人挺吃这一套，也许我老了？又或是我太年轻，抵制这种大势？我总是会不爽，当看到博物馆的展台前面放一台电脑里面放着具体资料，亦或是有个投影来介绍，对，就是不爽。但是好像为了让人们，让越来越年轻的人们，让对这些东西越来越熟悉而对博物馆内的东西越发疏远又不去看书的我们去了解，这好像就是一种大势。洪水猛兽啊。
我也可能是有对电脑这些东西有点抵触，但是因为啥呢（挠头）。
几天不写日记，我已经话都说不利索了。
刚到博物馆的时候我的心情是万分欣喜的，癫狂到想每天提着电脑来这地方来。但是现在却兴致缺缺（不过明天可能就继续兴奋了）。刚进去玩的时候还想着再听一遍那些邪乎乎的茅山道士呢哈哈，遂想起那段在博物馆做志愿者的时光，虽然时间很短，但却像一根绳，不经意间把许多的东西全部绑着串联通电了起来。是挺有趣的。

我也说不清楚，我为啥会喜欢西北的那种风格多些。
就像我今天骑着自行车在市里转了两个小时，漫无目的（其实挺有目的的，但是那个目的根本就不是目的）。
不过体力下降好厉害啊，逛了逛博物馆，骑了骑车就感觉好累现在眼睛都要睁不开。


看了一眼gtd感觉心里一凉。24天了，完成次数才10次上下，更别提那个py了。
真的是心里一凉。

最近手机的状况越来越不好了。它今天下午几乎就没怎么好过，我觉得自己可能以后就不怎么能玩手机了不然迟早让这个玩意气死。

沈脖子最近挺安生的，我最近也没啥状态，都不骚扰他，变成他主动骚扰我了。

哦对了，前两天跟老杨谈过理想的问题，还谈过西扎（讲道理这种东西，已经变得有距离感了，如此不真实），不过我累了，这东西迟早还要说起的hhh。
老杨真是闲云野鹤啊。不。应该说老杨真老杨啊。

Entered on [2017-06-07 Wed 22:32]  
Ended on [2017-06-13 Tue 22:57]
*** 2017-06-17 Saturday
**** 哈哈哈 史诗级灾难片！
全苑停电！
连着几栋楼都停电了。
实属壮观。
当是时只听啵的一声轻轻的爆破音，紧接着昏天暗地，进入无光之界。
众男生皆走出宿舍站在阳台上以手机照明相互惊叫，抱怨声，大骂声，起哄声此起彼伏。这可能是为数不多的热闹情形。虽然持续时间不长人们便纷纷走回宿舍，把玩手机或是继续打电脑，但也有些人决定去吃串，决定出门走走，决定去听听歌。未尝不是一件好事。当然，对于那些热衷于学习但同学来说这就比较难受了。
来电的时候免不了一阵欢呼。

这么一折腾我倒是清醒了一点。
不过还是不想学习2333。
六神无主啊近来。
啧啧啧。
我也不知道为什么。
我可能需要一些...放空？
祝我早日从此障中脱身。


Entered on [2017-06-17 Sat 20:21]  
Ended on [2017-06-17 Sat 20:34]
*** 2017-06-24 Saturday
**** 在白昼「降临」之前，在失去意识以前
我赶紧来写日记。
机会难得。难得要干活，趁着夜深人静打扫厕所。
近来，恩，一如既往的，丧志。
我好像还像旧时一样，临近考试表面镇定自若，其实紧张的不行（以前还会自满的与人吹逼：考试嘛，考成什么样算什么样；或是佯装心不在焉不去复习一副事不关己成竹在胸的样子），不停的搓手（好像从高一开始就养成了这个已经内化了的习惯，最初可能是因为整个手因为紧张而出汗抓不住钢笔所以用卫生纸握住后搓去手上那种干涩的感觉）直至泥下。有时候我忽然意识到自己在搓手，便知道自己是在紧张，非常紧张。
这两天疯狂玩电脑，状若高中。而且疯狂搓手。

看圣杰大佬虽然不搞计软，却找简单算法题打发消遣时光，不知道比我这种一紧张就只知道玩手机打游戏的弱鸡高到哪里去了。

昨日与沈哥肠聊。沈哥以为：社会会「软」下去（一种只可意会的状态）。并认为会「阶级固化」（圈子集合在交并中缩小）。
他说了很多，但可能我造化不够，一时却只有一种，愚民和环境如蚁群和酸，把支撑一个宫殿的石柱磨蚀，直至支离破碎大厦崩塌的观感。
我则觉得人是一直不乏蠢的，也不会少有精英，社会软不软不提，但是有些东西变得太快。比如我弟弟现在即抱着手机不放，小朋友们打着王者长起与沈哥「再不济」看金庸古龙的巨大反差；再比如新闻从报纸到电视到自媒体，信息的传播与增殖到了一定的地步，时时都活在魔幻里；再再比如我小时候觉得智能无法涉及的围棋已经全面告负，谷歌宣称步入人工智能时代......我有时候就会觉得奇点爆炸理论并不只是像一出闹剧或科幻（因为一些原因，很多的界限都驳淆了，魔幻，科幻，现实，新闻，演绎，小说，市井驳杂的糕点...当然我还想加入更多，眼泪啊，音乐啊，建筑啊，天空啊...罗砌的代码...）

还聊了些什么自媒体啊，未来的谵妄啊，空洞的利己主义啊，科技大势下的时代啊balabala，最后两人嗦不粗话，非常难受，最后得出权且观察，观察观察观察的结论，然后一起做肉身翻墙的春秋大梦。

618随着自己的癫狂状态不可抑制的剁了手，买了两箱牛奶，一堆书，以及游戏。然后现在又到了夏促。

哎呀呀，你看我的记性......我最初想写这日记是因为...我今天早上做了个奇怪的梦，可惜场景是架构的，情节虽然甚是合理但是亦为虚构，只有跟平时一样的人物代入是现实存在的。
我为什么起床之后还如此印象深刻呢...大概是每一次这样的梦我都会印象颇深吧...
莫名其妙的饭局，莫名其妙的乘车，莫名其妙的...
算了我还是不写出来了吧。强行破坏梦境和意境有违大道。



Entered on [2017-06-24 Sat 01:31]  
Ended on [2017-06-24 Sat 02:53]
** 2017-07 July
*** 2017-07-02 Sunday
**** 时隔多时回滚日记！
也不知道能写多久，我其实挺困了。
主要是心情比预想中要好一些，睡意也就愈发强烈起来。

这两天考试，每天也就晚上玩一玩游戏，其余时间除了复习就是玩手机。
考试的心情一览无余，想凭借打游戏放松心情，却是越打越烦躁，尤其是破坦克。跟小染一起打城堡破坏者还是蛮开心的233。有几天打坦克挺开心的，然而这两天，不，今天，登陆卡，进图卡，ppt，死机，内存不足，各种情况全都出来了。然后能好好打的局里有一部分被队友卖，有一部分被弱智队友打蠢，有一部分因为进图晚血崩。我可以不在乎胜率，不在乎均伤，不在乎效率，但是能不能让我开心开心？能不能让我好好的玩一玩？心态炸裂，气到暴毙。
也是因为考试吧，最近疯狂的玩手游。可谓「爆肝」。不过过了这一阵，我可能就又要咸鱼了吧。

已然无心听沈哥高谈阔论，有时来了一点精神想怼他一下却势未至气先失。




小如意考完了，坚定的学医，我很是佩服。只是不知有此志是好是坏。我相信小如意是有想法的，但是我不由得不担心......
是什么呢。



最近睡觉有做过美梦，绝对是美梦，然而醒来只剩下空空荡荡的丢东西的感觉，慌忙补觉却又进入了另外的梦里...再醒来...就什么都不记得了...

最近也没有再看书。倒是与我预想中的不同的真的有在复习，并非如上学期一般裸考。大概真的是怕挂科吧。分数一大半来自于复习，不，应该说复习就像注水，冲泡那杯我早上的咖啡。不复习与喝颗粒无异，当然胶囊当我没说。
当然能不挂科就算复习成功了吧！hhh

最近一直在下雨，感觉已经到了阴雨连绵的时候了。听闻南方多处有洪水，学校里学生们真切的「摸鱼」，「划水」，无地容身，甚至推迟期末到下学期，当真是很有趣。

啊，肯定，有什么落下了。有很多落下了。消失在了这一段，于我来说不存在的灰白时光里。每天机械的复习考试玩手机玩电脑，也就聊聊天有时候能点起一些小小的火光。很危险的边缘啊。

身体到底还是太疲惫了啊，不行了我上床了。

Entered on [2017-07-02 Sun 21:47]  
Ended on [2017-07-02 Sun 22:44]
*** 2017-07-07 Friday
**** 闲来无事，写写日记

最近有在学linux，但是还是一如既往的学了一会就累了。这不两天了我才刚刚安上虚拟机，倒是中途走神找了些不错的应用...

不过比如今天起床玩手机，下楼吃饭，上楼看一会教学，中午吃饭，吃完饭睡觉，起床就四点多了，再上楼看一会教学便到了现在的流水账一般的生活简直就是天堂。回到山上就感觉时间变得迂缓停滞，需要我到二楼恢复原有的时间。
晚上大概吃完饭还能去山上转转，说不定还能趁着天亮除除草。
家里鸡鸭鹅狗具备，就是有些嘈杂。比如昨天因为下雨没有带这群狗出去玩，到了半夜就疯狂的嘶叫就像坏掉的耳机一样发出连续不断令人发狂的噪音。

魂1真是让人欲罢不能啊。我好想要一台机子带的动受死啊...受苦啊，病村精污啊，跑图啊什么的确实很难受啊，但是第一次看到王城，第一次看到月光蝶，第一次看到索哥赞美太阳的时候，那种满足感突破天际啊。不过家里有一条世界大蛇还是比较蛋疼，如鲠在喉。

写了些废宅的东西啊。嘛，先这样吧。难得假期呢。小染所言倒是有些道理的啊：「不打游戏的假期还叫什么假期」

有点想看动漫。

啊，还有想写的，算了回头再说咯，下楼吃饭了。

Entered on [2017-07-07 Fri 18:21]  
Ended on [2017-07-07 Fri 19:19]
*** 2017-07-08 Saturday
**** 昨天晚上又石乐志啊

坦克这个东西真是太可怕了。倒也不是说会上瘾，就是上头。上了头什么也拦不住，上了头什么都在跟你作对。
进拉斯维利对面所有人都去智障山谷；每次残局断腿吃肉的时候装弹都差一点，或者刚打完一轮伸缩队友弹夹车疾驰而来把肉抢走；火炮只认我一个一般狂轰滥炸；常常遇到蛮不讲理的四重无脑碾压，队友还偏偏智商下线该黑的不黑，唯一一个想黑的还是战列舰伸缩被四重入魂也是醉了。
打着打着就到了深夜，尤愤懑不爽。

Entered on [2017-07-08 Sat 11:42]  
Ended on [2017-07-08 Sat 11:49]
*** 2017-07-09 Sunday
**** 啊

Entered on [2017-07-09 Sun 22:33]  
Ended on
**** 还算悠闲
啊，果然还是想玩的欲望大于想学的欲望。

我收回那句「还算悠闲」的话。
来我来流水账一下今天都做了些啥：早上起来，看了半个小时电脑，陪可可玩了一个小时。看半小时电脑，吃饭。12:00。看一小时电脑电脑。然后玩了一小时手机，然后看两小时电脑。看电脑。陪刚刚起床的可可的玩半小时。看两个半小时电脑。吃饭。上山除草一小时。回来看半小时电脑，洗澡，看电脑到现在。[2017-07-10 Mon 22:05]
中途陪可可玩，上大号，被可可的动画片吸引注意亦用去了许多时间。
如此充实的一天。

我来分割一下「玩电脑」。我本来是看hexo更了想记下这学期做过的一些东西，正好昨天比赛看到一个快速幂的题，当时直接套了板子，耿耿于怀到今天。遂做快速幂专题。
然后记我当时做的那道「组合数求模」。那个题的解法需要用lucas定理。lucas就要用到逆元。求逆元就要用到扩展欧几里得定理还有两种方法我还没开始看。扩展欧几里得...然后今天看了一天怎么扩展欧几里得求同余方程和不定方程的题。都快忘了初衷是什么了2333。
明天大概就能写完扩欧相关啦。orz我本意是赶紧写完这篇快速幂然后去学某个进制换算的。啊，学完了能填一篇，再莽一下关于并查集的。然后dfsbfs....TAT考试前好像就有一道bfs没做出来。。。。啊一直挂在心上呢。
当然中途去把昨天那个爆炸的oj题交了交，还错了两道（有一道蜜汁tle，是for里放strlen....我黑人问号懵逼，回头看一下for的结构好了。。另一道优化了一下结构。。你说一共交了4道，1道签到，1道模版快速幂，剩下俩还都错了我tm社保）

昨天差点爆炸。本来说10点-11点开热身赛，我tm以为比一小时就完事了。结果真的是「热身赛」，后面还有一个5个小时的正式比赛，我tm社保！熬着午觉不睡，前天喝的酒精做了几道就心态爆炸了。玩手游去吧...手机开始和我作对疯狂自点。简直火大的要死。好在昨天竟真的误打误撞恢复了hexo，也不算没有收获吧。

啊。感觉成了我一个人在这里叨叨叨叨的发泄了。
有的时候会想起来，啊，这个地方是不是用一个比喻比较好呢。然而发泄的时候一般是想不到的，恩，就是一般我都是想不到的2333。

好了吐完槽了，这两天再努努力，更更hexo，linux也别落下，累了看看视频也不错。
oo去了厦门，找了住的地方便摸进了网吧。沈哥去了天津，找了住的地方便摸进了网吧。啊。真是羡慕呢。
之后他们来的时候一定要让他们干活割草锄地哼哼哼。

奶奶包的水饺一如既往的大，馄饨一样一如既往的好吃。
母亲功力也是越发深厚，竟已能做出老婆饼，老面包，甚至中式汉堡之类的面包蛋糕。可惜我不能以一鉴赏人之心情全身心的投入到这些糕点之中，如冒险家一般好奇的探寻...

忽然想起中午吃饭奶奶所言：这就是代沟啊，你们后面的一代没有对食物的敬意与感觉，没有对食物的珍重，没有饿过。（我记得在什么深层结构中提到了中国人的饥饿，「食」，大概已经是早就内化了吧）

哦，我忽然想起来我跟老杨是一个小学的事。
等到大一将要毕业了才知道的事。
老杨还打过魏宏鑫。我听到的时候是停止思考的。啊，哪怕现在也是停止思考的。（啊，魏宏鑫被老杨打到完胜是什么样的事情呢...啧啧啧）
啊，造化还真是弄人不倦啊。我小学都在干什么啊...

算了算了，睡觉睡觉。
大概还能再玩一会手机恩。
啊，写日记的时候玩了会电脑，看了会闲物hhh。
太阳好热！我要去冷冽谷凉快凉快！啊。我没有魂3。

Entered on [2017-07-09 Sun 22:34]  
Ended on [2017-07-10 Mon 23:18]
*** 2017-07-13 Thursday
**** 我靠...
写个快速幂写了这么久。。而且。。没写完。。。。还有欧拉要记。。明天看能不能把欧拉搞出来顺便把这些题日了。
天啊。。计划被无限制后延。。。
今天挺蠢，几道题起初都没有直接的看懂题意。最后还爆了道精......睡了睡了。

Entered on [2017-07-13 Thu 00:57]  
Ended on [2017-07-13 Thu 00:58]
*** 2017-07-20 Thursday
**** 今日所闻
教练先是一番嘴炮（我已经不知道怎么形容了...陈志老师就是能说，不过也不是令人厌倦道那种，就是跟小米亲一样的那样...talker！
「
别人只是辅助。
要多失败。
要找到乐趣。
没有天花板。
感谢南邮。
」

周围一屋子的dalao，深是感到压力和兴奋。

第一天凭借模版（模版题不让代模版是疯了吗！）和一点暑假和昨天熬夜的学kmp的成果熬了下来。
明天的就要都不会了。高斯消元。fft。莫比乌斯反演。
离散对数。划分树。主席树。区间最值查询。好的都很棒。都很大。都不会。
嗑药学习去了。
啊不对，嗑泽野。

改天聊聊新的环境，这两个新的临时舍友。hhhhhhh。

Entered on [2017-07-20 Thu 10:33]  
Ended on [2017-07-20 Thu 21:41]
*** 2017-07-21 Friday
**** 好绝望啊！
我觉得我尽力了啊，还是看不懂啊！莫比乌斯反演什么的...晚上再看吧= =
babystepgiantstep也是只会模版啊，理解不是太能（毕竟hash都不会啊。。）
fft直接就炸了啊= =....唔托沈哥的福我能看进去一点了。。。今天可以不做题光看hhh

Entered on [2017-07-21 Fri 09:14]
Ended on [2017-07-21 Fri 11:08]
**** 恩我还活着！
活的好好的hhh
主要是各种偷懒。。你看我甚至下午还趁着吃饭「偷偷」玩了会电脑（然而悲哀的是我是在电脑上玩手游QAQ，手机已经热的...95%以上的时间是无法操作的，就一个移动热点的作用2333）
然后今天的题果然一个不会，不用板子就直接懵逼，暴力都不会暴。哦对，这就看出我的弱项：强变通和智商。比如我看到这个题的数据范围，就放弃了尝试（万一数据水呢！万一可以优化呢！）比如我看到一个题，一眼就看出，恩，没有思路，就直接放弃了；或者一眼就看出，哦，fft优化，哦，线段树，不会，就不管了...然后居然有dalao同学邪法过，或者各种令人窒息的操作优化过...
简直了。我下午就在整理板子...写日志一样...

哦。大概就是明白了一件事吧。智商不够。也没有狂热到压倒过自身的价值判断体系。经常会上知乎看一些「打铁了怎么办」「acm到底有什么意义」「为什么不要把时间花太多在acm上」之类的问题。毕竟每每看到别人一身旧知经验等级上完全碾压，或者看那些高中dalao的博客花式被虐，心理总会有那么一些不平衡。加上自己进步缓慢，常常觉得停滞不前而前路漫漫，便会有心灰意冷之感。
等明天看省赛题目吧...不，等这个暑假过去吧...这些问题的答案可能就在这个暑假里了...按这种压榨的方法下去，绝对会是质的飞跃...无论是技术上还是在专注力、意志力、学习能力之类的东西都绝对是...改革...
好吧这就是我对集训的认识吧hhh昨天特别累，今天好多了（也可能是因为今天没怎么做题，然后昨天还欠了一屁股账，堆砌过多之后反而不在乎了）

好了也就写那么多了。高斯消元的板子完全看不进去了。直接用板子做题去体会了...

哦对了，南京这个时候真是热啊。确实比济南要潮一些，可以感觉到的就像被一团热云包裹，根本不是正午在山上太阳高悬的刺热质感。

再多抱怨一会吧。这样啰嗦啰嗦还是挺开心的。

看到各种同学啊，老乡啊，网友啊都在玩啊，失衡感非要说的话肯定是有，不过并不强烈，根本不如赶紧补题和赶紧预习的想法来的强烈好吗...（根本不如对人生对怀疑来的强烈好吗！什么莫比乌斯加速，fft加速，自动机，全tm黑科技好吗！说起这个，n^2怎么了！n^2招你惹你了！把n^2加速成n^1.5（五边形！），加速成n+m(kmp!)，加速成nlogn(fft！)丧心病狂好吗！n^2累了！...
tm黑科技学到麻木。
各种线性，线性，线性。

（只是一个弱鸡忽然接触到了新大陆感觉简直太可怕了。
瑟瑟发抖。

Entered on [2017-07-21 Fri 23:17]  
Ended on [2017-07-22 Sat 00:19]
*** 2017-07-23 Sunday
**** 今天些许小累。
感觉这样吃一顿坐5h吃一顿坐5h的生活迟早长胖。

下午6点多小憩一觉，差点没醒过来...晚上又去活动室学了一会，好歹算是了解了dij的大概。

另，今天效率略低。
做题状态也不是很好，居然为了特判想了3h....自己疯狂怀疑自己2333，还有玄学题目（其实是概率题，一般称之为玄学，因为实在不明白怎么就是那么算的）本来还能a一道题的，然而思维僵化，满脑子Lucas，一点也不想暴力枚举n!....

晚上效率近乎为0吧...不是很懂。看了会fft，然后发现看不懂。
又欠了一屁股债。得，还不完了。

今天上午修空调的来了。然而并没有什么用。据说是因为太热了，空调也受不了。现在冷气下沉热气上浮....非常尴尬。

可能是今天因为比赛没做出题来的原因比较焦虑吧...省赛只有三题水平（真实会的只有3题，然而只做出2题..）继续努力= =先把有意思的日完，图论啊，sg啊，还有自动机什么的黑科技...
凸包...fft...高斯消元...先放一放吧...

补日志去了..今天欠的有点多..

Entered on [2017-07-23 Sun 00:07]  
Ended on [2017-07-23 Sun 00:23]
*** 2017-07-24 Monday
**** 睡了睡了
这两天状态不算好。比起第一天的劲头（效率）差远了。
刚水了两道题。。太久不做水题看见个题就如临大敌，末了本来可以秒的。。

最近图论啥的一点不会，要慢慢补了。
今天总结了下sg函数，会写了kruskal（模版），说起来收获挺少的....
明天继续加油吧。争取多搞一些东西。
赶紧睡了明天早起看个强连通，然后把dij的优化学完，然后去那边学spfa和二分图啥的。恩...把昨天的题尽量的补两道吧。
累了就回去补第一天的素数打表题2333333

哦今天是卡模版题来着，kruskal有个tol = 0老是忘，还有一个恶心输入的题卡了好久。当时急的要命，上网搜到的都是「模版」「简单」「基础」之类的字眼无情的嘲讽着我，然而我就是a不过，拼命与题解找不同...最后改了输入格式...不说了= =

是效率有点低哈。这样下去迟早药丸，赶紧睡觉睡觉睡觉。

Entered on [2017-07-24 Mon 01:35]  
Ended on [2017-07-24 Mon 01:43]
*** 2017-07-25 Tuesday
**** 今天再怠惰一波！
多校第一次。
组队感觉还不错。
不过队友全tm会高精啊，有点姜。
稍微难一点的题就不会了。啧。离着别人差得远，不如先做专题训练。

大姜无边。

主要是补不完的绝望感。学最大流去了。现在就是快马加鞭，还不到，还远不到离开模版的地步，甚至大部分时候是靠模版理解整个算法。
不过打模版也是挺开心233.
这几天的做的题可能已经碾压了上个学期的题了吧。我的天我上个学期都在干些什么。

这两天都是下午回来之后先睡一觉呢。果然空坐5h还是很累的，对身体伤的挺厉害。还有boss说的那个14h编程hhh，我选择保重身体。
然而我虽然是这样说的，我还是很矛盾。。因为差距不是那么容易弥补啊。

Entered on [2017-07-25 Tue 23:55]  
Ended on [2017-07-26 Wed 00:05]
*** 2017-07-26 Wednesday
**** 今天怠惰的具体表现！
只做了大概7题！
愚蠢的没有学新知识！
玩了会网易云！（辣鸡网易云今天推荐的音乐跟昨天的一模一样）
玩了会崩坏！
逛了会steamcn！
看了会漫画！

不过今天收获大概是。。不要依赖模版。不要依赖模板。自己写。

Entered on [2017-07-26 Wed 01:03]  
Ended on [2017-07-26 Wed 01:05]
**** 难受
一大早起来头疼的要命，恨不得再回去睡一觉，然而已经太热了...
我靠这个头疼法怎么做题。。。
昨天晚上风扇开的档位太大被吹了？
啧，难受

Entered on [2017-07-26 Wed 10:02]  
Ended on [2017-07-26 Wed 10:07]
*** 2017-07-31 Monday
**** 怠惰ing
Day10的题解崩掉了，伤心，辣鸡typora
身体不行了啊......身体崩掉了。
今天一天处于身体疲乏，夹杂着饥饿和肚子痛的状态之中。
本来不至于这么不堪的= =都怪自己这两天玩的太猛，有种脱缰之感。
进入天天水题的模式。。。
要学莫队...线段（主席？）树...区间的题越来越多了...
不过先顾及身体吧...今天水个cf的题就算了......今天坐的这5h真心难受。
行吧....我还是慢慢来吧，贪快还是有些太吃力了。（进一步证明了智商之不足..）

Entered on [2017-07-31 Mon 16:32]  
Ended on [2017-07-31 Mon 16:55]
** 2017-08 August
*** 2017-08-05 Saturday
**** 休息啦
我还是挺有意思的。我觉得如果一群人聚在一起打比赛刷题什么的确实开开心心乐趣满满，现在集训的话就颇有一种被强迫的意味让我非常难受。这种压迫反弹是我最惯用的手法了，从小到大一直在这样...但是不集训哪里来的强度呢...（其实是老板在的时候比较压抑心里压力就大起来了，老板不在还是挺好的2333

Entered on [2017-08-05 Sat 19:41]  
Ended on [2017-08-05 Sat 23:16]
*** 2017-08-08 Tuesday
**** 恩这两天没怎么学...
每天沉迷肝wf和看ti，自己果然还是更贪玩一些。
虽然每天日常都在打着训练，但是比起刚开始那一阵差太多了啊...大概就是5h与10h的区别...不过10h的我也快坏掉了...

今天终于下雨了，南京难得的迎来了能够在室外活动的温度。雨后的冷风棒极了。

Entered on [2017-08-08 Tue 15:35]  
Ended on [2017-08-09 Wed 11:35]
*** 2017-08-09 Wednesday
**** 姜啊
又不会了...
回去打打游戏等着看ti了，掀桌。
ti还是比较让人开心的，比起自己的蒟蒻和懒惰。
咸鱼终归是咸鱼，我觉得这集训最大的收获是找到了一条脱咸的道路，然而因为路途过于遥远让人痛不欲生...
更有甚者就是题解都看不懂咯。

总想看的更高更远结果跌倒在台阶上，总拿着自己的弱当作盾牌掩盖着不想努力不想前进...理由是要多少有多少，什么疲惫劳累，什么差的太远，什么学的太多，什么压力太大(但是没用。跟以前一样，只是意识到了，并且呻吟着，但无动于衷。没用，该偷懒还是偷懒，该摸鱼还是摸鱼，这十天来做的题恐不及开始那十天的一半。)
我会看到要学的有......列出一个大单子，然后挠一挠头，寻思着实在太多，便不再去接触。我会像一个烦躁的鼓风机不停的呼出自己的怨愤消耗着电力却

只能做到多校联合里的「easy」的程度...(个别easy题还要靠队友)「medium-easy」都不能做...(卷积+压位，进制转化找规律类康托排列)真的姜啊...

今天连二幂拆分的递归形式和01背包的装满都不会...二幂拆分就跟快速幂差不多的东西...然而想不到递推式则无从谈起...
愚啊

Entered on [2017-08-09 Wed 15:52]  
Ended on [2017-08-09 Wed 16:30]
**** 
哦我的贪心是思路有问题...果然是可以直接莽的...
-17：15另外老板话是真的多，说了很多的话没有任何实际的东西...然后话还刺的很 啧啧啧。

Entered on [2017-08-09 Wed 16:39]  
Ended on [2017-08-09 Wed 16:40]
*** 2017-08-11 Friday
**** 。。。
队伍训练就要做world final。。。
就是说跟高考一样，要多刷真题嘛23333
但是我觉得我应该先补专题知识点啊...我这就跟没上过课没看过课本就去考试一样啊。

Entered on [2017-08-11 Fri 16:54]  
Ended on [2017-08-11 Fri 16:56]
** 2017-09 September
*** 2017-09-10 Sunday
**** 恩...被人催了QAQ

嘛。。一直就在玩就是了。
口口声声暑假没过够，其实只是想玩而已。

网络赛上才觉出自己菜。可是一点都不想去动呢。
看看双周的时间吧。看上去双周的课比起单周要少不少。
不过acm菜啊，别的也完全跟不上同学了啊。啧。

哎不过还是惰性大发，脑子里只有玩乐。两个月没写能够感受出来连文字都有些许的陌生了。

或许比起上学期，这学期吃的比上学期开了，不那么拘束了。

看着大一军训总会有一种宛若昨日的错觉。谁又曾想如此快的就是一年呢。快到我甚至无从抓住可可成长的点滴——太快了，真的是，太快了。

嘛...这周先这么放着吧。倒是惬意的很，玩乐享受。不过每周有硬性的3场比赛摆在那。想过于放松也是不得的。下周起就要开始工作啦。
那就这样吧，下周见啦（或者我啥时候又心潮澎湃来写233）

Entered on [2017-09-10 Sun 16:44]  
Ended on [2017-09-12 Tue 15:27]
*** 2017-09-23 Saturday
**** 写着写着都要变成周记了啊。
单周是有点忙的，不过也还好。

...每天写写作业，看看垃圾网文，肝一会游戏，差不多就过去了。
周一一心一意玩游戏，周二继续写了一点kmp，周三下午睡了一觉然后晚上做水题做的非常开心，找到了一同做题的乐趣（怕是只有水题才能找到这种乐趣），周四上完体育一身疲惫，记清晚上干了啥。周五也是一心一意玩游戏...
啊，上周说这周开始学习，结果还是没有做到hhh。

这周唯一值得一说的就是找回了听音乐的习惯...
每周还有一个盼头，就是等R&M的更新。R&M是真的好看。爆炸性细节，每天当听力听了一遍又一遍。

现场赛打到现在，也几乎无欲无求了，就摸摸鱼，水水赛，心里的难受也没有原先那么强烈了。想想欠下的债也似乎越发的多了，多到不想去承受，甚至不想去思考...

...老板开始讲话了，emmm。老板总是会在一些废话里掺杂一些稍有趣的东西。或者说老板把稍有趣的东西变成一坨废话_(:з」∠啥啥啥，个人pk赛？要死了要死了


-----到第二天的分割线------

哇划水了诶。虽然一直在努力的想但是。嘛，最后还是抱紧大腿。
有点难受呀。
不过终于是过了低保了，可以出去啦。
好像是广西....恩，小期待。

-----不知道第几天了的分割线-----

哎，双周就是舒服，美滋滋的睡一大个午觉，打游戏，吃饭，写写作业，日子颇为清闲。
补点东西，晚上等着看R&M了。

Entered on [2017-09-23 Sat 16:56]  
Ended on [2017-09-26 Tue 20:38]
** 2017-10 October
*** 2017-10-08 Sunday
**** emmm，这个十一

和学习无缘啦。
oo和周神来玩了三天，我除了请他们吃吃饭别的什么也做不到...emmm，甚至要他们带我游南京。
oo中秋那天居然带了个妹子过来，虽然我和周神有着无尽的怀疑与遐想但不好当面问。事后提及oo只是否认...我和周神去玩了玩中山陵啥的，下午会面之前一直是他们两个在逛街-.-不过说起来，妹子还是挺好的。

我和周神的意见还是很是相仿的，这几个陵园并没有想象中的精彩。若得清闲无人之时说不定能够领略一些东西，十一嘛...而且没有儿时那种去陵园的兴奋与狂想了，想来一是为时间蹂躏又不再看书，一是被人群以及一旁的周神冲淡了吧。

第一天的中间发生了一点小插曲。让我和周神心惊胆战，让oo心旷神怡的小插曲。。oo的蜜汁失踪。
是时我们三个骑着黄车往新街口赶，冒着细雨，过着马路。周神对于按喇叭的行为极为不满，然而一路上不停的有人冲着他按喇叭...我正准备跟oo说周神忍无可忍寻到目标要报复了，却发现oo不见了。
oo手机无电，身无分文，就这样凭空消失在我们周围。
我和周神往复寻找无果，恐惧、担忧、不安悄然燃起。于是我们开始遐想猜测。
对于我来说第一个念头就是oo出事了。但是我们回到oo之前还存在还说笑的路口，并无血溅之场景。查了查我的手机，oo的黄车并没有锁。（他手机没电了我开的黄车..)
oo在偌大的南京城中迷失，不得不求助于交警同志，周神臆想，“我是一游客，我手机没电，身无分文，我和同学走散了，能送我去警察局吗？”
一个大活人怎么会没了呢？
我和周神互相安慰着，oo的求生欲望应该足够，他应付的来。心里却是一阵一阵的抽搐。
他如果没出什么事的话，会不会借电话？记不记得我们的电话号码？按照那个路口所示，他会不会没看到我们直行，便右转了？应该不会啊？又或是折回毅然往赴我们骑到黄车的地方？
周神问我：一个人忽然和其他人失去联系并且处于一陌生环境时会怎么做？
我说我会呆在原地。周神摇头。那不是oo。
在我们终于放弃了寻找挣扎，准备两人先行吃饭，见招拆招时，忽然发现oo在qq联系了我们要我们在大排档见他，并且给我打了个电话。
？？？
回电话时已是对方不方便接通电话，然而qq却是“4g在线”。
难道说oo骑着黄车在路上哼着歌，忽然路边一人一把把oo从车上撸下来，劫持了他并向我们传达了什么信号？

当然最后在大排档找到了安然无恙的oo，长舒一口气，去听oo的故事。

oo居然在那个路口神游天外，晃过神时直行的红灯已经亮起，剩下一个左转的绿灯闪闪。oo发现我们不见了，便果断的左转...然后凭借着自身对于cbd的感知与阴差阳错不知是幸运max还是探路max的能力，寻着印象中不多的几条路（然而是错误的印象...）正确的来到了新街口，但是新街口大，他无能找到一个具体的地点。于是他来到了我们之前吃过饭的一个广场，而且非常谨慎，绕了广场辨识了好几圈，因为身下的黄车是无钱无电的他唯一能凭借的交通工具了。然后...他遇到了一个推销的，就是那种，太常见的，到处都是的，推销擦鞋的自称大学生的推销员。
两人的对话极为诡异，oo渴望知道位置，知道更多信息，迎着推销员就去，（正愁无人可找？）主动攀谈。推销员则对于此人的热情非常诧异。
可是总有那么些意料之中情理之外典型在现实中发生着，按oo的话来说，现实永远比电影中的套路来的更深，更混乱，更多变数，或者更不套路。oo已经处在一种，几乎随时都能将身边之事之后的情节铺展下去，套路的不套路的，亦或是想起某部经典的电影，与这件事有种种共通之处的模式中。（压抑不住的）
推销员：希望你给贫困的孩子一点资助。
oo：哎呀，我现在没有现金，手机也没电了。
推销员（微微一笑）：不用担心，我有充电宝，你要不要先冲一点电？
于是两人疯狂的聊天，oo趁机充电。我们都以为推销员为了应付oo这种说辞的人而真的准备了充电宝，不想会真的有这种人...
于是oo用30元买到了5%的手机电量、一瓶诡异的去污剂，并获取了大排档的具体位置。

令人窒息的操作。




最近沉迷睡觉，非常难受。中午动辄两小时且起来后一副昏迷的状态，我怀疑跟我最近的不良状态有关系，上课，睡觉，打游戏，玩手机，几乎是我最担心的模式了吧。
你看光这么一篇日记都拖拖拖...
我感觉比较美好的状态是做题+看番。
23333。最好的是做题+看书，但那是不存在的。

另外我最近感觉很多我的行为模式是...源自于...自卑？
再行观察与思考吧，累了，写许久不曾动过的题去了。


Entered on [2017-10-08 Sun 09:56]  
Ended on [2017-10-11 Wed 10:52]
*** 2017-10-24 Tuesday
**** 周记变月记
月记啊。

上周充实且忙碌，周一监考大二入队，周二面试大一入队，周三训练，周四周五好歹得空疯狂玩游戏，每晚睡眠可能都不会超过6、7个小时，全靠中午补觉。
面试大一之前我甚至比他们还要紧张。当然面试起来就好多了，毕竟被试之人不是我。

这周的话，前两日都去做了几道题。主要是寄予厚望的2队9队（可能就是实力上的第二第三）都打了铁，一时之间上下都有些焦虑与心急，连我们这种本意即打铁的队伍也不得不重视起来，开始三天打鱼两天晒网的训练。


近来颇爱看也许是上学期网络文学课的唯一收获--雪中悍刀行。与以前看网络小说的消遣与为了获取奇异快感不同，看这个竟是很是享受。

想了想也许是最近充实的很，竟是没什么好记的。
写写做题的话，大概就是自己做水题的功力又上了一两分？
游戏的话，怕是感觉wf只有专精平原和垃圾可水。赤毒啥的一点都不想打。

最近南京少有的晴天，却是晴天中才感觉到秋意的凉冷，已是不能只在宿舍里穿单衣短裤。

Entered on [2017-10-24 Tue 23:23]  
Ended on [2017-10-25 Wed 11:34]
** 2017-11 November
*** 2017-11-05 Sunday
**** 月记
我不知道我每天会多少次想起写日记，但是从来没有动过。。
大体上最近除非训练，几乎都没有动mac吧。当然理由非常正当，因为以后要用windows比赛嘛，虽然我感觉写代码几乎用不到我但总还是多用windows写几道题的好。
最近由隔壁吴宇晨和并不勤奋的李承俊掀起了小小的学习风潮，竟是让宿舍多了一分游戏外的研习气氛。连我最近都颇受感染，游戏时间有了明显的下降，写代码的时间不断增加。。当然也可能是由于紧张所致。。。
不过还是觉得自己有点菜啊= =而且没有能变强的趋势。。cf的div2的c题从来做不出来...难过。

近来因为会和李承俊一起上体育打羽毛球，交流比起原来不知多了多少。总算不是四个闷骚的男儿对着自己的电脑噼啪，偶尔会有一些交流了。
不过最有趣的大概还是兴致广泛的阮海。我发现这些四川的最是有趣，比如银城。
网络有点问题，回头写啦。

Entered on [2017-11-05 Sun 16:53]  
Ended on [2017-11-08 Wed 16:00]
*** 2017-11-08 Wednesday
**** 又来啦。
最近欠了不少债=。=总之就是感觉做不完的题。
当然很大一部分原因是因为这两天用了好多好多时间写了个400行（当然去掉调试也就200余行了hhh）的离散数学上机实验作业。隔壁吴宇晨兴致勃勃的搞起各种研究，然后狂躁的来呼号：我这个地方不懂，去查这个地方，发现他用另一个我不懂的名词去解释这个东西，我又去查...与我当初准备科协考试的时候何其相似，应该说快速接触一个新领域与知识的时候就会这样吧。我不知道有多少人是自己写的代码，但是我感觉我周围应该只有我自己吧hhh，小小的自满一番，也算是能得到的不多的慰藉了--比起身边之人，仍还有胜之之处。

一直想着抽个时间写点题解，一直腾不出这个时间来。今天（周三）本是有这个机会的（最不济也能写个题，然而被我花在了玩Devil Daggers和pony island上。不得不说小精品玩起来的感觉就是不一样，前者是针对强迫症和恐惧的问题，后者则是meta经典或者说是爆炸作？我没在史丹利那边感觉到什么悚然或者芒刺在背的感觉，只是有感慨，undertale可能是第一个吓到我的游戏，新手教程给我满满的恶意，那朵邪笑的花让我毫无准备的被捅了一刀子。现在那种感觉又有点回来了。
你看，本来是检讨自己自控差的，写着写着成了对游戏的理解了。
还有那个销魂城，不下于pony island.exe的独立世界。我感觉我大概是不适合fps的，选了个中等的难度打的慢不说，还极为吃力，经常要靠无限复活来搞大老爹...
总之不是完全由wf组成的就不错了。wf说起来也已经真的进入养老了。有时候去就看看有没有感兴趣的裂缝啊，有没有ods啊，看看突击感不感兴趣啊，然后就随随意的下线了=。=
不过没有一个能在大量代码之余放松心情的游戏之类的，比较僵硬。感觉代码和音乐拾起来了，是不是能找点b站视频看呢。不过节制是需要的。规划嘛...
偶然间看到了清华大神的时间表，刚才竟是没来由的想起了圣杰的那份时间表，不由得感慨这些人才是优秀啊。我不求那种时间遵循，只求一点自控...
我特别容易陷入某个境地不能自拔，然后把紧住的弦一口气崩断，继而瘫软无力，三天打鱼两天晒网。有时候摸到极致摸无可摸，都想喊一句，狗才摸鱼！哈哈哈。

还有些要写的但是来不及写了。
看了两遍银翼杀手2049。一时很想逃个课去看电影。事实也确实逃了一次。第一次逃课，在上周的周一。（差点就忘了这好像还算很有纪念意义的事）
雪中。不说雪中写的好不好，不过我是情随之牵，顺带破天荒的，很是想家。
不急不急。能捡回一点就好。
惊了，看了看写了不少，看来一时半会不写废话还是照样的多。

太晚了，身体也需要些休息。奇怪的是平日我1点睡7点起，中午睡1h，前两天双周的周一周二下午无课，晚上11点睡7点起，中午仍然是不受控的一觉睡个2、3个小时。
大概是宅人变胖需多眠吧。

想放假回家啊。

Entered on [2017-11-08 Wed 23:22]  
Ended on [2017-11-09 Thu 00:55]
*** 2017-11-18 Saturday
**** 
好久没有写了hexo，所以想去补一点...最近虽然有在做题，但是大多杂而不难，没有知难而上的勇气和毅力，所以水平上升的也就颇为缓慢。
另外辣鸡next，居然不支持高亮宏定义...心急如焚的调了半个多小时最后还是一点一点排除出来的。
想到只有一周不到的比赛，就不免心生惧意。

买了个h840，感觉非常愉悦。不管怎么说还是更喜欢在宿舍活动，也不知道是否是习惯使然，哪怕宿舍里舍友打游戏的声音常常干扰到我，我也仍是不愿去教室或是活动室，尤其是活动室，如果邓导不在，在那里一点都不能安心，只有清冷。也许是屋子里人数虽少却人人稳压我一头然后自卑或强烈的胜负心所致？这回其实完全是兴之所至，认为自己写代码（打游戏）的时候还是很需要一个环境的，于是花了并不多的钱，买了个隔音效果不错音质更是不错的耳机，已是心满意足的很。

啊，4天前，过了生日。
之所以迟迟没有写其实完全是自己懒。
毕竟这两周是程序设计周（已经只剩下一周了）美好的，近乎无课的，休息周。
对于大部分同学可能是这样吧=-=我也不知道这一周怎么过来的，大概就是上午起来一直到下午写写程序，晚上打打游戏一天就他娘的没了。
前三天实现了那个奇怪的「文本编辑器」的模拟的程序设计......我就是太过吹毛求疵，其实大概的框架第一天就完成了...现在想了想其实还有不少不尽如人意的地方，只是我也没什么心思再去完善了。我感觉这个程序设计周对于那些不曾偷懒的同学是大有裨益的，代码能力，交流能力，以及这么一个简单的流程，就连我也在这个过程中有些体会（不过大多可能就是调试之烦，清点细节之累之类的抱怨）。
上午普遍比较僵硬，效率不高，周一是睡回笼睡到十点，周二是没效率，周三直接没起，周四打游戏，周五也没起...也许是每天上午的那些课里我都是的精神状态，延续到了这周的...

啊，生日。
我感觉我也是挺心性凉薄的。几乎不记别人生日，节日不为朋友们祝福，也不曾主动问候他们。在与人交往一事上从来是被动姿态，遇事先想拒绝逃避，其后再权衡利弊，算盘噼里啪啦响，结果却是...每次过生日的时候都会觉得，啊，大概是没什么人祝我生快了。然后就会惊喜的等到一份份礼物和祝福。
矫情的说起来，也可能就是一种难以言说的孤独。
周二的时候已经很「意外」收到了许多的祝福，下午就收到了大佬们的请帖，我犹豫迟疑了一下还是答应了。

于是我们去了大成。
第一次打了台球=-=分花色和单色的那种...虽然几乎是一直打不准，不过可以一直打直到打中了为止...也有「找女朋友局」里把女朋友拱手相让于我的操作。杰大爷是真的容易上头...我感觉那天小一半的时间在看杰大爷自己跟自己过不去...据如意所说，他每次都会这样...
当我看到那个生日蛋糕的时候我整个人是蒙的...细细回想不知道自己有多久没有这样正式的许愿吹蜡烛吃蛋糕而后狂欢的过生日了...大概有一些是打游戏度过，有当时让我感动不已那份大家东拼西凑出的蛋糕，更多的早早的消失在记忆深处...

啊，当下的心境是不能表述出当时的幻景的。
那就先封存在水晶里好了。


wf肝了肝活动又没啥肝的了，意兴阑珊。玩了会灰谷，音乐爆炸，剧情...，玩法还行，就是英文有点僵，有时候不知道兵种怎么用...倒是预览图做的不错。每次打这种游戏都会生出打sc2的古怪念头。

雪中看到结尾了。怎么说呢，意犹未尽吧。

线段树做的我心都要碎了。
区间合并稍微有一点瑕疵，然后就是不知道是在哪里有瑕疵...照着别人的代码一点一点的改，爆炸啊。wa到怀疑人生......这个破题我已经做了两天了。。。
就是那种窒息感，我都感觉我要被这个题逼着打两天游戏了。

发现了game of life，一开始是自己在尝试基础图形，后来加载了几个大图，只感觉非常爽，非常愉悦，却没有看出什么门道，纯粹是看热闹。

一篇日记写了3天....一拖再拖...

Entered on [2017-11-18 Sat 18:14]  
Ended on
*** 2017-11-21 Tuesday
**** 另外稍稍吐槽一下
线段树，僵。区间合并，僵。多个区间操作，僵。
更别说僵的爆表的扫描线了。这就跟kmp还没做完忽然发现后面还有扩展kmp、ac自动机后缀自动机一样令人绝望。
⬅做线段树的时候还会遇到dfs序，离散化...不要太绝望。
还得做几个概率的题...
我在想我以前都在摸些什么...

昨天晚上把那个奇怪的右界判断改了a过了题之后，酣畅淋漓，顿时有「仰天大笑出门去，呲牙咧嘴冻回来」的大感慨。

Entered on [2017-11-21 Tue 22:06]  
Ended on [2017-11-21 Tue 22:10]
*** 2017-11-22 Wednesday
**** =-=早知道...
早知道就不补题了（掀桌！）虽然啊我内心非常开心但是但是但是问题在于时间真的不够啊啊啊！怎么就要到周五了！怎么就线段树里还有扫描线，还有dfs序，还有主席树！！！
怎么字符串就还有bug至极的后缀自动机！
怎么线段树就还能延伸出树链剖分！！！

恩应该没了。大概。我一个都完不成了。
按照邓导的说法，就是我们去做的时候能够分辨：看，这个是树链剖分；看，这个是后缀自动机；看，这个是概率dp，然后我们就可以摸鱼了。
....
当下很忧郁啊。

Entered on [2017-11-22 Wed 22:53]  
Ended on [2017-11-22 Wed 22:58]
*** 2017-11-24 Friday
**** ....等我
突然说要出国了...

然后跟我疯狂的说人生不易...说好累，好累。

我想可能是提前的，把本应零零碎碎在几年后经历的痛苦压缩在一个月里体验了。

我好担心啊...

疯话不好玩，因为我会当真的啊......

但也比不说好...hhh我真是矛盾呢
可是我真的不想下次就真的再也不说了。。就一直自己。。自己那样。。连可以分享，可以吐露的地方都没有........
又真的想去关心却非常害怕适得其反..

一定要坚强啊。
一定，一定啊。

Entered on [2017-11-24 Fri 23:31]  
Ended on [2017-11-24 Fri 23:38]
*** 2017-11-25 Saturday
**** Day2
emm，今天其实没什么好记的，就是广西大学，热身赛，冷这么三件事吧。
尽量早睡吧。。回头记啦

Entered on [2017-11-25 Sat 22:44]  
Ended on [2017-11-25 Sat 22:45]
** 2017-12 December
*** 2017-12-03 Sunday
**** 周记！
周五的时候找了个cf做了做..
然后非常气的卡在b题。
觉得自己有时候思维断断续续的..然后代码也写的很丑陋，修改的时候经常出现改了还错的状况...我本来还想截图的，都于心不忍了...整整十次..水题交了整整十次，还是在cf上有数据的前提下。当然心不在焉改的不是勤快是一回事，不过代码真的丑。思路虽然和题解「差不多」但是总是感觉写出来的东西很丑。
我的感觉还是比较准的。这个「差不多」比较致命，其实是一点小地方没考虑到导致自己爆炸。（就是所有的方块其实都会被算进去，所以再遍历无意义，需要的只是判断不存在的情况就好了....只有超n和超m是不存在的，想的复杂了...）。
嘛。。感觉自己就是需要这种水题就能快速水过的能力。
继续加油吧...

周末就要好好的玩嘛！
周五时候再次被对于我来说可能是至高命题的问题困扰：是玩还是学？
虽然一般会选择玩，但是也有比较例外的情况。
问出这个问题的时候我大概就有些想玩了，但是会被想学的念头所阻挠，于是产生了这个问题。
其实就是贪心啦。
于是玩的时候就会带有负罪感，于是下一次玩的时候就会继续产生这个问题，继续负罪。
虽然母亲说天不会塌最糟糕又如何可我依旧还是放不下啊。毕竟自己比别人差那么多，起点落后那么多，又那么想玩...

最后我强行总结出「也许我这是前一阵下药过猛，需要一段时间的休息，就如同下药之前玩wf，玩wf之前是暑假训练一样的周期循环」来安慰自己。
于是就开始玩啦！
周六的cf也没打啦。
哈哈。

看了两季小英雄，感觉不错。就是图个愉悦嘛。
自从上次出去比赛的时候看了些b站的视频感觉自己突然好想补番啊。

Entered on [2017-12-03 Sun 16:07]  
Ended on [2017-12-03 Sun 17:40]
*** 2017-12-07 Thursday
**** 周记周记！
哎，早该写这篇的啦。
是比较轻松的双周，我这周却过的非常疲惫=-=每天都不想做题，不想学习....不但精神萎靡不振，天气也是变得极寒了起来。零度，零度，这两天早上出去跑操都能看到草坪上尚未消去的霜印。

周二去看了coco和至暗时刻。coco的话，不管从哪个角度看都是很好的片子，嗯，很多的角度啦。不过有一点我很在意，coco的故事并不那么惊艳（我可以这么说吧），但是到了电影院眼泪还是止不住的哗哗的流。也可能是大家的心情都比较放松吧，一个...发泄的空间？
至暗时刻...这大概算是传记片？来到人民中获取力量！说实话我二刷这个的欲望比刷coco要强...另外我终于看到了久违的2d电影了......以及...这是加里奥德曼？我回去查了下...小天狼星？你怎么变成这样的丘吉尔了？（其实我一开始还以为这个丘吉尔会戒酒的2333，另外厕所大法好）
还有...看的时候有种小错觉...这个丘吉尔身上有好多着跟希特勒相仿的气质，总是会十分走神的想起元首的愤怒...

嗯刚才兴冲冲的以为匈牙利问题就是匈牙利算法，就是ek...一下子搞混了三个玩意...难过。
没想到每行每列取单一值的和的最值竟然没有黑科技算法，是o(n3)的...我刚才去看匈牙利，o(ve)，不错。然后去看可怕的dinic，嗯？o(v^2e)？什么鬼情况？怎么没优化的比优化的好？然后就看到了o(ve^2)的ek....一瞬间以为kuangbin巨巨已经能把ek优化成ve了呢...（可能这一阵真的，脑中空洞无物）

那毫无说服力！我还能变着花样虐sc2艰难电脑呢，还能打到150的apm呢，空洞什么不存在的（
最近没心情学习就去打sc了。

有跟不同的同学交流，正常的，但是在计科系里就格格不入的好学生，wx，一心想变强却僵硬毫无自学能力的lyj。

哇，wxy大神是大学才接触ctf的？初中接触acm的？？惊了。
搞得我搞ctf的欲望猛增。
不过只要一想自己现在acm的菜和怠惰那热情就会自己熄灭了=-=

说起熄灭，这一阵是真的冷，冷得要死要死。
惨了词穷=-=还没怎么用词就穷了，这阵也确实没看书。嗯不是这阵，是这几个月。
大概比赛前老杨给过我一段小说我到现在还没看w...
记性也不大好了...溜了溜了。

Entered on [2017-12-07 Thu 20:58]  
Ended on [2017-12-07 Thu 22:47]
*** 2017-12-11 Monday
*** 2017-12-13 Wednesday
**** 补一下上次比赛的反思，顺带写一点东西
今天其实又怠惰了一天。。

首先是关于周日的比赛的反思

首先现场感受
------------------------
巨难受
我看题就有点慢了 精力集中不起来
然后非常蠢的前期慌 慌 哇这是什么？不会啊。。哇。。当时满脑子这些东西然后就有点紧张过度思维不清
如果是组队 感觉还能好一点 个人赛好久没打了
另外没有趁着封榜（这个封榜居然是不出评测结果）之前多交一点  说到底开局太姜了
封了之后发现 诶 二分？ 诶？水题？ 诶……这题这里写的是什么shit
我擦这时候我才觉得我可能只有最后一小时在线？
而且好多题我连看都没看。
这是中文题啊！
无语凝噎啊

哎 又受刺激了 而且压力更大了……（我为什么这么菜？别人为什么做这套做的那么快？kalili为什么这么强？我什么时候也能这样？这次凉了是凉的透透的 状态不好 又在204那里被空调热成傻子等等不管什么理由都只是次要的 最主要的还是 原罪之菜）

我这一周确乎是没怎么写题……
你一定会说,可是那太累了啊……
但是不努力怎么弥补自己的菜……？我现在比起去年的我到底有什么变化？该会的还是看不出写不对 

我擦这个是得分制的 我tm 我tm
加上ac率被大量的提交破坏了平衡……混淆视听
胸有不平啊

讲题了讲题了
a 签到
b 经典 两种1*2 2*1 拼满的方案 状态压缩（……）dp.i.j 第i行状态为j 异或 位运算推转移方程
c 水题……？（我看到小数就发怵走开了 封榜之后回来看感觉很水……）
d 暴力跑可以得分 枚举
e （一道看起来就是模板题的题）？？？没有人做出来
多重级组合 用到容斥
结论c(n+m-1,m)栅栏法（全部）
减去1种超k 2种超k……
f 比较简单（emmm）非常明显！一眼看出！我tm……反应了超久好嘛……我先想到最大值的最小化balabala……二分……
还有这个任务无法完成……（不记得有没有判断了……只记得tm我在想二分边界向前向后的时候被热成了zz疯狂失去集中力）
g 基础动态规划？？？转移方程？？？我大概花了一个小时怼这个题的暴力结果是dp？为什么？
dp.i.j 第i个字符为t
dp.i.0=min(dp.i-1.0+1,dp.
h 写起来很麻烦
单调栈 剩余字符保证凑满并够大就弹出
归并排序思想 ……
时间复杂度是
i 并不难 麻烦 模拟
递归枚举出所有牌型 56^3
tm我到了最后加时才看到这题……好像很水……
j 比较难？
我日kmp？？？我tm怎么没有看出来？
用next数组的最大值？？？
不是吧？？？
不是吧？？？
不是…  
更新一个t的next数组
枚举s……失配就把失配到前一处的子串加进t

-------------------------------
当天晚上的分析。。

总是想玩游戏，但是这次比赛的总结还是要写的，所以就一边玩一边写了。

其实冷静下来分析一下的话，我得到了一个结论，自己或许把太多东西放到了重要的地方，结果
到了最后几乎是无所得（当然家也是相对的无所得）
经常写这样的话：想打游戏，想看动漫，想做题……大概就是这样吧。
就像我从两周前就开始说这两周的事情了，但是果然最后还是近乎玩了两周过来（emmm，记不清上上周的事情了，记忆消退的越来越快了


结果。结果就是今天凉了。

先强行分析一波吧。回头把现场的分析拿来。首先，前期慌乱，不看榜，ac率不分析。第二，读题不力（当然听完题解之后感觉还行吧，非常幸运的避开了比较麻烦和难的题，不过有道基础dp我到现在都觉得暴力是有道理的=-=但不会每次都这么幸运啊....）第三，当然就是做的题少，二分的那个题....说实话我真的不能一眼看出来，我倒是一开始有二分答案的念头不过看了一眼题就感觉像贪心的某道题...这些不关键，关键在于这次好多dp，然后概率，kmp没看出来，模拟没做，啧。脑壳疼。大概剩下的就是忘记骗分了....


然后就是最开始说到的那个「贪心」的问题......我的结论就是我太看重周末的那两个考试了，不停的跟别人说：我10号校赛16六级17物理实验期末。反复扩大对它的恐惧，反复扩大他们的重要性，在这种反复中变得慌乱最后选择选择性忽视他们，因为在放大的恐惧中对他们复习什么实在是太困难了......

emmm，最后结论就是当成平常的日子过就好了，该做我的题还是做我的题，它考它的，无所谓...六级首先机会还很多，记得邓导好像是还没过……？2333.物理实验期末的话，听天由命就好了，首先这个老师……算了不说了。抽空看看复习材料和书就好了。


近来睡的超级香，裹着被子真正体会到了冬天舒服的地方。

玩一会睡了。
--------------------
然后这周其实没写作业。呸，写代码。
因为...周五要交深度学习的报告...这个深度学习课。每次我们过去都是去自己学习，就给了我们一套代码和一个pdf（直接讲深度学习的课件），我们就一脸懵逼的在那里无所事事，直到上周...忽然告诉我们下次结课，让我们写报告去...
于是这几日就在疯狂的补知识，看matlab的代码。
然后大概就是昨天晚上，看到调用logistic函数的时候彻底懵逼了。
（内心非常多的感概：卧槽？这又是啥？goup？godown？为什么这些循环起来就能完成训练？隐层起了个什么作用？这些他娘的公式怎么来的？又怎么用？
然后差不多一点一点的向上找，先从受限玻尔兹曼自动机开始搜起，然后发现这东西一堆推导，一堆概率公式。
嗯，怎么入手呢。于是辗转了诸多资料....
最后发现玻尔兹曼自动机原来是热力学统计模型？也许出自于一个ising model（还没看这个的资料）？物理模型的数学公式和应用是神经网络的基础？知道的越多，想知道的也就越多...
batch，softmax，logistic，回归模型，归一化....一个个奇怪的概念跃入眼帘，这也许就是我们当时看课件通篇认真读完却什么也记不住收获不到一样。

另外，了解了一点神经网络的历史之后，有些感慨。（以下总结或摘自机器之心）

人工神经网络（ANN）起源于堆神经系统的模拟，但生物学建立起了神经网络（NN）的整个框架却不能满足多层训练，直到Hinton和LeCun奠定和推广了反向传播算法（BP），才再次引来春天。然而生物学的无依据和数学性质堪忧的优化以及支持向量机（SVM）等后起之秀使得NN又一次走向低谷。

「第二次 NN 低谷期间，Hinton 没有放弃，转而点了另外一个科技树：热力学统计模型。」
于是他结合玻尔兹曼统计、马尔可夫随机场找到了NN的新模型：玻尔兹曼姬（BM）。
不久后他发现多层神经网络可以被描述为一种玻尔兹曼姬的特例：受限玻尔兹曼姬（RBM）
然后我们对于玻尔兹曼分布进行一些变形之后惊奇的发现....softmax出现了，很自然的在统计力学分布里出现了。
「非常巧合的是，量子物理学里面有个模型极其像神经网络，以至于只要了解过几乎都会惊叹两者的相似度。这个模型就是著名 易辛模型 （Ising model）。易辛模型（物理学界常见调侃：你3维Ising 模型会解了吗？）描述了晶格系统中的相变，解释了铁磁性问题（你可能好奇过，为啥这么多金属，就铁等少数金属特别敏感，而且还能被磁化。这个模型给出了解释）。」
等到hinton对能量函数进行一些操作之后（里面居然还有直觉...）..sigmoid函数出现了！「这时候sigmoid函数就有了自然的解释：玻尔兹曼分布下隐含层神经元激活的条件概率的激活函数」
「而优化的目标，就是极大似然估计，也就是最大化p(v) = ....，这里其实也非常有趣，因为和热力学统计中的自由能非常相关。」
「总之一切看上去都很有道理。Hinton 展现了 NN 和玻尔兹曼分布间惊人的联系（其在论文中多次称 surprisingly simple ），其背后的内涵引人遐想。甚至有人在听过 Hinton 的讲座之后，还发现 RBM 的训练模式和量子重整化群的重整化步骤是同构的。」
「之后「深度学习」这个词逐渐走上历史的前台，虽然 1986 年就有这个概念了。可以说 RBM 是这一波人工智能浪潮的先行者。」

「不过不久，人们发现，使用 ReLU 以及合适的初始化方法，用上 CNN，搭配上强劲的 GPU 之后，发现原来的深度神经网络可以照常训练，根本不用 RBM 预训练。RBM 虽然数学上很漂亮，但是受结构限制严重，而且在 supervised learning 方面往往搞不过直接暴力反向传播。前几年吴恩达在 Google 让神经网络自动检测视频中的猫的时候，Google 内部的深度学习框架几乎就是用来支持 RBM 等的训练的。而现在 Google 开源的 TensorFlow 等主流框架中都没有 RBM 的影子。很多从 TensorFlow 入手的新人估计也没有听过 RBM。

好了，现在除了各种小修小改（残差网络，Adam 优化器，ReLU，Batchnorm，Dropout，GRU，和稍微创意点的 GAN），神经网络训练主流算法又回到了 30 年前（那个时候 CNN，LSTM 已经有了）的反向传播了。」


嗯。其实下面还有很多内容，但是那是关于hinton这个永无止息的老头的新的探索和尝试了。
最让我激动的是物理、数学、计算机科学在那么一个闪烁的瞬间链接在了一起，层层面面，深究一个人工智能方面的问题，其模型来自生物的话我还可以理解，但物理...然后通过数学连通。可能是我接触的层次还太低了，虽然知道物理和数学息息相关的，计算机的内容可以通过数学建立一些模型啊图啊之类的解决问题...但是看到这个还是惊到了。怎么说呢，得到了惊人的相似性（甚至同构）？刚才从hinton跳到了一篇关于wittin的介绍的文章...已经没有什么可以说的了。
离着上面的东西还太远，我先搞好基础的啦。

不过真的是头疼啊...玻尔兹曼姬一点都不友好...一开始看着那些能量函数凶神恶煞现在看起来还是凶神恶煞...
好歹有点头绪了...知道程序重要的地方在哪，不懂的地方在哪，理解卡在什么地方，应该找什么资料（深度学习得恶补基础...）。

睡了睡了。

Entered on [2017-12-13 Wed 22:31]  
Ended on [2017-12-14 Thu 01:04]
*** 2017-12-20 Wednesday
**** QAQ
昨天晚上打cf一直打到2点....
哇，当我卡在a题的时候我的内心是崩溃的...脑子好像秀逗了然后一定要贪心一定要排序，dfs也没考虑好时间复杂度，吃痛。
好歹b题暴力过了...（我其实这个考虑了一下，最直白的10000*5000真不一定会过，结果200ms，也是醉）以后感觉10^4常数很小都可以n^2了....
c题连看都没看=-=rank疯狂掉.....难受啊....我上次cf还是做了3题的啊...啊啊啊......
什么时候能开完div2啊啊啊啊啊啊。
继续开好了...开虚拟...反正就两小时嘛....TAT

------------------

然后今天上午就起不来床了...七点多自然醒了一下，看了看表感觉还有一小时才上课，但睡意极大，就定了个半小时的闹钟，这半小时居然眨眼功夫都没有就过去了...敲掉闹钟继续睡！

另外机器学习那边很卡的啦。首先要做ng的习题，然后对于玻尔兹曼姬又不可能有新的理解......只好，就这么拖下去...


时间不够用啊...除非每天不打游戏...QAQ强人所难啊（顺便说一句，连睿神都抵挡不住魂的诱惑，哈哈哈哈）虽然说每天打了几个小时游戏之后就（索然无味）去学习了...但是tm哪来这么多几个小时啊...

虽然母亲说过想玩就玩......但是内心的贪欲还是无时不刻在抓挠着我...

- - ----------------

啊，买了个书架，昨天花了一个小时和阮海一起装了起来，最后瞎调了调连接处使它还算稳定就开始用啦。把书一个个摆上之后忽然感觉非常空虚：怎么书这么少！怎么连个书架都摆不满！

-----------------------

忽然困惑，git是不是会把org也当成md文件读...怎么会出分割线...还是说两者在转义上有很多一样的？
不过md好像也没啥特别好的应用...引用可能稍微有用，try一下

> 这是一个区块

> > 这是嵌套的区块？

+ R
+ G
+ B

粗体估计是没有，那么斜体估计也没有，比如我记得org是用|**|来当|**|层级*的*....
(其实有分割线就挺好的233)

-----------------

emm，一时不知道写啥了。这周末就要回家啦，我最近状态有点不对，心浮气躁的，啊，越是想摆脱这种焦躁就越会焦躁（这大概不是因为要回家吧...难道还有不自主的焦虑一说？）。。。
诶对了，老杨给我发了首庭園にて，简直是！

Entered on [2017-12-20 Wed 10:13]  
Ended on [2017-12-20 Wed 10:39]
*** 2017-12-21 Thursday
**** 写点日记滚去写作业。
我觉得我们那个深度学习的课是智障课，给非常稀少的古旧的课件，给一个DBN的还算具体的实现，然后啥都不讲，上了三节自习，忽然告诉我们下次交报告。就是智障课。上次告诉我们，只要照着它的DBN的实现简单讲讲它是怎么工作的就行了...那其实跟没有上过这个课没有任何区别。

所以我放弃写报告啦。算是赌气吧。不过这个课向我打开了一扇新世界的大门，大概就是这个课唯一的作用了。

发现比起上一次的笔记，还算是丰实了一点。但是看起hinton的视频还是吃力......也许不能直接看后面的RBM，还是要从前面开始。另外这个课是2013年的，这个时间我也是找了半天....总会心生一种：啊，这东西好老啊，那感觉学起来好不值啊的错觉。
不过这么一来时间啊，时间啊。

------------------------------------

今天就是比较无成的一天。上午回来后打游戏到睡午觉，午觉睡到起来吃晚饭，然后上知乎瞎看一些机器之心的内容（比较想找到RBM在现在的作用，可惜没找到），然后下决心再来看一眼智障课上的课件，发现哦，原来这个结构跟这图长得一样。然后里面的内核实质，比如softmax，比如为什么bp怎么bp，比如rbm内里函数是啥，一概不知。

使得可读性变差的最关键的一点是因为要向量化，所以要不停的做reshape。
另外就是关于定义的不清晰导致对于变量的定义感到困惑：为啥要这么做？为啥分？tm搞来搞去我都搞糊涂的变量其实如果理解了本体的意义就好了。

最后就不写报告啦。

---------------------------------------

对了说下规划：最近的话可以稍微放松放松，在尽量保证日常div2abc的情况下（即保证基础的coding的情况下），每天可以多玩一些，然后恶补数学。

《概率论》还没怎么开始看，不过已经在《代数》第二章刚开始的对称群（其实是关于置换的概念没清晰）就稍稍的卡了下（还要请睿神解惑233）。

感觉是，漫漫长路，对我的身心是一种挑战的感觉。

啊，明天要回家啦。搓手搓手。明天下午就不去了！溜溜溜，先保证明天上午能过的比较愉悦，写作业，早睡了。

Entered on [2017-12-21 Thu 22:31]  
Ended on [2017-12-21 Thu 22:51]
* 2018
** 2018-02 February
*** 2018-02-25 Sunday
**** 嗯，我回来了！
果然还是分饰多角比较有趣。

果然我这个假期凉了。

果然啊...

果然我还是忍不住自己的。没碰拜年祭却还是天天打开b站，最后还看了几部番。
果然看番还是会哭的。
果然看番还是素服的。
二者可能是一回事吧。

果然啊...

果然是这样一个千篇一律的假期。一个让懒惰懈怠一心追求当下的愉悦的我欢愉的假期，一个让担心未来不想默默无闻一心想做第一想做人上人的我愤怒咬牙的假期。
啊。人本身竟能有如此多的矛盾。

果然还是有一个gtd比较好。最怕的就是已经到了连gtd都不想去学的地步了...
去学去学了。

Entered on [2018-02-25 Sun 18:17]  
Ended on [2018-02-25 Sun 18:32]
*** 2018-02-26 Monday
**** 呼——
今天还好。
除了睡觉的时间有点长..晚上势必要晚睡一会了。中午居然一口气从两点半多睡到5点...早上也是从10点半开始睡11点睡着睡睡睡睡睡睡到9点多...
啧。
今天org学的不赖。

有几个调用不出来的东西挺烦的，耗了很多时间却没有实际收益。大概是真的调不出来...
这样看起来，今天能学个大半。
然后就可以着手设计gtd的格式和大纲了。
吃饭，然后还邓导书，最后随便玩玩跑个步。
吃我活学活用（咳，其实没学到时间戳）想到这个日记是用org写的其实还是很有不真实的感觉的...
<2018-02-26 Mon 18:29>
哇，好累啊。
其实就跑了两圈233。
不过晚饭之后的跑步不是很舒服，第二圈后面饭嗝上来了。
...洗过澡之后好生疲惫，只想休息=-=看来只能明天计议了。
这就看了三集overload2了....
怠惰这东西还真是说来就来。
<2018-02-26 Mon 21:28>

算了，能振奋一下是一下吧，主要是昨天睡的太少了吧。
另外今天上午我走在路上...脑子里的东西有点杂。
想重构那个游戏人生的美好世界
想昨天那个正环的题（呀今天没做题）
想量子力学那个支离破碎的现实
想自己违和自卑 为何处处受到压制
然后想这个想那个，感觉自己果然还是很需要gtd这个东西。是不是就能清空一下脑子呢。

啊，睡前还是挣扎着学了点（其实是汤圆打电话过来来着）明天随便学学计时报告，然后设计一下gtd文件的样子，顺便做两个小题，就完美了。
老杨可以的，加油（笑
嗯就这样。

Entered on [2018-02-26 Mon 17:21]  
Ended on [2018-02-26 Mon 23:20]
*** 2018-02-27 Tuesday
**** 耶
org差不多学完啦。剩下的记不住的随时查就好了，实在不行找英文文档。

太久不写代码 一写全是错。。真是见了鬼了。一道正环写了辣么久。

晚上下雨了，没跑成步。

明天一天无课，我再捣鼓捣鼓gtd这边，大把时间呢。
想着要不要来包咖啡晚上干tmd的一场cf呢。
啧。

可行！赶紧洗澡，打会游戏，明天看情况可以写点作业...嗯（咦，作业放到gtd里也不错诶，美哉美哉。这样就有许多的固定项目了，哇咔咔咔咔）

上午的课就没怎么好好听....果然还是不大怎么能集中精力了吗...或许需要打一些cf来凝聚一下自己？

Entered on [2018-02-27 Tue 20:43]  
Ended on [2018-02-27 Tue 20:51]
*** 2018-02-28 Wednesday
**** emm，有点难受
昨天晚上中了睿神的蛊惑，打了一晚上游戏....
有点压不住了...想魂3pvp，想打泰坦，想打起源...

先把gtd弄完吧。实验证明计时功能可以的，就算是sleep状态也算在计时的。这样我就。放心了。



Entered on [2018-02-28 Wed 10:24]  
Ended on
**** 诶不小心关掉了
三圈！吃完饭还是有点不行。不大行不大行。主要是好累...好累...
还有一个问题就是跑完步之后需要好好的洗澡，不仅仅是强迫症的需求更是舒适度的需求，跑个步出个汗洗个热水澡有着凌驾于睡懒觉的舒适感。就是每次都要洗好多钱！破洗澡器什么时候坏啊...快回到不花钱就能洗澡的状态吧！今天我认真计数还是洗到了两块多...想来前两天都是3-4++++吧....

今天又把读书笔记半认真的复制粘贴过去了...唉，虽然大家都这么做不过我还是挺难受的...
另外这个过程中感觉坛经，不，这些经书都很有意思啊...虽然我感觉大部分都是来自于文字本身的力量...但是有点想看。比如说「心外见法为外道。若悟得自心本性，就是菩提涅槃，离一切生死故。」就很有感觉hhh。

不说了，写着写着日记去看有趣的歌词去了...再写怕是就走神走没了。
赶紧多写两道题...今天中午本来还觉得：「诶这速度下去怕不是今天就能写完」，结果就写了一道题(−_−＃)

[2018-02-28 Wed 18:33]


哦剋，今天差不多4h。虽然做的题不多...不过慢慢找状态呗，省的什么不初始化，YESYes弄混这种错误到时候再犯....
满意！
本来跑步的时候还感觉：啊，今天明明是无课的一天，明明是全自由的一天，怎么感觉自己玩也没怎么玩，学也没怎么学呢....现在可以说，学的还行。可以开始玩了！

把14g流量拉满了，全变成死宅之物！hhh，不过感觉看不大过来，好多也不舍得看...
啊就跟ngnl的小说一样！不舍得看！

算了神智不清了，溜了溜了。


Entered on [2018-02-28 Wed 18:18]  
Ended on [2018-02-28 Wed 22:04]
** 2018-03 March
*** 2018-03-01 Thursday
**** 难受
本来...本来昨天是非常愉悦的一天的。
结果被突如其来的事件打破了。我想用掉昨天月底的流量结果用的过了头....多花了..350.
说下结论..
1. 流量计算是实时的，但流量查询不是实时的会有1-3h的延迟。
2. 因为1，所以后买流量包是没用的
3. 流量的监控是实时的，但电脑和手机的流量差异在30%-50%。所以手机监控是很稳的
4. 超出流量巨tm贵，巨tm贵，巨tm贵。
5. 好像没了。下次预留出防爆阈值，相信监控，给到准确的值。

好气啊可是毫无办法，看着钱哗哗哗的就流没了，真的是看着流没了。在我关了流量之后的两个小时之后的每分没秒都是煎熬，就是个没有止境的无底洞...

只能说，这学期大概是一个游戏都不能买了...想来每个学期都有各式各样的问题出现，手机坏了、电脑坏了、流量xjb跑......难受啊...真的难受啊...


第一节密码学的课受益颇多，应该是想看的书+1，想学的科目+1...

跑步搞的有点累啊...在想到底适不适合我们呢...每次跑完步之后都很累，晚上都需要很早的休息，虽然不是啥坏事但是会极大的压缩每日的行动时长啊...跑步半小时+，睡觉提前2h+....(つД`)ノ

睡了睡了 下午体育，上完了就是假！！就是3天长假！

[2018-03-01 Thu 12:33]

罕见罕见，我以为今天就没了呢。
我竟然打游戏打的有点厌了...（当然我知道也只是今天暂时的而已...）
身体无限疲惫，体育课换了个相当专业的老师，我们的待遇就相应的变得严苛了许多，虽然说是强度很小的「恢复性训练」，还是哭天抢地哀声一片，主要还是大家锻炼都太不够了吗...

下午回来一边吃打回的饭看食戟之灵，诶那种感觉，啧啧啧，食戟的还是非常有张力的，细数一下的话，用梗、爆衣、场景想象，打斗想象...总之以幻觉为主，以特效为辅，效果绝佳，让我饭都吃的尤为之香。

然后？然后大概就是打了会泰坦+炉石，打了会宝石td并又通了一次，回去看了两集骨傲天，然后又看了食戟6、7集吧...回头又玩了会1920分辨率的泰坦（意外的挺爽）

不说啦。。我去写两个题，累了就去睡了


Entered on [2018-03-01 Thu 12:11]  
Ended on [2018-03-01 Thu 23:45]
*** 2018-03-02 Friday
**** 诶
假期！假期！
哇哇哇，不要啊，要开会讨论新学期的训练和天梯赛事宜了...QAQ


咦，这个点了呢。
5点起来打了会游戏...吃饭..没跑步回来继续打游戏。
然后好像还有8道题的样子...今天做完吗...╭(°A°`)╮

[2018-03-02 Fri 21:50]


一直在打嗝...从晚上喝汤的时候就开始了...然后我作死的吃了俩鸡蛋，一晚上就停了两小时刚才又开始了...咯咯咯咯咯。


....讲道理，不卡大概能做出来吧(´･ω･`)但是卡了。
卡了。
难受。
睡觉了，加上这个题还差...6题
呵.(


Entered on [2018-03-02 Fri 11:28]  
Ended on [2018-03-02 Fri 23:59]
*** 2018-03-03 Saturday
**** ...
又卡了。
又卡了啊啊啊啊啊啊！

[2018-03-03 Sat 13:03]

昨天没跑步，今天又没跑。毁于一旦的感觉啊。
4点半大概我刚起来的时候棣文找我。。又扔给我一份编程作业(´▽｀)我倒是没啥，权当是复习一次面向对象的编程了吧，感觉收获也不是没有hhhh，成就感也是十足的，就是有点小累，然后顺便花去了相当多的时间...然后最短路那一套差4道应该还，一下午大概7h的编程时间虽然在那里但是都不是做题...
另外的另外，没玩游戏没看番有点憋得慌，不过念及明天还tm是周末就感觉好多了。咩哈哈哈。明天大概做完那套题，顺便开下一套，然后水几道模版爽爽，剩下打游戏看番！

嗯大概就这样了，有bug我也不管了！睡了睡了


Entered on [2018-03-03 Sat 13:03]  
Ended on [2018-03-04 Sun 01:40]
*** 2018-03-04 Sunday
**** 困困困！
退退退！西内wednesday。
困困困，起来做题。

剩下的越来越难越来越麻烦了orz，不大想做了，下次带着spfa一起处理掉好了。
这也算是勉强做完了。
开新内容啦。
再不开这个最短路怕是要把我拖死了。

[2018-03-04 Sun 12:43]


Entered on [2018-03-04 Sun 10:15]  
Ended on
*** 2018-03-05 Monday
**** 周一了诶
三天假期过去了QAQ
昨天下午打了会自虐小游戏，更好了起源玩了玩起源，看了会gate队，晚上上床看了会ngnl，嗯昨天幸福满满的过去了。因为昨晚的雨第一天早上没有跑操。上午水课数据结构，晚上有选修电影欣赏，据说先是讲一些历史知识啥的，没电影看还是有点小失望。所以中午不打算睡觉了，直接写点题，晚上回来大概玩玩就睡了，明天课不少的(´▽｀)。

[2018-03-05 Mon 13:07]


不过果然还是好困！好困！！！
不行我去摸鱼了。狗屎困意。
实在不行晚上带着mac去上课。

[2018-03-05 Mon 14:31]

发现这种环境下emacs大量耗电，关了关了。


Entered on [2018-03-05 Mon 13:03]  
Ended on [2018-03-05 Mon 19:20]
*** 2018-03-06 Tuesday
**** 今天怼带权并查集
呵。
poj1182，食物链，如临大敌。

[2018-03-06 Tue 16:05]

tm，发现昨天的3038wa了，如临大敌的查题解一点一点对照修改，最后对到最tm不可能的while读入，然后a了。
我tm....境界不够，做题太少了。遇到这种问题就大为光火....
不过搞得我兴致缺缺。
带权并查集不会改板子，感觉直接换个板子比较舒服一些，说到做到，这就改。改完就不做了。大成功，大概就用了。。嗯，10分钟！
打游戏去了。

[2018-03-06 Tue 17:14]




Entered on [2018-03-06 Tue 16:04]  
Ended on
*** 2018-03-07 Wednesday
**** 为什么这么困呢...
6点多起来发现不需要跑操，一气又睡到9点。起来之后还是浑身不适，可是我最近也没跑步啊...这两天下雨(つД`)ノ
昨天好像一个题都没做啊...虽然说课不少可是不能这样子呀...（大概是有些疲了，就去打游戏看比赛看番了...
带mac来上课了。。感觉。数据结构就是水课（震声）做题做题。

[2018-03-07 Wed 09:58]

中午玩手机，忽然看到周五比赛的消息...惊坐起，重新安排下。

被一个昨天晚上写完的并查集卡了三小时之久。对着题解一点一点看，根本找不到问题...
就输出跟别人不一样，找了测试数据来，发现原来输出不一样所以不能判定0 1的情况...狗屎，狗屎，狗屎。
还是不够自信啊(´▽｀)老是觉得自己的带权并查集写的不对，其实就是卡了特别数据。。

托没路走！托洛梅路走！（我不认同啊啊啊啊！）坚持一下！再多写两题！

[2018-03-07 Wed 19:29]




Entered on [2018-03-07 Wed 09:54]  
Ended on
*** 2018-03-09 Friday
**** 昨天没写诶
昨天上午去水课。。写了两道（大概？）的简单搜索。。

下午体育之后彻底放飞自我，没一点心思写题。。虽然说今天下午就要比赛了可是有点紧张的过分了..
说到底不习惯不带板子的比赛吧...(つД`)ノ
然后kuangbin的dp。。感觉略难，去看简单dp，也不怎么会............
硬着头皮做几道吧。

Entered on [2018-03-09 Fri 09:38]  
Ended on
*** 2018-03-12 Monday
**** 怠惰3天。
嗯。周五还行，背了个kruskal居然a了\(//∇//)\，剩下的不是蠢就是骗分，嗯。最后排15...嗯大二第四...还行吧...

然后疯玩了两天的起源（其实已经玩了差不多一周了，天天在玩）。。起源的支线系统还是挺蠢的，不过蠢不过我的强迫症。也可能是我不是处于一个欣赏游戏的角度而是愉悦自我的节点上，所以玩的还算尽兴。育碧细节做的真心不错，文本量也是可以的，有的地方好像还有奇怪的乱入，所以既有魔幻（大毁灭，文明续存，「大放厥词」，与神祗一战...）又有历史（埃及艳后那时期的一段混乱史，搞得我甚至对真正的历史到底如何产生了兴趣...习俗，信仰...混乱的时代的愚民狂徒也表现的很好...）以及游戏剧情（兄弟会的起源啊原来是。）很有趣的是没有几个boss是无恶不作的大恶人，尤其是中间有一个强力意志者比后面的凯撒都丰满的多...感觉为了给游戏者减轻负担，有些地方是执意的丑化了boss...另外破战斗系统还要打诸神、大象，给那种容错率极低的boss，让人难受（感觉打这种只能是用特定的几把武器才能打得过..比如增加容错的「击中后回血」属性。
总而言之还是挺好的游戏的。埃及的风景很棒。记得前两天看了张kky在埃及拍的照片，与起源相差无几嘛...可能跟比例把握的也比较好有关吧。
啊，疯玩的起因是有个满级的活动...很想做就直接莽了。说起来比起黑魂游戏性差些、build性差些，胜在...胜在满级时间短XD。说到满级我想起一学期都没满的wow......

在上数据结构...链表真心不想学QAQ。
呃...继续做并查集吧..不过在那之前先把周五比赛的题看一遍。。

[2018-03-12 Mon 10:26]

每个看似大块的时间几乎都被占了...
周三、日晚上训练，今天晚上的选修，全都是如梗在喉性质的。我也不知道为什么，总之就是不舒坦，很不舒坦。
明天晚上还有选拔...诶。。想起选拔赶紧把拓扑的题做一下，然后做下作业...

另外中午2点半睡到4点半醒了居然浑身疲惫还想睡...最近玩的太疯又缺觉了大概...
嗯？想到好像每个被占用的晚上都可以有一个快走的锻炼似乎就没那么难受了。
昨天饮水机没水，今天饮水机坏了，打回水却只有滚烫的热水...极度缺水中...

[2018-03-12 Mon 17:08]



Entered on [2018-03-12 Mon 09:56]  
Ended on
*** 2018-03-14 Wednesday
**** emmm
昨天比较忙。。中午一睡三小时起来之后还是很困，以后中午不能睡那么久了...
晚上面试下一批校队的。。感觉就是瘸子里挑将军诶，虽然感觉我去年跟他们差不了多少就是了...
啊，过得好快啊...自己还是好菜啊...

[2018-03-14 Wed 08:41]

另外mmp我并查集停了快一周了。
好像就是上周三开始做奇怪的搜索啊dp啊，现在又在补拓扑，晚上训练之后怕是新的专题，凉凉啊。

[2018-03-14 Wed 10:13]

tm，陷入只想睡觉的贤者模式了。
啊啊啊啊啊啊啊啊。
要不定个一个半小时的闹钟？然后赶紧上床睡觉？
事实上我很想一觉睡到晚上训练...

[2018-03-14 Wed 12:17]

这年头还能被其他人鼓劲也是有点意思。
啊，水了点模版题，有点难受啊。
我回去看后缀自动机的时候，引入的时候是二分+哈希，「这个做法非常经典就不详细讲了」。我：？？？？？？哈希我也得补咯。
感觉字符串就这么过了的话自己怕是要凉啊。看了眼kuangbin的专题，ac自动机，后缀数组，感觉爆炸多的。

[2018-03-14 Wed 21:05]



Entered on [2018-03-14 Wed 08:25]  
Ended on
*** 2018-03-15 Thursday
**** 看了眼gtd
凉了啊。跑步凉了，3个晚上被占，周四动弹不得，没剩下几天。
我自己这个，真的，很需要gtd督促啊。
那么这个3天把字符串做完？我觉得不靠谱啊。忽然月中有点难受啊。不过3.10比的赛吧？emmmm，算下来这个月做了多少题呢。。说是这个月其实就是开学以来。。才30，平均一天两道，真的，水了啊。

毕竟月底就是比赛了。总不能吃老底吧..没什么好吃的啊也。

上午上课非常认真的看了看后缀自动机。
卡在了parent数组...其实继续硬啃也行的，不过实在是san值爆炸。
不得不说前置技能点的不够啊。
回过头去看ac自动机。发现前置还是不够，kmp有了，字典树不行。又得从字典树补起。呵。树。

不说了，起源也没啥好玩的了，魂3校园延迟爆炸断了我的pvp梦，现在也就崩坏+炉石需要微肝，泰坦宝石td闲暇一玩，偶尔还能和小染玩玩大富翁，也就没什么游戏打了。（就是说过去了一波强游戏流）。
哇说起游戏流，我真是那种一玩起来瘾就停不下来的玩家。起源是流程短而且蠢，所以几天就a掉了，想当初warframe，魂3，个个都是2、3个月才平息的热情，更别提大一两次重拾坦克世界，两次重拾炉石，一次重拾星际等等了，魔兽还是不拾了，尤记得当初魔兽一玩一个学期成绩一落千丈23333。

唉。所以说其实做题也是类似的一个过程，只不过因为难度梯度和前置技能等等关系，流程会缩短很多，比如kuangbin那套并查集还没补完，都有些不想做了。最短路亦然。

希望能好好利用三天小假吧。最好能拿出让我满意的成果。上个三天比完赛我就沉迷起源去了，这次补回来。

歌也没怎么好好扩展了。
2月底花了那么多冤枉钱下的番也没怎么看，啊好忙啊。
啊好忙啊。

[2018-03-15 Thu 16:46]

啊啊 啊。
效率
效率
效率
低低低低低低低低低低低炸了啊。早知道还不如全身心直接打游戏的好。
看直播，看同学打dota，听歌，总之注意力分散，也许体育课之后过于疲惫还是早休息的好？学习的效率实在是不堪入目。


Entered on [2018-03-15 Thu 16:07]  
Ended on [2018-03-15 Thu 23:15]
*** 2018-03-16 Friday
**** 效率爆炸低
低低低低低低
不如打游戏。
真的低，一天就做了点作业，一道扩展kmp。好难。

Entered on [2018-03-16 Fri 23:56]  
Ended on
*** 2018-03-17 Saturday
**** 看了眼别人的经历
就觉得自己除了怠惰大概只有怠惰了。
我已经要大三了，却完全比不过别人大一的热情与题量。
啧。每每想起便感觉很灰暗。
大概自己没有废寝忘食的那种狂热了。一天一题，呵。

转一下思路吧。。有点僵硬。做点并查集。。

结果今天大概就做了一题的样子...？记不太清了，连今天怎么过的都浑浑噩噩的。
下午一直在玩就是了。

上午中午有心学，不过无力...
难受啊。

Entered on [2018-03-17 Sat 10:22]  
Ended on [2018-03-18 Sun 00:29]
*** 2018-03-18 Sunday
**** 晚上打cf
做点综合水题吧...
tm，还想做水题的，没想到狗比赛是要换10种语言做每一道题.......
md所以写点思路就算了。。没学语言的心思暂时。
放弃了。不过学到了多个数gcd的方法...算了算了。

Entered on [2018-03-18 Sun 00:30]  
Ended on
**** 如今真是...
咸鱼失去梦想啊。
经过几天的怠惰之后，终于今天训练被高中生吊打。然后忽然偶然看到那些从大学才开始接触acm甚至大二才接触然后final金牌什么的...备受打击，至于后来又偶然看到了claris巨佬的记录，瑟瑟发抖，无法言语。
怎么说呢。。自己如果不怠惰的话或许还有机会触碰到的，另一个位面？
几乎抑制不住自己那种：「就这样浑噩下去吧，快快乐乐的，没有半点痛苦的大学生活」的想法了。几乎抑制不住自己去想象灰暗惨淡的未来了。
可是怎么办呢？父亲在某种角度让我去当兵是对的啊，因为我不够狠，因为我吃不住苦，从很久很久以前就是如此。

下定决心steam卸载吗？不可棱啊...积郁只会以其他的形式体现...等等。所以有没有刷题解郁的操作？
明天再说吧。
md忽然发现并查集那套拖了10天了。明天k掉啦。说到做到。

晚上做了个不错的题，构造题，但是有用到筛法。

嗯...没啥了，今天也就是上午起来写了点代码，然后打炉石，打alan wake。
昨天晚上梦见自己在打星际家园了。起床的时候恋恋不舍，可是已经找不回来了。现在盛行的说法是eve是很像它。我一点都不觉得啊。
起来想了想，能让自己如此有热情的游戏，还有坦克和没玩完的魔兽世界吧。坦克是不会碰了（flag立下），这辣鸡游戏就是时间损耗机。等自己快老死了大概可以玩（。魔兽也差不多。

睡了睡了。真是左右为难的生活。

Entered on [2018-03-18 Sun 23:54]
Ended on [2018-03-19 Mon 00:18]
*** 2018-03-20 Tuesday
**** 把并查集做完啦。
然后做完拓扑，嗯，就可以开最小生成树啦。
哇，今天上课的时候看noi大佬的课件，完全懵逼，一点不懂。。真是令人绝望啊。
再说慢慢来怕是于事无补了啊...
做拓扑去了，然后今天晚上美滋滋的看看番就好了。

天气骤冷，从二十五六度一下子掉到了5度，令人窒息。我因为懒正准备拿出拖了好几天的夏天衣服，结果一场持续好几天的雨直接降温二十度...衣服都不用换了，甚至还要拿出更厚的外套。

感觉课越来越难了...密码学和信息论都是浮于表面则易于理解，而深入其中，想知道点东西的话...就好难。比如为什么块加密的第一种gh法的gh和g^-1h^-1等价。。

昨天晚上本来应该写日记的，结果。。卡了道zz题一小时之久，气的心塞，虽然是自己的小失误..但是当时的心情就是极端爆炸，气急败坏，对。
昨天选修课终于开始看电影了，看的是《罗拉快跑》。难以想象这是二十年前跟我们岁数相仿的电影...
一开始我看卡通跟现实结合，然后几乎一直伴随节奏乐，给了第一次罗拉跑步许多镜头，压抑的喘不过来，以为讲的是一个现代生活的「压抑」「快」把人变形之类的东西。如果罗拉直接被打死就结束的话也许差不多吧...只是经过每个人然后照片后事的手法很奇怪，不知道想表达什么。世事无常？阴差阳错？
再往后看居然是石头门一样的倒退重来而且拥有上一次体验记忆的故事...于是不可抑制的脑子里循环着世界线是会收束的，世界线是会收束的，结果一定差不许多...
然后发现这个故事想表达的东西就不一样了...变成关于时间，蝴蝶效应，女权...最后变成一个教科书案例放给广大学习电影的同学(´▽｀)，从这个意义上是真的成功啊。
当然第二条线的颠覆法律和第三条线的赌场怎么说也是很有讲头的。至于其他的，交给oo那种专业的人去写，我们去看就好了\(//∇//)\
不过忽然想到赌场赚大钱是很可以解释的啊（。当然这个地方如果这么解释的话那么就是罗拉有意识的改变世界线了...

所以发现这些多世界故事流行不是没有道理的啊...记得前天大概还写关于alan里面奇怪的电视机播放恐怖节目讲量子自杀，也是说了不少关于多世界理论的事，虽然应该只是用来佐证里世界的现实依托使得故事真实魔幻。关键是多世界理论对人们的影响真的很大...以前看石头门的时候没怎么在意，回头可以重补一下。。反之0好像出了...Makise那么可爱（甚至南宁站被用作官方用户名...印象太深）重补不亏。


哇居然有这么多人来上自习嘛。。搞得我也有点想上了（。然而我并没有几个晚上有空...

嗯，在获得了一些满足之后来写日记还是很容易获得更大的自我满足的。
这也许跟在获得了一些痛苦后来写日记是很容易获得更大的痛苦异曲同工。
说起痛苦...上次看到的...呜呜呜...

Entered on [2018-03-20 Tue 17:36]  
Ended on [2018-03-20 Tue 18:04]
*** 2018-03-21 Wednesday
**** 切模板题好爽
tm，我记得暑假板子题看好久的说...

额。好晚了才想起写日记啊。
算了。。这破cf太晚了。。水了两道题还不知对错。。然后c卡的死死的。虽然才做了一个小时但是好累啊。。。

Entered on [2018-03-21 Wed 11:36]  
Ended on [2018-03-24 Sat 01:32]
*** 2018-03-27 Tuesday
**** 不行啦
有点熬不住了。
果然身体第一，锻炼身体不能停啊。虽然说锻炼和熬夜这两者并没有抵消的操作就是了...
周三要讲dp...我自己的dp烂的不行，本来想水水过去的，今天可以说是跟圣杰大佬说了一晚上的话......
先补下前两天的日志吧...周四头疼直接睡过去了，周五做了点pta的题，周日的模拟赛有点让人担心，然后我就提心吊胆的周六周日两天动漫补不进题，周日下午模拟赛（没想到很水啊...希望真的到天梯赛也这么水，没有图论，没有二叉树），晚上又训练...晚上又找回了失去了很久的不自信...因为一直在做奇怪的水题啊，pta的题啊...忽然做到邀请赛的题，一看a水题，b线段树扫描线，c带钥匙（压缩）搜索，d缩点的网络流/二分图，e经典dp，f阅读题，g水/二分图，h拓扑...自己水了a黑妹大佬水了gf直接就滚去摸鱼了...一直想写c就是没想好框架...摸鱼很难受。

与圣杰大佬相谈甚久。果然大佬的生活和我是不一样的...他是啥都学，不，应该说是啥比赛都参加，然后「被迫」去学相关知识，最后选定了机器学习作为主攻...据说拿了二十多个奖了...然后就可以找到相关导师说我这个比赛得奖了balabala然后可以接项目啊，写paper啊之类的...
对，跟导师的交流这一项上，让我很惊异。比如跟教他数模的老师问他能不能拿平时分满分，最后连期末都不用考...跟物理院长email说能不能多给平时分毕竟自己是绩点第一什么的...然后问他如何上手前端啊、机器学习啊，他说就找相关老师接几个任务就行...
另外就是熬夜这一点啊...两天上手py，半夜起来写老师给的项目...tm，感觉这个人...非人啊。
莫名其妙又想到了他的时间表orz，只能%%%%%。就是自律、敢做、会抓机会、又努力的大佬啊。
总感觉写出来没有那种直观的交流冲击力啊...睿神总说我自怨自艾，事实就是因为菜，前面又站着dalao，涌现一波动力才会这样啊...

现在努力应该还不晚吧...虽然已经大二下了。
所以立下宏愿：两天做出这套dp！

不过现在看来不现实啦。
另外好想学机器学习...等这阵dp、周末的天梯蓝桥结束了再再再说吧www
不说啦，回去写第一道状压dp...

Entered on [2018-03-27 Tue 01:33]  
Ended on [2018-03-27 Tue 01:56]
**** 
跟母上大人谈了一下自己的困惑...
主要是想玩和不能玩的循环与瞻前顾后的困境。
母上大人提出通过完成短时计划来把心拉回来。确实，我放大了看自己的弱点和缺陷就会无时不让我痛苦。那么org，以后又要多多拜托了....现在想来当初（啥时候来着）认真看了两天的org是多么明智，虽然这几天忙的没怎么用...


tm，hexo内核的也不知道哪个环节不匹配，会让机子疯狂发热，甚至占用100+的cpu，窒息得很。



这两天沉迷reol的歌...我就是一阵一阵的...前两天就疯狂的听uplift spice的歌，不过塔吊人真好听。现在是monster和染真好听。当然amazing trees和vv-alk无可取代的坐稳码码听歌的头号交椅。


继续做dp去了...唉...


Entered on [2018-03-27 Tue 21:26]  
Ended on [2018-03-27 Tue 21:38]
*** 2018-03-30 Friday
**** 啊。
昨天被老板抓着训了十分钟感觉就像一个小时一样漫长。
其实也不是在训了，大体就是说我是计软院挑大梁的，我必须要有作为啊；我将来如果想是工作的话acm一定要搞出成绩啊；自己要疯狂的练啊；副队要有副队的样子要主动啊，要经常在活动室里啊；要积极大创啊；你这样不行啊之类的...
然后...嗯，自己果然是母上说的那样「被安排有任务才会去努力」的那种人，很轻易的就会怠惰，很轻易的就放松要求，然后就演变成父亲说的对自己不够狠...嘛...
对了这好像是周二和母上谈论的内容，她说我从小被她安排的太多了..然后「失去了主动能力，却能在有任务逼自己完成的时候开发自己的能力，又不喜欢被布置任务」...是这样的啊，深有体会啊。
来活动室的时间还是太少了。比如昨天上完体育在宿舍呆了好久才慢吞吞的过来，今天也是下午明明没课，中午睡了不起，起了也要漫无目的的打开电脑玩玩这个玩玩那个，熬到6点吃饭才过来。

嘛...明天比赛，今天还是早休息吧。
呃...忘了复习模版了...最短路的dij和bellman，并查集，二叉树相关，约瑟夫环，拓扑排序这些了解一下就好了...明天还有两小时在路上...

忘了写关于斯皮尔伯格的新电影的事了...听群里的人说上百个梗，简直骗钱。说什么就是漫迷游戏迷的福音，吹上了天，搞得我好想看。等下一个清明假期！

今天没什么精神...日记都写不顺当了，我去跑个步回去洗洗睡了。

Entered on [2018-03-30 Fri 20:53]  
Ended on [2018-03-30 Fri 21:48]
** 2018-04 April
*** 2018-04-03 Tuesday
**** 
这两天虽然人在活动室但是。做的题是没有的。
今天好歹把mst专题水完了....全是水题几乎...接下来开紫书的题和线段树吧。我感觉我搜索还不是那么稳，再做点紫书的经典题。
话说今天玩了一天...三节课一节好好听的都没有....信息论自暴自弃一直在玩炉石，密码学完全不想听完全跟不上（都不用走神就跟不上的快车）也在玩炉石，数电在写作业....

我那天想写的是...我就算身在活动室里也不是能全心全意的集中在做题上的...比如周一我写了两个多小时的des，完全不知道错哪。今天对拍一小时，才知道置换用的下标没-1，左移两位写的是错的。
还有就是，我想要的到底是什么？快乐？还是未来？
似乎从高中起我就已经被这个问题困扰了。
每天回家吃饭，打游戏到深夜三点，中午起来吃饭，打游戏到深夜三点。我是在逃避凶猛的现实吗？还是说我就是离水之鱼，缺了游戏就过不得？还是积累了太多需要排解的废物？我想除了一些因为自由时间少的幽怨之外大概大部分都只是为了玩而玩吧...当时不会过脑子的，满脑子是游戏，现在能支配自己的时间了反而玩的没原先那么凶了，也终于停下来回首问自己：为什么玩游戏？或者换一个角度，为什么打acm？
时常也会羡慕舍友天天在宿舍里打游戏，也会想起自己有时候也是这样的。但是又会因为他们各方面（专业上的）很菜而心生不屑与自我上位感。
我现在感觉自己还是更想要一个安稳的未来。

突然入夏，中午竟然开起了空调。那种情况感觉不开自己无法入睡，哪怕起来之后还在想着不去上课了吧要不然，会死的会死的....想来自己耐热性是真差。转念我舍友在不怎么冷的时候开空调，大家似乎都差不很多。这么说自己的心性还差得远。

睿神昨天说起武理工的那事来着。了解了一下大概之后我只是觉得可怖，继而就是绝望。这种东西多像那些什么什么圈内的规则。自我成环封闭的系统，内部如何我们无从得知。还有多少？重的像这种，轻的像数模只许几个队伍说起系统竟然想到了wju，自我印证的循环之类的奇怪的东西。不过用在这里也挺好。
气都气不动了，哀也无处可哀了，最多想想这不过是一隅，激起浪花然后平复，于是系统更加完善，池水更加幽邃，像病毒一样突变进化适应性愈强，而内里本质不会改变。

周六天梯赛....状态说不上好，有点紧张了。主要是1-1和2-1卡了太久，导致整个时间上不够用，2-4不知道啥板子...3-2和3-3看都没看...
总结下的话就是差个2-4和3题随便开的分。说起来简单，差了得半小时多和相当多的做题经验。181跟220差40呢...

周日蓝桥杯，做的时候感觉很水，出来一想这个不对那个读错题了0分我日什么玩意。
不谈了。蓝桥大概是崩了。第一次写提交了没反应的考试型题。

嘛...总记得应该有挺多东西没写的。算了等电影下完就回宿舍。明天不想上课。。。。反正也不听。


Entered on [2018-04-03 Tue 20:34]  
Ended on [2018-04-03 Tue 21:42]
*** 2018-04-10 Tuesday
**** 好久不写日记了啊。
清明开始就没动....
清明之前的四天真是挺厉害的现在想来。没碰游戏，没碰动漫，没怎么碰手机。
应该说清明我好好的放松了自己几天之后自己就怠惰了起来....两次尝试振作都被线段树和复杂dfs击败了...是我太懒了还是这两座大山太难了？想当初我线段树是照着题解写的，勉强能理解，但是现在...还写不出来我有点接受不了...

清明第一天就在宿舍疯狂摸鱼(dac，恐怖黎明)，第二天看电影(头号玩家，爆裂无声)，第三天摸鱼看dac，第四天上午摸鱼，下午打选拔。
是这样啊，之所以觉得怠惰是因为收不回心来了，感觉跟刚放完寒假暑假的感觉特别像。我暴氪炉石，拾回坦克玩了玩（犹记得前两天还在说坦克世界不会碰了，flag真的没一个月就被我自己收了）无不是这种体现，现在的话可能更多的心思偏向炉石吧，说不上好坏，不过比偏向坦克让行人安心多了。
看了眼去年的日记，自己打坦克打了两三个月（从接近期末到暑假放假，放假后一直到10月左右是warfrarm，圣诞到寒假结束是魂3，自己打游戏到旅程从没停过。
啊说起氪金...下次说吧
还有头号玩家！
还有啥..关于build...

md被树支配了——在gtd里写下：做完划分树、主席树、rmq、伸展树、树链剖分的专题...感觉我可以去死了。
忽然危机。
吃饭，写stitp的简介，然后今天做划分树。

明天二刷头号玩家。


Entered on [2018-04-10 Tue 17:15]  
Ended on [2018-04-10 Tue 18:22]
*** 2018-04-14 Saturday
**** 摸了好几天了。
昨天炉石上线新版本，嗯这两天打炉石确实有些多了。
今天和昨天一样，就摸了几个比赛的签到题，然后抄了个线段树。
有点想摸了，看会电影带书回去看吧。

emmmm，rmq最通用的做法就是线段树，但是st好像可以更简便的做一些查询最值的问题。直译应该就是区间询问类问题，有bit，线段树，st等等做法。

周三摸了一天，走去看电影一路走的累的不行。。二刷了头号玩家（。晚上数学专场直接螺旋升天，反演、fft这种难的不说，简单的找规律和积分求面积我都不会了（其实是连抛物线方程都忘记了）

周四体育之后来写了两个题的样子。哦对，把划分树写完了。划分树挺有意思的，唯一一个不是裸的板子的题还是要抄题解。

周五上午做电工实验做的心烦意乱，电路好好的但是仪器线路有问题...然后捣鼓完了大创就睡觉，晚上搓一晚上炉石。
说起大创，哎...印象里就是吹，以及吴的付出和我们俩的摸。

最近状态好差。今天好好休息，明天再来活动室啦。

Entered on [2018-04-14 Sat 16:39]  
Ended on [2018-04-14 Sat 16:48]
*** 2018-04-16 Monday
**** 唉
这两天状态奇差啊，是不是因为最近炉石打多了啊...
前天没写几个题，昨天比赛更是水的一塌糊涂（自己水）。kmp去求不连续随便n^2跑的字符串寻找，多组数据看都不看疯狂询问自己为何wa1然后心态爆炸，这和我大一的时候有什么区别？
我甚至觉得自己比以前还要菜上一分。

跑过来就是抱怨一下，另外最近睡觉总也是睡不够？晚上睡了接近9个小时，中午又睡了两个小时，起来的时候恋恋不舍...
补昨天的题一会去看电影了...

Entered on [2018-04-16 Mon 15:40]  
Ended on [2018-04-16 Mon 15:45]
*** 2018-04-25 Wednesday
**** 诶又好久没写了
周日比赛凉了。三题，第八，一等...看起来虽然还行，但是果然还是差的远...吴永琦5题...我的三题除了签到都是最后半小时莽出来的...甚至有一个是最后一分钟a的...刺激是刺激，但是。。。菜也确实。

woc才反应过来十天没写了，这一周过的真的是浑浑噩噩，毫无知觉。最近状态就是很差，每天不知道自己都干了些啥，十五天就写了划分树、rmq的几个板子题你敢信...
啧。
jojo！我不做人了！
但是果然还是控制不住自己的想去看番啊。
今天写了点bit，大概理解了下逆序对离散化...emmm，这周要开树链剖分啊QAQ

上周三看了湮灭和狂暴巨兽。后者就是爽片，没啥好说的，倒是湮灭十分有趣。一个完全棱镜dna的遗落南境。但是隐隐感觉好像也在说（最内核的是人心而不是外星人）？设定很棒，严谨的话...大概不需要追究那么多？
不过能在一个有限的时长自圆其说，美轮美奂感觉已经是很极致了。虽然很多东西都没表达出来，尤其是在到达塔之后的那一段让人感觉很难受，虽然是致幻一般的场景，却在外星人出来之后变得诡异起来。
不过我个人还是对蠕动的掌纹啊，特质的dna啊，主角团的各种混合啊（物理学家越来越像死去的医生，主角身上带出别人的纹身）比较感兴趣。
小说的话可能会更有趣吧。

最后。

贫弱贫弱！无駄无駄！
uryyyyyyyyyyyy

Entered on [2018-04-25 Wed 11:11]  
Ended on [2018-04-25 Wed 11:36]
*** 2018-04-30 Monday
**** 感冒了....
大概是，周五的事吧。
那天发现舍友感冒了，一笑置之。第二天起床自己喉咙跟粘了一块口香糖一样难受（其实想象中更像蛞蝓），现在还没好。。
主要是这段时间太热了啊....
热到宿舍不开空调我就几近抓狂的程度...
然后因为太热根本觉不出来是因为热还是感冒才出的汗。。

看了三四天，终于看完第三部jojo啦！jotaro强无敌！
欧拉欧拉欧拉欧拉欧拉欧拉！
无駄无駄无駄无駄无駄无駄！
这就是我的逃跑路线！
你失败的原因只有一个，DIO，那就是你激怒了我。
你要说的下一句话是！
德意志的科学技术世界第一！shikaiyiji！
jojo！这是我最后的波纹！
呀嘞呀嘞（yareyareda☆ z)
YESYESYES NONONO
oh my god！
每个人都是为了克服不安和恐惧以求心安理得地活下去！（DIO就是厉害）
Kono DIO Da！
wryyyyyyy——
RERORERORERORERO——

2333333

用给人安利的话来说（作者的话）：「它讲述的是一部获得智慧，让自己的心灵得到成长，然后变强的故事。 就算结果是死亡，在那个过程中主人公得到了勇气，心灵得到了成长，那么在我的心中这就是一个happy ending。」
嗯。果然第四部第五部第六部好期待啊XD，哪怕听说jotaro早逝了QAQ...

emmmm，走神看了会书。

所以从上周四开始就没怎么做过题了。
原因嘛。集中不起精神，切切水题还行，一动脑子去思考bit之类的东西就会很难受。
摸了一周了...要不要继续摸呢。
或者换个专题切吧...做那个啥，那个传递闭包。


Entered on [2018-04-30 Mon 14:09]  
Ended on [2018-04-30 Mon 16:22]
** 2018-05 May
*** 2018-05-08 Tuesday
**** 怠惰=。=
emmm，最近就真的是怠惰了。完全不想做题，每周大概就水几道水题，训练的时候也是负责切水题，毫无建树...
然而没两天就要去比赛了...
唯一值得庆幸的是我的感冒好了很多。
每天都在打游戏看动漫中度过......想做题又不知道做什么...眼高手低可能又开始了...
大概这段时间有点恐慌，有点焦虑，沉不下心来...

唯一值得庆幸的是偶尔还会看一点的书...?翻开艾柯的鲑鱼一书，不由直呼「仿讽文学世界第一」。

今天晚上也是，坐在活动室里两个小时，有一个小时在玩手机。
不行啊这样的状态下去的话....
准备晚上回去打cf了...还记得上次div3的题都tm没过。心态爆炸。
对啊。。md回去补一下div3的题好了...看一会书吧。。

听了一会lain的分析...

Entered on [2018-05-08 Tue 19:14]  
Ended on [2018-05-08 Tue 21:05]
*** 2018-05-15 Tuesday
**** 我回来了！
我从湘潭回来了！
没带电脑去三天的旅程还是有些僵硬的，不过下周去西安好像是只有两天，不带也行吧大概。
怎么说呢...比赛的过程是十分僵硬的，具体见赛区记吧。
当然只要有奖那旅游的过程就是公费的，美滋滋。

emmm，日记写崩了，一边写一边玩手机看dota比赛，还写个题解，还做个费用表格。。。（然后发现两个队伍用的钱比去年三个队伍用的还多）

Entered on [2018-05-15 Tue 15:56]  
Ended on [2018-05-15 Tue 21:41]
*** 2018-05-22 Tuesday
**** emmmm，来迟了
本来是打算今晚好好写写游记的，结果到了活动室莫名其妙赶上开会（其实是我还以为邓导是队长来着...直到现在我也这么觉得），买了波票，跟老师打屁了好久。
这个过程中终于理解了西安站k题的线段树里面到底维护的是啥了。
下定决心补线段树和树状数组，结果上来就碰了一头包，我第一个经典题没找到思路，甚至看了题解还是一时不知道维护的是什么...
然后就带着电脑回来，想着今天晚上没啥事，明天一天没啥事，就躲在宿舍里写点日记，写点题解，感觉挺好的。
然而回来之后就一直在玩slay the spire，杀戮尖塔。再次证明了游戏性的重要性——与游戏本身简单与否没有太大关系（也许可以说是roguelike的便利性？）使得本身单薄的游戏变得耐玩起来。当然和欣也一起玩才是最有意思的地方。不然什么脸黑天胡制裁combo都无处分享不是吗。其实炉石也是一样的，虽然炉石有一些「想成为最强，想变成最强」的一种执念——亦即充钱的冲动根源。
所以一直拖到现在才开始写日记。

有些疲累，上床了...
我可能需要买一个床上电脑桌。不过感觉只要自己身体还能坚持的话还是不想这样的....

最近可能有些纵欲过度了。买了海王星涅普顿123代，买了杀戮尖塔（这游戏的价格据说十分硬核），买了卫生纸，买了些生活零碎用品，如今还想买电脑桌。自己也许是真的很开心吧。

毕竟是icpc的银牌啊。。还是有一点含金量的（虽然就这次比赛而言十分水）
上一周的游记/赛区记还没怎么写这一周就又去了西安...
啊...所以啊。

深切的感受到自己文化的缺失与遗漏，那种感觉就像是小时候企图完好的保存出手里的一捧水却难免因此而摇摇晃晃，像是看着雪景想要把美丽与静谧封存在某一个时刻（确实做到了），像是想要把和某人相与的时光停滞或让它成为自己的一部分而心不在焉。所以我永远都是那么的愚蠢。

cf欠了一堆题。上次ec的ab都没过，我感觉自己需要一些时间。
就要蓝桥杯了，还是有些紧张的。

明天还是不要看电影了，感觉会很大的影响晚上的训练。看身体情况吧，毕竟天这么凉爽，上周去看妇联3的那种极端天气我都强行去了...
欠的东西越来越多了...就越不想补。不过总还有那么一些东西在激励着我前进，使我不至于完全的成为废人，可能是自己比较幸运的地方吧。

要写的东西有点多。先把游记写完可能思路会清晰一点吧。那么睡了。

Entered on [2018-05-22 Tue 23:28]  
Ended on [2018-05-23 Wed 00:07]
*** 2018-05-23 Wednesday
**** 感觉自己不能这样摸了啊。
看了点icpccamp的文章，其实就是看了点大佬的一点东西，感觉自己再这样摸下去就什么也没有了，连acm这么有趣的东西都不能好好的玩。

Entered on [2018-05-23 Wed 15:02]  
Ended on
*** 2018-05-24 Thursday
**** 啊手边有mac真好
没事就能来写一点。
才知道是明天就溜去北京了。

昨天晚上训练的时候非常僵硬。g题一个简单的规律题我竟然去模拟C的过程模拟了一个小时然后心态爆炸=。=b题是个非常奇怪的动态规划，他们说很简单我却感觉完全摸不清楚...我的dp还是需要加强QAQ....嘤嘤嘤。
背包都慌得一比的我，哎...

emmmm，然后忘了想写啥。
上两次的题还可以勉强一记。
睿神说的啥仁王我都玩不了了啊...连买的海王星都没怎么玩...当然回来前两天总是比较放纵啥都没干，结果这连着四周跑有点吃不消啊...等到江苏那站完了之后差不多就该英语周然后六级然后期末全开了吧...时间感觉非常吃紧啊。毕竟这学期的各个科目都差不多还没开始学...（应该说进入了大一以为自己绝不会进的状态了嘛2333。数电、密码学、信息论、数据结构、电工实验，嗯应该就这些）然后那期间就算学好了剩下的时间估计也用来做题了吧（也不一定，我记得上学期好像是打了一个月的瘫克来着）

我在碎碎念什么啊...
溜了溜了，补点作业回来写游记。


Entered on [2018-05-24 Thu 20:50]  
Ended on [2018-05-24 Thu 21:30]
*** 2018-05-28 Monday
**** 我从北京回来啦
嗯。蓝桥杯凉了。
三等。校内垫底。
dp，数学。
嘛...其实看到题的时候就知道凉了不过心中还存有一丝侥幸。
以及没有对比就没有伤害的和我住一起的lyy就是一等榜首=。=

以上。

但是作为旅游来说还是不错的...遗憾可能是没去清华北大玩吧。有规定的参观时间，然后我就跑到旁边的圆明园，在里面转了四五个小时。也仅仅只是窥其一条路线而已。圆明园大得可怕，圆明园中的圆明园基本上可以说是一点都没转。据偷听来的导游所言，圆明园是焚毁最严重的，因为多为木质材料，而西洋楼那边因为石质较多所以还存留了一些遗迹。
然后又简单的走了一小圈颐和园。
前天晚上还去了后海公园和南锣鼓巷。旅游街商业街没什么好玩的，不过胡同对于我来说还是蛮有吸引力的。

也许这就是旅游杯吧。

下周去徐州不知道要成什么样。。不管了，先摸两天再说。话说我湘潭的题解才只写了一点点...这样下去我要嘤嘤嘤了。

Entered on [2018-05-28 Mon 10:03]  
Ended on [2018-05-28 Mon 10:18]
*** 2018-05-30 Wednesday
**** 虽然我确实很摸
但是我也没办法啊！我现在已经完全无法平衡学习、做题和游戏这三方面的时间了，更别说还要补题、写游记、写题解...
我现在最想的是补dp....蓝桥吃的亏啊。
竟然转眼就要六月了，六月就是考试的月份了...自己平时也没怎么学，就有点怕。徐州应该就是最后一站了。回来之后就能收收心安心做平时的事了吧。跑来跑去的还是挺累的。

不说了，赶紧补点题。

现在其实挺奇怪的，想玩游戏，又不是那么强烈，然而一跟睿神一起玩就是一个下午...

Entered on [2018-05-30 Wed 10:09]  
Ended on [2018-05-30 Wed 10:12]
**** 难受啊。。
想补矩阵快速幂了又。。不会啥就想补啥。
不过这个好补，明天k了好了...

我居然看出了一道并查集的板子题。终于能感受到做板子题还是有用的这件事了。
不想回去。。再做点题好了

Entered on [2018-05-30 Wed 21:32]  
Ended on [2018-05-30 Wed 21:45]
** 2018-06 June
*** 2018-06-07 Thursday
**** 心态炸了。。
本来以为这周末能做完主席树然后放开手脚复习英语顺便水题，结果我这怼了两天没见成效，反而看到树状数组套主席树整个人都不好了啊。

听说暑假要特训...emmmm，好像就是聚众打cf？不过我现在有点水啊....有点慌

Entered on [2018-06-07 Thu 20:54]  
Ended on [2018-06-07 Thu 20:57]
*** 2018-06-11 Monday
**** 好久没写了。。
嗯。。最近就是疲惫疲惫然后懈怠懈怠，我周四计划着周末写完主席树，现在才动了两道题，倒是玩游戏的热情不断高涨。

晚上打满了一场cf。原因在于我狂写一道题试图枚举出所有的情况而钻入牛角尖久久不得。心态爆炸。我总觉得比赛的时候的心态也不是太好，太过轻易的动摇而崩塌。

下午跑去活动室看了一会遣悲怀，感觉自己就是在文字之间寻找一种支离破碎的感觉，尤其是自己对于文字本身的理解越发纤薄的现在，无从在故事之间或语言文字之间找出奇妙的共鸣，只能身处迷宫对着随处可见的碎片感慨而无法重现整个城堡的建造过程或描绘那样一种一比一的现实地图。

Entered on [2018-06-11 Mon 23:31]  
Ended on [2018-06-11 Mon 23:37]
*** 2018-06-26 Tuesday
**** 是有好久不更了啊...
唔嗯...最近大概在一种看漫画(e站啦)、打游戏、复习的循环之中...
至于好久不写日记的原因...大概是好久不碰mac了吧...
每次条件反射一般想起做题时就会想起主席树呢，然后就叹一口气把这件事搁置了。
其实就是怠惰啦。游戏那么好玩，一款游戏玩久了玩腻了还可以换一个口味继续玩，虽然我不是很清楚玩了这么多年的lol的室友到底是一种怎样的执念呢...

emmmm，就前一阵玩游戏比较多的时候看侏罗纪世界2来着。然后就感觉这电影满满的qte（跟着舍友看过一点点的底特律、鬼泣）和黑魂式跑酷。什么屋檐疾走、狭廊追逐，都有一种「主角应该是资深魂玩家没错了」的感觉。就这样出戏的看了这电影，最后想了想也没给母亲他们推荐，毕竟商业元素那么多，我怕破坏了可可的恐龙梦...还有恐龙吃人、笑面坏蛋什么的，总觉得为时还太早。

尝试着做一会题吧，就当复健了...毕竟一个月了呐。



















Entered on [2018-06-26 Tue 20:52]  
Ended on
** 2018-07 July
*** 2018-07-03 Tuesday
**** 嘤嘤嘤
我连二分都写不好了...
只会嘤嘤嘤了。

前两天看了动物世界和超人总动员2。我觉得动物世界挺好，是个合格的爽片。虽然有些地方还是挺怪的，但是原著在那里摆着，剧情上保证还是有的。表现的也很不错，这会有了一点看动漫的感觉。
超人总动员2嘛...养孩子比当超人难的多hhh。小杰nb！

才在活动室坐了一个半小时我已经有倦意了...
然而在宿舍刷泰坦0死号可以一下子坐一天。放假了，那些想玩的游戏也都喷薄而出，monaco，泰坦之旅（使我不至于去沉迷gd），传火，爬塔，贝姐，甚至crashland，无限...
怎么可能满足的了嘛！
可是！
可是！
我身为最菜副队，暑假还要参加特训，甚至被列到final队里。
然而我连二分都写不好。
那我回去继续写了。。。

Entered on [2018-07-03 Tue 20:05]  
Ended on [2018-07-03 Tue 20:28]
*** 2018-07-09 Monday
**** 回家真舒服！
嘤嘤嘤，做题好累。虽然整场都是大佬带飞，但是。。。
哎。
这几个没做出来的题大概还是可以莽出来的，虽然我不知道sat是什么，不过另外一道dfs，一道缩点求双连通？总之应该属于我们能做的范畴的，然而。

有点累。。上床歇一会。。

回家是真的舒服。
南京真的热。
要死要死。上床了

Entered on [2018-07-09 Mon 19:45]  
Ended on [2018-07-09 Mon 19:52]
*** 2018-07-10 Tuesday
**** 
基础训练
常规计划
初稿


Entered on [2018-07-10 Tue 12:13]  
Ended on
*** 2018-07-16 Monday
**** 啊啊，我的休息日
休息日就这么过去了啊。
略有不甘啊。
又回到了每天训练补题的时候了。不过说起来我上一次的题解还没写，最近几次也只是补了一道题而已。那么既然休息已经过去了，这两天认真的写一下吧，反正宿舍也马上就要我孤独一人了。
昨天应该去看电影的。最近好电影那么多，怎么看也都不会亏的。我昨天就是稍稍满足了一下游戏的欲望，玩了会魂2泰坦爬塔，基本上大部分时间在看银魂。
怎么说呢，银魂果然还是很适合放松的乱七八糟番啊。
啊当然很多时候也更想看英雄学院那样更紧凑的番。另外最近还看了浪客剑心，啧，就目前的几集来看，就是失了吐槽的银魂嘛...虽然银魂的吐槽似乎是核心。

训练的话，还好吧。如果一人承担那确实有些沉重了，不过我们毕竟有三人，做题讨论的过程还是挺开心的。不过我还是有点被lyy压制，在只有我们两个的那次比赛里基本上就是lyy单打了。好在有琦神在。

每天吃40多块=。=还是稍有些心疼的。基本上肉不会少，但是每天也不想点黄焖鸡这种便宜的，更不想跑到时刻规定极为严苛的食堂，所以点一些既带一些小菜（素菜保证营养可口味上的混合），然后加上肉（把子肉、红烧肉、卤肉），差不多就是我每天在吃的了。
总会以消耗大，疲累为由安慰自己。当然，母上说的「自己的感觉最重要」肯定是第一要素的，只是心里还是会有一点微小的挣扎罢了。

嘛，想了想也没什么好写的，有这时间不如去写每日的训练日记了。
那就这样。

Entered on [2018-07-16 Mon 10:13]  
Ended on [2018-07-16 Mon 10:33]
*** 2018-07-19 Thursday
**** 
今天打了场牛客多校，叉姐的题有点厉害啊...
只过了4题，还有一题是查的oeis，这时候只能嘤嘤嘤了。
挺有意思的题都是。
但是讲起来就一点都不好玩了。因为讲的东西基本上一点都不会。

算了。我忽然发现上次漏了一次写题解的原因是因为那天被老板留到8点半多。发现的原因是因为又被留了，又到了八点半多。我真是醉了。

今天比之前还要疲累，一个是信息量填充的，感觉啊忽然什么都不会的疲累，再有就是这么多场下来其实已经没什么紧张感了，忽然一个多校还是有点绷弦的。

不说了，明天去上海，好好休息吧，这几天就当摸了。

Entered on [2018-07-19 Thu 20:17]  
Ended on [2018-07-19 Thu 20:23]
*** 2018-07-23 Monday
**** 啊啊
集体训练正式开始了。
吴永琦大佬不会真的凉了吧。好担心啊。

昨天又玩了一天。因为预报有暴雨就没有出去，本来还是想去看两个电影的。
睿神天天拿warframe诱惑我，令我心神不宁。

前天的话是上海大都会赛，然而差一题金。emmm，具体的话，我和琦神时间大多花在一道奇怪的数位（伪）dp上了。然后我a题题意漏了一个关键点，导致lyy写的时候白费了很多时间和功夫。
以及最后才知道有道题lyy可以开我没有告诉lyy（那道题榜上没人过...）。
总的来说lyy和琦神nb。我大概参与了两题，都是很简单的那种。

感觉的话，上海大学还是挺好的。给人的印象很好。

然后。老板真啰嗦。

Entered on [2018-07-23 Mon 10:30]  
Ended on [2018-07-23 Mon 10:38]
*** 2018-07-27 Friday
**** 啊好累
难得的比较容易的一次区域赛的题

反正从老板前天开始追踪补题开始我们的摸鱼日子就彻底到头了。
真正成了做题5小时，补题20小时了。
今天又尝试treap无果。再看一会，万一写出来了呢=。=
每天都这样真的累。几乎要保证12小时的代码和学习时间。

好消息是明天就是last了！之后的周末要好好休息以及看电影。
坏消息是我欠的题还不少，另外dp的题还没出。出的话肯定又是一番极其困苦的奋斗。数据结构的还好吧，我觉得。

Entered on [2018-07-27 Fri 23:46]  
Ended on [2018-07-27 Fri 23:49]
** 2018-08 August
*** 2018-08-02 Thursday
**** 啊，讲题好累啊。
紧张的不得了，讲的时候头脑一片空白，糊弄着就过去了。
dp好难啊。

然后这几天大概处在一种比较zz的状态里，也没怎么好好补题（虽然昨天为了出dp题倒是做了不少。。），比赛时候也是多在摸鱼，题解也是没怎么好好写了。
比如今天，回到宿舍看看手机，吃个饭看看银魂，然后洗个澡上床看小说看到疲累了，便下床来开始做题。总觉得有些阴阳调换错反的感觉。明天最好改一改。不过前两天确实是挺努力的，这两天回来连拿出电脑的心思都没了。

上个周末（就前两天）跑出去看了三场电影。先是摩天营救，然后是狄仁杰之四大天王，最后看了西红柿首富。怎么说呢，我不是很喜欢西红柿首富这种风格，倒是更倾心周星驰的那种（说起来好像有不少致敬的地方），像我这样容易钻牛角尖的其实容易被剧情带动所以比起笑点更在意主线，也许这就是银魂吸引我的地方吧。
狄仁杰我没看过前面的，只记得有什么龙王好像电视上飘过几眼。
这部的后面虽然还算得精彩，不过真的不是什么想象力的巅峰云云那样，相比我倒是更愿意跑到知乎翻一翻「有什么庞然大物，存在的或不存在的皆可」这样的问题，或者翻一翻scp里有什么有意思的东西。我比较不满的就是初见得地上有什么了不得的符号显现，还道是什么魔道玄幻就要展开了，结果非要撕扯在现实和非现实之间，打着幻觉、方术的幌子什么也施展不开，偏偏就是爽和矜持的摇摆，大大不如头号玩家。
摩天大楼，据说是很老的人设又拿出来卖了，但是我看得舒服（嘛，不过一到民众和警察就感觉有些强行衬托的感觉了，不舒服）。千米高空极限角度跳跃，独木桥，沿摩天之楼外壁侧滑、站立、数数跳至涡轮之中令人「心旷神怡」。

emmmm，我得去忙了，再扯些有的没的怕是一道题都没法补，估计要被lyy怼死啦。这两天不出工不出力的，一直在摸。

Entered on [2018-08-02 Thu 22:56]  
Ended on [2018-08-02 Thu 23:21]
*** 2018-08-09 Thursday
*** 2018-08-18 Saturday
**** 我真是日了
我真是日了啊
笔记本没电了卡也就罢了，怎么nmcf也卡的跟狗一样，劳资疯狂被hack心态本来就爆炸好不容易调好了tm还jb卡卡卡提交页面都打不开，我打nm呢，我打nm呢？？？
认真的做一场比赛这么难？第一题读错了我本来就很不开心的，还tmhack劳资，我真是日了。
主要这个打不开心态爆炸好吗。最后五分钟hack掉，改好了交不上去哪说理？
洗澡冷静去了，辣鸡cf

Entered on [2018-08-18 Sat 00:51]  
Ended on [2018-08-18 Sat 00:54]
*** 2018-08-26 Sunday
**** 啊，久违了，日记。
见字如面。

mac最近也开始有点卡了，不过重启总能解决问题，我觉得是我一直开机加上一直要写typora（我下意识就是一个tpyedef），果然美观还是有代价的，虽然一时可能不会显露，时间一长开的一多输入法就跟不上打字了。

舍友顶着发抖的双腿在做俯卧撑，真的厉害。了解到隔壁宿舍截然不同的气氛与习惯，还是蛮有意思的。就像我了解一寝比较好（破）玩，以前只是知道他们聊的比较开，仅此而已。相较而言我们宿舍的学习环境已经不错了，在承俊和阮海不开黑的时候（小声）。这样想想的话也许自己开学之后真的不能大量的窝在宿舍里了呢。
不过开学之后好像会被课程淹没啊。
好就好在，大部分还都是电脑方面的，应该还是比较好搞定的。至少不用做那么多作业啦。(/ω＼)

又看了两场电影。。emmmm，这个暑假的假期大部分被我用来看电影了。。数一下都看了些啥。。狄仁杰、大白鲨、摩天营救、西红市、一出好戏、蚁人2、风语咒、小偷家族。可惜没看药神和邪不压正。可惜了。然后就是我的精神状态是有些紧张和压抑的，所以小偷家族并没有那么深入的看进去。也可惜了。
现在大概就等最后的碟中谍了。
嘛。。不过这样一看的话我在电影上花了好多钱啊。。
我同学告诉我一出好戏前面是喜剧后面是悲剧，我看了之后觉得他在骗我，明明是前面悲剧后面喜剧。
蚁人看得很舒服。对，舒服。看狄仁杰的时候要是有这种舒服的感觉就好了（然而注定不会）。

我把巨人看完了。
好看。真的好看。叙事、作画、音乐、立意与绝大部分现在那些番云泥之别。
但是我还是只想提泽野。
我再重复一遍，泽野本命。emmmm，我也不知道为什么。从高中开始接触二次元，从高中开始用二次元的音乐填充自己的空虚，自己就已经深入泽野不能自拔了。klk，青驱，再就是，巨人。
哪怕我已经千次万次的在坦克世界里听过他们（也不知道该说是好还是不好了。。但是没有泽野我就没法打坦克已经成为了既定事实），再次听到依然还是会肥躯一震。再就是那大概是炒冷饭一样的各式变奏以及变奏直接变出的别的曲子.....百听不腻。
去年的网易云这样告诉我：「世界属于泽野」。3225次泽野，榜单前10里除了第10是以前单曲写码的whisper of winter，其他的全是泽野...（当然和vv-alk那个辑真的是及时雨很有关系），听到最多的歌词是「世界」。（through my blood,shout,blumenkranz,layers,gravitywall...)
找个时间去一首一首的对巨人里的曲子。我要把专辑里每个曲子出现在哪个位置全都找出来。
有点过于私人化了啊。嘛权当我在口胡好了。

hhh，果然看番多了人也会中二起来吗。
暑假果然没干什么正事啊，我把存货的小英雄看完了之后想看老番，看了十集的浪客剑心之后感觉设定好像哪里见过，限刀令...然后跑去温了几集银魂一口气看到了250集。期间炉石出了新版本兴奋了大概有那么一个星期。这两天趁着今天休息，昨天网络赛，前天准备网络赛连着三天直接把一二季巨人看完了。
只是看了二百集的银他妈我居然没学会吐槽，也没学会丢节操有些丢人了啊。

啊对了，ti8输掉了，2:3，lgd2:1被连翻两把。别的都没什么，只是fygod真的。fy。fy。

想了想又好久没用gtd了。这个东西可能不适合我（。不过org还是好用。该规划规划。
规划着规划着任务就堆积如山了，dsu，lctlca，trie，更别说我那掌握的蛇一样的线段树bit。主席树更是学了跟没学一样。
一点一点来吧。

不知道写啥了，在短时间倾吐一堆之后会突然感到疲倦与空白，不知道该说些什么。

对了，这个月的日子过得飞快。感觉就跟放假或者是在学校天天摸鱼的某个月一样，还没有注意到就已经过去了。回顾起来就显得特别麻烦。不记得做过些什么，也不记得自己会了些什么，只记得自己还算是写了几个做题报告的样子。


Entered on [2018-08-26 Sun 23:14]  
Ended on [2018-08-27 Mon 00:38]
*** 2018-08-27 Monday
**** 啊，好想走啊。
听老板叨叨真的是很难受的一件事情。
又或者是我对于高要求的抗拒？但是总是觉得非常别扭，非常膈应，非常憋屈，非常愤怒。我真的，想让他闭嘴。
同学问他想题想不出来，他居然说个典型的注意力不集中。
于是我这是又认定了个假想敌吗...像成老师那样的。

大概总是在一种逼迫与热爱之间摇摆，我想做，但是不是要那种「要做就做最好」，「要做就全身心投入」。那种冲突感就是在于明明是一种强制逼迫偏偏说成是没有乐趣在里面。然后在功利性的出发点上跟我们说些什么不要把比赛当成功利性的东西。
总之老板话太多了啊就是。

我可以享受，我也确实在享受。
这种事，说了也只是废话。
一边说着对不起对不起一边把刀子捅过来？好像不恰当。一边加压放担子，一边说不要有压力有担子。

所以我不喜欢到活动室。

Entered on [2018-08-27 Mon 17:28]  
Ended on [2018-08-27 Mon 17:52]
*** 2018-08-29 Wednesday
**** 结束了啊
暑期集训就这么结束了。
听着各位总结的声音总觉得没有实感。


Entered on [2018-08-29 Wed 16:45]  
Ended on
** 2018-09 September
*** 2018-09-04 Tuesday
**** 果然有点吃力啊。
想要在满足自己各种欲望的同时刷满这些专题果然还是有些困难的啊。
gtd对我来说也没有那么大的压制力，感觉不如直接贴markdown到主页置顶。

晚上也不怎么想写代码了，整理整理暑假的东西就睡了。
网络赛啊，接下来的网络赛。。哎。打的不好就要拆队伍是真的吓人。我反正是悬起一把刀。

不过自己说起来要是能把通杀戮尖塔进阶20的那股蛮力重现出来不知道能达到什么程度呢。
今天新生入学了。。。

另外大概是定好了21号去吉林市了。吉林省吉林市。好远啊。

碎碎念完啦。晚安。

Entered on [2018-09-04 Tue 23:19]  
Ended on [2018-09-04 Tue 23:21]
*** 2018-09-21 Friday
**** 有点没有实感啊

坐标，吉林-吉林。
摸了两周，这就跑来吉林了。
实实在在的摸了两周。想第一周的时候，数位dp和搜索专题做的飞快，然后后面用了两周都没有写完dlx的一半。

这两周大概因为舍友的原因捡起sc2玩了玩？然后很快的热情就过去了，合作也就那样，残酷任务也就那样，虽然很有挑战性，但是要在不停背板重来的基础上搞，我觉得不行。对战这辈子不可能的，每周打打突变就行了，突残的难度确实很高，背背板偷偷鸡也就过了，执政官一起玩确实很有意思。
不过说起来什么一起玩了都有意思，阮海开始爬塔，在我的怂恿下加入机器人大卡组神教，就是看着他打也十分爽啊，跟自己一人通关不是一个感觉的。

因为很无聊（很紧张），就不停的玩手机。但是手机又没什么好玩的，ngnl看完了——稍微提一句，帆楼那章挺好，机铠种一般（主要是本来的理由过于牵强，为了追空而追空），地精种那篇就感觉很奇怪的了。首先是给出了一个「没有天赋的人本来就赢不了天才」的结论却没有给方法（好像给了，是靠作弊），然后无厘头的让缇儿追着空他们跑了，整一章的打斗围绕着「对于性癖的执着」而来，真的是..变成奇怪的休闲轻小说了。max也没比赛；炉石不想打；崩坏已经卸了；牧羊人没动力开；之类的，所以就一直在刷nga。
不停的翻nga，炉石，sc2，wow区，最后发现还是wow有意思。但是又太肝，而且没有朋友一起，不符合现实。

「桌子只是太无聊了，想让别人知道他的生活而已」
还是小染会鸡汤。
不过我发现自己还真是想把日记给别人看，不知道是处于什么缘由。我想了想，给出了一个也许能说服别人却不能说服自己的理由：因为孤独，因为想让比尔了解自己。
实际上自己是不是有什么暴露之类的影子就不得而知了。

去写吉林day1了。
哎。好累。

Entered on [2018-09-21 Fri 21:36]  
Ended on [2018-09-22 Sat 22:11]
*** 2018-09-22 Saturday
**** 
说是要写吉林day其实也没写，昨天晚上还是特疲惫的睡了。
今天有心写却无力了，我吧眼镜丢在了出租车上。。嗯，是我的风格。
大概终于能配眼镜了吧，也大概终于能知道自己多少度了。
反正这一趟是能报销了，26-227 银奖，离晋江虽然只有一步之遥，但是实际上是一道金牌题的区别。
嘛，虽然我是队伍里摸鱼的那个，但是还是很开心的。
摸了摸了，看不清楚啥也写不好。各种错字我也没法管了。

Entered on [2018-09-22 Sat 22:17]  
Ended on [2018-09-22 Sat 22:20]
** 2018-10 October
*** 2018-10-08 Monday
**** 日记的事慢慢来啦

因为国庆一只在play computer games，就荒废了好几样东西，不知道这二十天能弥补回多少。
二十天啊，只有二十天了。
我自己的专题肯定要做完，然后总结也得写完，还有吉林记，然后大概就没啥啦，手游已经要顾不上了，每天魔兽炉石可能就堆满了。
国庆还有不少好电影没看，不过也好歹不算一直在玩，是有空了就玩，弟弟也算玩的蛮多的。
然后欠了不少觉，今天中午睡回一点。

就这样吧，做专题去啦。一会还要补一点作业。
我就是来理一理头绪的。

剑来的风格和雪中不太一样啊，有些地方有些造作，就刻意的痕迹太重了，不过大部分地方还好。

Entered on [2018-10-08 Mon 18:14]  
Ended on [2018-10-08 Mon 18:21]
*** 2018-10-14 Sunday
**** 玩了好几天了...
这几天基本上没怎么做题训练...就固定的两次训练，以至于我到现在还没做完那两个专题...
卡了一个树链剖分的题，大概不是我lca写的有问题，应该就是线段树上出了岔子，但是不会改啊，也不想重新写了。
卡了三天了。这三天来一打开电脑就是这个题，然后莽上四五发不过，心态一崩就取打游戏了。

这三天基本上都在跟李承峻打sc2。不满足于打电脑的李承峻还拉着我打了2v2，还打到了黄金...1v1好像不买战争宝箱不给开放？只能打10把首胜才给开？
不过不是我说，李承峻虽然很有心思，也很有热情，但是这个硬实力还是差了点。我指的就是运营。我是不会承认四五十的apm能干些啥的...起码多线是妥妥的打不起来（虽然我也打不起来，苦兮兮），所以我只会打打电脑，不会去打天梯...从这个角度而言李承峻可能很快就能超过我吧。

Entered on [2018-10-14 Sun 19:22]  
Ended on [2018-10-14 Sun 19:23]
*** 2018-10-15 Monday
**** lyy受了刺激...
说要每日一次训练...我觉得是有点不现实，两天一次还差不多。
不过相应的我也得努努力，这两周就多翘点课吧。

Entered on [2018-10-15 Mon 10:28]  
Ended on [2018-10-15 Mon 10:29]
** 2018-11 November
*** 2018-11-15 Thursday
**** 来写日记啦
哇，想想自己没写日记的天数，一个多月了吧。
这段时间...
比如lcj的sc2技术突飞猛进。
比如lh已经通了空洞骑士（几乎全通），开始炉石。
比如lr已经开始看炉石直播。
比如徐州银牌，青岛金牌。
比如可可生日，比如我生日。

比如。
一个月前我还在疯狂wow呢，现在就已经产生了毒瘾抗性了...简单的说就是突然肝累了，不想肝了，肝不起来了，没意思了。
不知道是为什么呐。
突然冷却疲惫也不像warframe那样是因为肝到了极致举目无求剩下的内容基本上都不想碰那样子了。

大概，是因为两周多前开始玩ff14的原因？就感觉wow被ff14的光辉完全地掩盖了...wow给人一种厚重、浑浊、人与人之间的氛围也是，社会化贴吧化的感觉。可能是我nga看多了，对于满级的一些东西产生了抵触与反感，也吃瓜看戏了不少恶念的东西，感觉就是。算了，当我在为自己的afk找理由好了（事实如此）...

总而言之ff14天下第一。
愿ff14的环境四季如春。

净土啊。
钓鱼、买房、弹琴、肝采集、肝制造、打牌、养鸟，我大概也算是圆了自己很小时候的一个愿望了。因为很久以前（小学）沉迷星际家园，所以对于带有多种行业的游戏都极其期待。记得有一阵忍受不住自己的欲望了，找了洛奇来玩，可惜自己在一个地下迷了路，心态爆炸直接delete游戏，体验极差（。
现在找到了ff14。


最近又开了妖怪手表复刻活动，到晚上的时候就是几十成百人浩浩荡荡如蝗虫一般杀向fate...我觉得大家称呼为暴民一点也不为过hhh。我已经不止一次被卡掉了，开着特效就是爆炸，完全看不清楚屏幕的。关了特效纯靠堆人也能把我卡掉。虽然反复fate跑来跑去的，不过大军压境还是很有意思的，热热闹闹的，刷几个小时也不累的（才怪，昨天刷到两点累得不行就睡了）

emmmm，想来于柳从暑假开始玩，到现在游戏时间是6天，我两周前开始玩，到现在已经3天了。我还是能肝啊（自夸），不过这事已经被睿神反复验证了哈哈哈哈（黑魂、warframe、爬塔也算）。
其实是这两周一直在疯玩，一道题都没有写，敲黑板，一道题都没有。今天和上周周四是这两周唯二的训练，我也不怎么打算写题，补补专题和日记算了。

哦对了，周末要去参加于柳的婚礼（手动扇子脸）。这游戏...emmmm，有一种东西叫幻想药，可以改变种族性别样貌（重新捏脸），所以...emmmm，结婚了用幻想药的话...由此我得到了一个显然的结论，于是我对周末那个婚礼就很期待了www。

一下子欠了好多内容还真是不知道从什么地方说起。
首先这两周确乎一直在玩（重复），lyy实现了他的说法，真的，除了周二琦神有组会不训练之外几乎就是每天都在训练了。
成效不能说没有，但是好累=。=为了「补偿」，正好青岛也金了嘛，剩下一个深圳是被田忌赛马当作下等马扔到大佬堆里，只需要争报销就可以了...难度还是很高的，不过无所谓了。
这周继续摸，没有问题。

其实我在上信息安全攻击与防范，然而我从来没有听过课（大概就是第一节：我用ppt讲课，不用课本，没听，后面就凉了，一点也听不懂了）。根本不知道做什么，要干什么。盲人。
啊，说起来这学期的课都没怎么听过了。唯一认真听的课就是毛概了。
毛概！！
我有空要整理个毛概笔记？感觉挺好的。
个人偏好那种零星碎片式的片段、语言什么的，大概从我很久以前写自杀那个研究的目录大概的时候就显露出来了，感觉写完了目录就写完了想说的一切。

昨天跟学长（大学里的最后一面了可能）聊了聊，喝了杯奶茶，难以想象的是居然是我说话的时候比较多...可能我好久不写日记憋了不少东西，比如上面那些我也跟他讲了，他说除了计算机通信与网络要听以外别的基本上用不到...我大概也是这么觉得的，自己可能跟本专业愈走愈远了...还是要把唯一优势算法搞好吧。
基本上确定了找工作的路线。研的话虽然金牌但是我完全没有准备也没有计划，其实工作也没有。明年二三月就开始春招了，那时候差不多就要去实习啦。
那这期间，就是真格的开拓视野了，动一些自己不会的东西。当然数学...反演我到现在还不会，可能学不会了（我刚才翻了一下，去年就在写：「反演好难！学不会！还是要学」之类的，结果，哼）
好快啊。
这样想就好想回家啊。

每天被游戏充斥着，感觉真好。是一种理想的生活方式，虽然在某种程度上可以说是一种发泄与逃避，但是不可否认的是，很开心。


Entered on [2018-11-15 Thu 14:50]  
Ended on [2018-11-15 Thu 16:28]
*** 2018-11-21 Wednesday
**** 我又回来了！
因为接下来有好多实验课，所以我又名正言顺的跑来写日记啦。
比如操作系统，根本什么也不会嘛；又比如信安，很简单的又做完了或者根本平台不合；信安攻击也是不会，鸽了；宽带还没上，感觉不会；也就只有汇编跟理解语言差不多，又在认认真真的写了。

喝口水，打会炉石，一回回来。

Entered on [2018-11-21 Wed 08:19]  
Ended on [2018-11-21 Wed 08:28]
**** 哈哈哈
在老师眼皮下面打游戏被老师骂了。
hhh。
我陈述一个事实似乎没有什么问题啊。
算了。

呵。肯定还是自己心有不甘感到怨怼才会如此吧。永远是在自己的角度，计较个人得失，所以常常这样。当然情商低下不知如何处理也是死结吧。
但是每次这样都会手足无措然后毫无理性的当刺头还是太蠢了。
以后这样做人下去满身是刺怕不是要在未来被人把刺全都弯折掰断，疼全在自己。

关键是得到以自我道理为中心的委屈之后我会长时间处于一种愤怒和不满中，这个人充盈着一种幼稚的赌气，想想高中似乎就是如此了，愤怒之后就会退化作孩子态。
长不大呢。
那种突如其来迸发的委屈与狂躁、不满我实在是太熟悉了。
太久以前就是如此了，每次挨打的记忆都鲜血淋漓的暴露着（只是因为挨打的印象比较深刻，别的印象就只有吞泪、哭到身心俱疲哭不出眼泪的那种了，其实我指的是极度痛苦的瞬间，那种扭曲如湮灭或蚁人的中子境中花朵绽放的不现实景象），虽然为数不多但是撕心裂肺的痛楚当时是不会明白精神上的自我安慰是如何生效的，那就是转化痛苦、转移仇恨。
时间一久就成了一种习惯了吧。

另外就是...说得好听一点，我的个人意志过于的强烈，难听一些就是过度自我中心了。虽然有的时候谈话间经常能意识到但是如果表现在所有行为中的话就真的很严重了。
这个啥时候说都行，回头说算了。

---

啊，ff14的婚礼太棒了。
虽然说我们在那里乱放技能干扰视听，也是开心使然。
大家都好漂亮，弹琴又好听，看的我羡慕异常。
当然新郎新娘最棒啦！虽然不若想象中那样竟然是男女...

啊，ff14的妖表太肝了。我的游戏时间一下子就跑了一天多，诗人直接20直升50，全基础职业15，ff14真好玩，一点都不肝（。发光摇摇车还是很好看的，尤其是夜里辉夜姬一般的光芒。
终于开始跑主线了。我本意是我白魔天天打随机练级等级太高了，所以就想着练个副职跟主线进度一起跑，结果...哎。
还是用白魔主职的好，强行熟悉副本（手忙脚乱！永远不控蓝！dps被机制杀！嘤嘤嘤）。另外我的跑位很有问题...嗯，还是要多打的。我要永远做豆芽啊啊啊...

---

啊，上实验课又被李彦江坐在旁边问我mac如何如何，然后配置一个vscode一步三问，几乎每个操作都是我自己做的，半个多小时后放弃去找盗版Clion了。
和上次剧情一模一样啊。
我就不该帮他；我就该告诉他vscode自己配置是没有前途的；我就不该抱有救起一个毫无操作（学习）能力之人的希望，不会水就永远不会水也学不来，死记硬背永远没有前途。
我不知道他为什么要用mac（可能只是有钱），我不知道他为什么要学计算机（兴趣点在哪里？以及可能单纯只是功利的好找工作吧），我不知道...我不知道。
对比大部分正常人而言，我觉得没有学习能力之人太可悲了。李彦江如此，朱正天亦如此。朱正天是ky加毫无方向感与学习能力，别无二致。

---

啊，好想整理毛概课啊。



Entered on [2018-11-21 Wed 08:38]  
Ended on [2018-11-21 Wed 20:39]
** 2018-12 December
*** 2018-12-03 Monday
**** 怪物猎人 启动！
emmm，因为舍友都在玩的关系，所以基本上一直在和舍友一起快乐狩猎。
我寻思是不是要转个远程了，不然三近战猛男各种翻车。
甚至昨天连ff的每日都没有打orz。（3号）
然后昨天又没有打。（5号）
遇到好游戏的前几天必然是拼命的、疯狂的爆肝time？
然后就把主线做完了。

怪物猎人最让人不那么舒服的地方在于，一旦你成为了苍蓝星，站在了食物链的顶端，锤爆了各路古龙，甚至你觉得装备已经走到了一定的尽头，想换一个远程或者换一把武器的时候，突然发现前面那些怪都不用刷了，直接作出终极武器就可以毕业了，失去了一个成长熟练的过程。简单的说就是其他的不需要开荒了，让人处在开心和难过的摇摆之中。

然后发现欠了好多东西好像补不完了。比如说深圳游记、青岛也还没写完；比如琦神不少有趣的见闻；比如毛概老师各种言论；比如说各种游戏体验，猎人生活；比如补题（？补题？那是什么？）；比如专题（？专题？那又是什么？）。
从青岛之后就完全摸鱼了。至今已经有...整整一个月了。
都不知道什么时候才能写了。

这周周末是汇编考试以及大创的中期检查，我要在这几天把大创的那个代码研究一下，然后xjb编几个算法...emmmm，有点困难。
下周要把毛概的调查研究写一下，最开始想写一下和魔法有关的东西...嗯，是一种比较摸的做法吧。总之就是想写点关于网络文化的。以及下周末要去西安参加ecfinal。
然后基本上就要期末考试啦。
生活还真是不给人一两个周喘息的机会呢。虽然我每天都在喘息摸鱼打游戏。但是有压力和没有压力是两个概念的事情。

刚刚看了第一次出去比赛的心境和心情，和现在是完全不同的啊。
甚至比现在好很多。以前会有许多的精力放在比赛之外，观察周围的人和物，虽然打铁却十分快乐。现在呢...
我因为性格之类的原因吧，在队伍里是和稀泥的角色，也不怎么振声发出言论，更多的也因为被lyy的独裁压制，只有琦神的时候还是蛮开心的，lyy的话，我还没有学会怎么交流。
总还觉得没有找到一个那样大家一起开心，一起搞题的那种队伍，那种理想中的大家的关系甚至好到互相交换癖好的地步，像是在深圳总决赛听咖啡鸡发言的时候所说的，三个人泡在机房，睡在机房，醒来就是一起切题交流，累了就点一杯奶茶那样的队伍，是一件蛮遗憾的事情。当然了，那种和女朋友一起做题的更是让人欣羡。
有的只是个人的短期奋斗（划掉），只是一些微不足道的对兴趣的追求，到了后面虽然还有一些兴致，却没有精力完全投入其中了。
还有一些兴致：treap！dsu on tree！lct！我觉得这些东西真的令人愉悦不已。但是一旦进入数学、dp的范畴，我就兴致阑珊了...个人喜好问题吧。

啊，炉石也要更新了。进入肝痛阶段=。=ff卡在南方堡了，没太多时间去做...嗯，其实有，但是都去猎人了。

Entered on [2018-12-03 Mon 08:07]  
Ended on [2018-12-05 Wed 10:45]
*** 2018-12-27 Thursday
**** 啊，好冷啊
零下了呢。
大概只有被子才能抵挡住的冷冽寒气从窗户的缝里渗过来，一点点扎进皮肤里。

其实最近（一个半月啦）一直在打游戏，只是忽然拔肝四顾心茫然，就跑来写日记了。

让我数一下最近的功绩（算是总结性的...爽那么一下。把肝游戏的成果呼啦啦全都摆出来，就跟可可炫耀自己的玩具一样的，如数家珍，哪怕是给自己看，也能开心的不得了。）
怪物猎人250h达成。虽然实际游戏时间。。差那么一点点。
200场片手，85太刀，100轻重弩，240斩斧，140双刀，大概就这样了。
片手熟练（✓）太刀熟练（✓）双刀熟练（？双刀不是只有yyb和yb嘛）弩（不需要）斩斧熟练（✓ 开荒武器用到现在还是不会用后退斩真是抱歉）
片手精通（✗）太刀精通（✗）
其实也就是经过了开荒-熟悉-校服齐了之后对咩咩子下手的顺序之后，忽然失去了目标。珠子是刷不出来的，几个星期的爆肝已经很说明问题了，什么也没有（虽然舍友比我少肝一半却多一两颗攻击珠），然后渣渣辉也是各种不出货。技术方面，刷了50只咩咩子之后也感觉再进步的话其实挺困难的了，就进入了贤者模式了。我个人虽然很享受竞速的过程，但是很多时候挺看脸的（咩咩子是一只可以通过站位预判行动的古龙，但是问题是比如我用片手，很多时候视角一飞天盾就没了，剩下的就全靠感觉和咩咩子来送前爪了。当然不会调我的问题很大，见切同理的，所以精通打了叉，就跟魂3弹反的那种感觉很像，要掌握弹反，然后掌握二换之类的，我觉得都是需要下苦功夫练的）。从片手开始。四分很困难，进一次三分台就要开心的截图。然后一次比一次快，直到有一天我穿上了不动，哇，2分15（9星）。那一个晚上一直在打8星练手，出了2分7，各种不顺，大概杀了20多只之后居然打出了2分00的人生巅峰。注意那时候贝爷没出，还不是校服哦。校服出了之后反而2分台的次数越来越少了。不过还是很容易hhh，后来就练了太刀，玩了玩就跑去欺负咩咩子，还记得上来不动就是2分26，后来发现似乎竞速都是回避达人烟，然后拼命打也最好就打出2分25这样子。
就没啦。想想自己校服之后打的还没有校服之前好，实在丢人。
现在打咩咩子一般都是看到自己一个失误然后就各种粗口心想这把又没啦，心情也就一次比一次差，没有以前那种莽劲了。
那天贤者之后我就跑去网上找mod下了，秉着不直接杀死游戏的想法，只是增加了掉率，大概就是普遍2-5倍极端10倍这样子。总算好过了不少。隔壁欣也直接商店购买rare78珠子、宝玉逆鳞我是觉得有点过了，就没啥好玩的了。

我的怪猎人生大概就到160hr这样了，基本后面养老了。渣渣辉二期的时候肝一肝，王炎王王冥灯更新一波校服可能就真的没啥肝的了？
捉环境生物和大小金我是没太大兴趣啦，我更在意的还是竞速...大概就这样。
哦对了，其实这游戏还是一起玩比较好玩。除了单人速杀之外我觉得最爽的就是三个队友都是舍友然后我拿一把巫师去打1眠2麻1ko，那种感觉无与伦比（一开始眠会被欣也打成儿子，我就直接切扩散了）。单人扩散也爽的，尤其是恐暴龙（近战各种摸不到很气于是扩散启动）就算是流程化也打起来舒适。见面眠，爆桶，一旁地洞，不动，龙击起眠开始扩散并调和，打一波掉进地洞，再打一波，出来一会倒地，扩散，起来基本上残，补二眠爆桶龙击起眠结束。流程里还能补两发毒补伤害优化，但是足够了hhh。


这两天每天爬个塔，把三职业心脏通了（一次过），继续保持全成就。爬塔还是做的挺用心的，优化了界面图标特效什么的感觉很好，新的遗物和卡也都挺不错，希望有更多的内容吧。集中大卡组机器人强无敌，打天敌觉醒者也砍瓜切菜跟网文一样（虽然只有一集中，虽然打心脏全靠起手回响，虽然第一次见心脏吃了第一发满的大伤害，并没有积出球和甲，是容易但是看起来掉了很多血，但是确实强）。战士脸好上来问好牌接破碎金冠，最后4耸肩5全身2屏障1堡垒1巩固1旋风1专注1亮剑1打击1痛击3防御1岿然叠叠叠撞撞撞就过了。。全写出来是因为卡组真的很精简，很强（30分钟打完）。猎人起手潘多拉开始杂技，那种一回合10多卡（其实打心脏的时候一回合打了30+卡）杂技到最后靠涂毒叠毒，计划妥当留出爆发催化剂的combo打赢。前面我有两次差点删了催化剂。打了70分钟...算上sl的时间得有一个半小时。全程碎碎念，估计舍友都怕了我了。不过这种碎碎念念叨起来特别愉快，跟做题时候那种大多时候碎碎念得不到结论不同，都是可以直接践行的措施，算来算去斤斤计较还要一定的未来视，打着打着能愉悦的大笑（一回合杂技死了对面这样或者爆发催化对面突然幂级死亡？），不知道比炉石（和炉石的冒险）高到哪里去了。

然后昨天开始玩了玩石头门，熟悉的慢节奏和galgame式视官（觉）小说，对桌李承峻过来康了康直言「这也太无聊了吧」，不过上次我玩泰坦、ff、魔兽他都是这么说的emmmm。
啊，确实有点慢呢，我打了这三个小时才刚到makise跑到lab来这段....后面应该还蛮漫长的。

进入肝荒之后（最近真的挺有时间，没课，不复习就这样子），想玩的游戏忽然变多了起来，泰坦、黎明、海王星（刷刷刷），石头门，fault2（康康康），贝姐（难的我不想拾起来...实话说这个游戏模式的简单和正常差别太大了点），沙雕crashlands（永远不知道怎么才能过第一关），无限（就是为了伊丽莎白！游戏本身系统我不很喜欢...），只是仓鼠是不会回去当的。


最后...
ff14应该是130h左右吧，大概就是每天摸鱼这样子（不想肝主线啊，不想肝主线啊。）主要是...买了月卡之后一个月我只玩了大概20h的样子？觉得豆芽太棒了一点，一想到再多打一打就要脱离豆芽了就感到心慌慌，立刻退出游戏。


才发现自己写了半天只写了点关于游戏的内容，啊，有些不妙呢。
睡了睡了，很晚啦。

Entered on [2018-12-27 Thu 23:43]  
Ended on [2018-12-28 Fri 01:45]
* 2019
** 2019-01 January
*** 2019-01-03 Thursday
**** 唔，凛冬已至！啊不，新年快乐！
今日bgm：我想在你的脉搏中跳舞+ハレハレヤ
曲风相近，而且都是一样的突然高音？

年度总结大概是没有了，自己翻一翻之前的日记好了。
寒假可能会写一个学期总结...？不好说，我西坡最喜欢做的一件事就是半途而废！
玩完生化奇兵无限，趁着贤者来写点东西。

所幸是个半开放的好结尾啊...好在我玩过石头门，可以假装booker记得所有，珍惜anna。
枯坐了一会竟是不知从何说起。想了想跑到steam评测里面找那段熟悉的评论了。
「如果我知道我们永远到不了那座城，那一天我绝对不会打断你在广场的舞蹈。」
「
"Booker...Are you afraid of God?"
"No, I'm afraid of you."

这是一款被称为第九艺术的游戏

我去过天际省，到过亚楠镇
畅游中世纪，流连诺拉村
在陶森特当过猎魔人，也在纽约2.0打过外星人
当过勇者除过魔王，也受苦打过薪王
然而这一切，全都比不上拿穿过层层乌云，出现在眼前的天空城
以及在沙滩上，跳着舞的伊丽莎白
」
第九艺术全在伊丽莎白上了。
「Elizabeth被抓去做实验时，我已经不在乎什么掩体不掩体的了，只想冲进去打烂那群混蛋的狗头」
对，这就是昨天晚上的我。伊丽莎白的求救和呼喊太让人心碎了。深更半夜的我根本就不想睡，满脑子都是救出伊丽莎白，至于当时场地中间是电梯，我心急火燎跑啊跑不知道去按电梯按钮，发现自己在院子里转圈绕环半天没想明白到底怎么走，气的肝火直冒。
当时因为前面fps苦手，经常被打哭，就打着打着弃了我的伊丽莎白。结果昨天因为打到后面发现其实也没啥难的，技能配合武器，远程欺负敌人，还是可以说随便打的。而且后面剧情很紧凑，前面的包袱一下子就抖开了，虽然在结尾的前一刻反转仍在等待着你，但是全都早有预谋..我其实已经感觉到了。就是那一点违和感，在剧情突飞猛进的时候让我脱离出沉浸体验，预料到了之后的事情。而这违和感出自我亲爱的伊丽莎白...在摧毁了装置之后伊丽莎白表现出的全知全能以及引导有点过了，有一种看穿了无数世界线，算尽了可能性，然后回到这里领着我们走向结局的感觉。好了我通过写这一段话自己meta自己让自己稍微清醒一点...
溺死，居然是无情的溺死。而且来的无比突然。本子看多的我还以为要深情的一吻然后...
但是后面因为紧凑，也造就了这样一个问题：太短了，能和伊丽莎白一起的时间太短了。再也不会有booker挡在她的身前了。再也看不到伊丽莎白装作能看懂黑板密密麻麻的公式抑或是凭栏眺望破亡中的哥伦比亚了。
但是已经很好了。这就很好了。不用受苦的未来。拔下伊丽莎白身后那根管子的时候我浑身都在颤抖。一如当年（假装当年）看到little sister的惨状的那一刻。
所以我几乎很难提起气来去打dlc，海葬I和II了。因为哥伦比亚，因为销魂城，因为伊丽莎白。

明亮色调的蒸汽朋克，稍微用心了的多时间线叙事（听说dlc还会圆回一代...），独一无二的人物情感极为深厚的伊丽莎白，以及「无限」绝望的极乐乌托邦社会（只是光芒被你身边的女儿掩盖了啊）。

最后吐槽一下，如果是个日系游戏那么应该会有跳脱的线啊，至少，至少，都已经近乎全能了，改变一下世界线啊！实在不行，改变一下设定，变量和常量不是完全固定的不好嘛！最最最少，开个裂隙去巴黎啊...这场战役结束我们就去巴黎！（哭）

平行世界这个东西用的越来越多了，前两天看的从人物到画面都惊为天人的蜘蛛侠「平行世界」（在电影院里meta，啊不，直接漫画戳在屏幕上感觉超棒），命运石之门，生化奇兵无限，瑞克和莫蒂，alan wake...不知道以后还会有些什么妖魔鬼怪呢。
自从看过了那本「上帝掷骰子吗」，其实对这些作品愈发期待，能不能更深入呢。
其实科幻的内容的确越来越多了，电影，游戏，很多地方都在讨论这些东西，什么能够倒退时间啦（等我玩完了奇异人生一定回来写..），什么机器人有没有人性啦...balabala

睡了，想起明天还有课，撑不住了。

Entered on [2019-01-03 Thu 00:03]  
Ended on [2019-01-03 Thu 01:02]
*** 2019-01-05 Saturday
**** 
今日bgm：ダイアモンド クレバス
次之：爱・おぼえていますか（东山）
怎么可以这么好听！
菅野洋子nb！吹爆！
是从大串烧里翻出来的，以上皆是（听过东山的版本后不能自拔..听不进原版了..）

因为最近一直在复习嘛，复习就要听歌嘛。因为如果环境很乱，那么听歌是很好的屏蔽与专注的方式；如果环境非常安静，听歌就更是一种享受，让枯燥的学习不再是无法划入规程的一件事情。
另，很气的是今年网易云的年度总结，榜首歌手竟然是Reol...emmmm，虽然这学期听的确实不少，但是根本无法撼动我听泽野的次数...只能得出下架歌曲已经不会算到榜单里（甚至不会在听歌次数上增加了）的结论了。数据控强迫症表示非常难受。
有一阵（记得泽野是8月份下的架）网易云下架了许多音乐，堪称疯狂，吓得我赶紧把喜爱歌单里的歌都存了下来，还以为二次元的末日要来了...结果还好，至少从我的歌单看还好。也有不少歌开始有了版权了，这大概是好事？


翻了眼git，这学期的更新记录惨不忍睹。
正巧找复习资料还翻到了如意大佬的博客，发现就算是那样忙也几乎能保持一日一更acm题，不由羞愧不已。自己沉醉在自己的音乐、游戏、漫画、动画的二次元中，懈怠荒废了很多，于精神上收获了快乐与满足，和大部分同龄人一样，最终变成了...放到总结里去批斗啦。

复习等同于从课本第一页开始学起。
对照着复习提纲一点一点找，全都笔记下来，时间非比寻常。超累啊。
每天的游戏时间也缩水的厉害（这也有脸说得咯），从一天除了吃喝拉撒睡全是打游戏（超糜烂），逐渐变成只有一两个小时的游戏时间了。
不行，把今天的内容复习完我一定要打一会游戏。

每日的心情心境不同，对待同一种天气的态度也不怎么相同。
最近就只有阴雨天。
我只是在想什么时候晴天，最好时间长一点，我好洗了我的衣服。

仿佛在燃烧一般的流星，摘它下来，点亮灯火。好听死了！

Entered on [2019-01-05 Sat 21:31]  
Ended on [2019-01-05 Sat 22:00]
** 2019-02 February
*** 2019-02-09 Saturday
**** 多少天没写了呢...
唔嗯...
发生了很多很多事啦。我似乎有这样一种毛病，即某件事情所积愈多，我愈是不愿去做它。与我不想玩好多游戏有异曲同工之趣。

回退着一件一件流水账吧。

像穿着新内裤迎接新年一样


Entered on [2019-02-09 Sat 11:31]  
Ended on
*** 2019-02-27 Wednesday
**** 是两周一度的实验课呢。
今日bgm：鸡乐器（划掉） 《云长》
次之：《起峰了》

唔，听了几天scboy的解说，再听几首歌的时候竟是莫名的亲切。《亚手》，《卫星点灯》虽然脍炙人口，尤其后者的高潮尤为漂亮，但是却不能在平日哼出来。

最近大创逼的很紧，怕是没啥玩乐的时间了。虽然已经放松了整整一周了。

上回书说到...
回退着一件一件流水账？

哼。
就是什么都没有做，一直在玩。



Entered on [2019-02-27 Wed 13:35]  
Ended on
**** 回来了！

拖着仅剩不多的理智来把日记写完。

流水账再等等。游记再等等。（再等就什么都剩不下啦）

最近看了好多好看的漫画，除了发糖的（五十岚、小弟与番长、品酒、味增汤、鬼如花绽放、长瀞、总之就是很可爱什么的），沙雕的（极主夫道、西顿、阿波连...算了不想列了，总是感觉有哪里遗漏于是就跑去疯狂寻找...）那种，入间、beastars、如果有来生、咒术回战、辉夜大小姐、美术部有问题...都是好好看的漫画啊。
——发自一名因为入间突然更出一名似曾相识的角色跑回去整个重看觉得真是太棒了的初级漫画者的由衷感慨。
尤记得某日看美术部感觉真好啊，这样的青春，这样的美好，然后回忆起自己不堪入目的青春和过往时光，在这条长河中越是看越是多有遗憾...不由得悲从心生，泪流不止。
过于美丽了啊。
这大概也是有些本子好看的实质？借由二次元可以表达现实中所不可能发生的一切，而这种表达由于本子的外壳可以横行无忌，没有边界，没有常理，不循逻辑，也就更令人欣羡。当然只是其中一个方面而已。

这学期的课确实多。主要是因为只有一个课算得上水课，剩下的那些全都是大作业之类的很有用的专业课。

哦对了，今天的机器学习实验真的惊到我了。先生成100个数据，50个n(0,1)50个n(1,1)。好很简单。把他们分类成两部分，问分类方式的查准率和查全率。
我大概想了一下，大概是验算这个数是不是属于曲线上的？写了一会发现自己对于数据理解有问题，然后一下子就理解了整个问题。
我以为数据是某个x对应的y的值，但其实是按照曲线取x值的概率而已，这样的话也就能解释为什么会有负数（如此强烈的违和没有注意到...
我是按照我平时的c语言思路想的，按照机器学习的思路的话，其实就是给一个数据集，你去分训练和测试集，然后跑测试集的查准查全什么的...
在我大概理解是直接套用和去训练两种不同思路之后感到不可名状的震惊。

最后。
这学期实习大概是没戏了，下面就是暑假了。暑假实习现在差不多就是投简历的时候了呢。
我的话，由于很想拖延，所以想着先放一下，等这些消息差不多都放出来，等我这周末把专利那东西搞完找个时间一起投了的好。



Entered on [2019-02-27 Wed 20:20]  
Ended on [2019-02-27 Wed 21:24]
** 2019-03 March
*** 2019-03-06 Wednesday
**** 唔，来晚了来晚了。
今日bgm：Lunatic--REOL
次之：サードアイや!

后天鬼泣5就出啦！

刚刚跑到steamcn看游戏新闻，看到了「你想去哪个游戏世界」的每周话题，稍加思索，写下这样的答案：
「
为什么想进入游戏世界呢——当然是现实世界有不能满足的地方，或者是这个世界有特别吸引人的地方。

当然是没有女朋友、还要被工作学习生活所迫啦。
但是很不想丧失自己很多的自由

warframe是不错的选择，就是没有啥感情线可以跑（如果我去了就能变成开放世界那我一定去）
所以我选择啥都能干的ff14！我要女朋友！我要钓鱼烹饪旅游！

（这话题里黄油和开放世界太占优势了。
」

翻了翻帖子，黄油和开放世界占了多数，开放世界又以天际、看门狗、星露谷为主。还有一些不好界定的（文明什么的。。。）以及。。觉得黑魂里怪很漂亮准备去不可描述的...
x有些就很见游戏与生活之间摇摆的度。比如选欧卡的...


说到摇摆的度，我就不得不说我现在在写的论文了...
因为我找不到一个这样的度。

老板给我们一周让我们写出一份专利，写的方式就是把很新的两篇或更多论文结合一下，变成自己的东西，无需管是否成立。
重点就是这个无需管是否成立。只要不违背一定的逻辑，根本啥都不用管直接拼凑拟合，哪怕长的跟融合怪一样也无所谓。
大概是我还抱着一些「能从里面学到一些」的天真想法的原因，我不由自主的会去思考某些方法的可行性，总觉得扭曲的融合实在是过于丑陋与无用，已经单纯只是一种骗局、唬烂了。这样的想法总让我内心十分不安。
这种不安困惑着我，与英文论文的英文本质构成两座大山压在我身上，让我寸步难移。
我现在刚刚有了一个大概的思路，还没有开始「摘」内容过来。只是我的思路也是嫁接的，是在我不停的自我劝说下才出现的思路。这样的劝说自己接受这种写论文写专利的方式的过程实在是过于操蛋，这才有了这篇日记。
跟同学讨论的内容只能流于表面，只知字面意思，每个字连起来就不识得了。这时候一句不明白，不需要明白就可以糊弄过去。
我大概需要先把「我正在很正经的做学问」这样的观念摒弃了再来，就当是一门作业...但是我喜欢事事衡量计算的强迫又不允许我这样。
唯一可以欣慰的是真的了解，注意就是表面意义的了解了一些cnn的东西。

最近没什么太大的事情了，阮海开始玩魂3，我这时候就搬着我的凳子坐到他旁边给他指路...发现萌新入坑的话，魂的地图真的是大坑，我开过十多次荒的人可以把一些东西记得很清楚，他们就不一样了，他们要么直接错过去，要么需要用命来探路...

去打游戏了。最近很怠惰，但是又很烦躁，觉得需要一些释放。

Entered on [2019-03-06 Wed 21:49]  
Ended on [2019-03-06 Wed 22:15]
*** 2019-03-21 Thursday
**** 咳，多事之秋啊。
今日bgm：Pretenders - live (tielle)
次之：Pretenders - eO1- 、 Pretenders

周日去蓝桥杯，大概就是退役赛了吧，多想打铁起手打铁结束啊（。
然后这周被点名做电子取证实验，感觉又是很麻烦的一事。这月底前还要写出一篇英文论文投出去，虽然这是小组的事，但是因为我一直处于一较为摸鱼的状态所以总觉得自己需要做点啥。

跑来写这日记其实是有原因的。最近一直心神不宁的，上周下了些电影看顺道也打消了去电影院的念头，这周开始看sc的录像研究起手运营，过两天（今天）就出只狼了，前几天的dmc5还没玩熟，红刀弹反蓝拳连招一个都没练，就是不想练。
然后昨天晚上，因为这两天听Pretenders贼带感，原曲大概是mica和Gemie唱的，可我怎么听都是tielle那版的更好听，而且还是某场的live，听得多了便心痒难耐，就想着去找那场演唱会。寻踪索骥没找到那场演唱会，却发现b站上有nzk004和nzk005现场，还是修好音发出来的，就特别开心的看了一晚上。真的是看了一晚上，看的摇头晃脑热血沸腾，真是不知现场会是何种心情。比如yosh在005开头的爆炸我是真的惊了，看他跳来跳去嗓子喊破真是high到不行看出一身汗（得了便宜跑去看reol的十中八九live也看出一身汗hhh）；比如004小林一出mpi顿时矮了不知多少那种感觉，比如比较004和005能感觉出（错觉也说不准？）mpi有进步，Gemie在没了小林就跟一姐没什么区别，Benjamin依旧最僵硬让人忍俊不禁，；比如Eliana唱before my body is dry的别有风味（当然没有小林的穿透力啦）；以及那些不知道是不是提前有所准备，对歌的临时改调和加哼唧加哇偶加诶诶，虽然我是一点不懂，但是听的确实有新鲜感，挺开心。
于是去看演唱会的欲望大增。

上个课，回来继续写。写完了就可以大概的想个统领开始写电子取证那个东西。（更大的可能是写完了就上床了...）

004的风格更全面一点，005...许是没了小林的原因，开头结尾都极燃令人印象深刻，D+T起手，yosh开头，barricades压轴，总有种「这是摇滚乐演唱会」的感觉。当然是总体而言，毕竟中间也有cage，Aesthetic之类风格的曲子。
听完了之后...泽野的歌姬真棒！最喜欢tielle的嗓音，Gemie mizuki不遑多让。英语课代表不够可爱pass！mpi、yosh确实可以，可惜005里没mica，没小林，
没nanami，004里没Eliana，没yosh，总是不能全啊。
这两场音乐会又能听一阵子啦。另外，泽野前两天出了新砖，虽然被腾讯买了到下个月才放出来，不过各位实体盘选手已经放出来啦，reol昨天好像还出了新砖，总之歌是不会乏了。

说回上周。上周看了网络谜踪，觉得很有趣。虽然导演好像说的革命还是颠覆有些过分，但是确乎很有想法——整个镜头全在电脑屏幕之上。通过电脑操作、聊天中输入又删除这种细节、视频聊天、监控、过去的照片视频、新闻、网络热点、直播历史、搜索等等（似乎都列出来了）叙事、表达感情。感觉在电脑操作和真实演出方面达成了一个平衡，有五五开之势。而且电脑操作还能从多方面渲染感情，操作过去文件、鼠标移动（速度、方向等等）、删除的话语、从平常操作中反映真实生活中的一些特点。
纯粹的电脑屏幕叙事。加上一个还蛮有意思的故事。足够了。然后穿插一些细节，甚至放一个外星人入侵的支线，就很吊人胃口里。
这样一讲就会想起习惯二线乃至多线的r&m，除了经典的s2e06，那天去看s3e07，四线并进：大选、学生去许愿池、警察rick的一天、rick饼干的创意，然后在大选结束最后合而为一，埋下伏笔。没得说。只是胸闷气短，连连叹息。

神吕布居然打赢了serral...

以上就大概是最近的一些事了，日常就是上课并且在课上玩手机，回到宿舍打游戏看直播看视频看动漫，过着如愿以偿的神仙生活。
简历投了几个，这应该是第一波，后面大概还会有...然后面试...

其实我觉得我就是不怎么做题，有点飘，没有东西压住自己。
加油吧，最近还是有一些可以忙的目标的。

Entered on [2019-03-21 Thu 16:27]  
Ended on [2019-03-21 Thu 22:21]
** 2019-04 April
*** 2019-04-01 Monday
**** lei了！
拼了一周，三节课点名不到终于把大创的论文搞完了。
说起来可能是很水，但是做起来却一点都不好做。我是摸鱼端，找找代码，改改代码，提点小意见，基本上决策写作什么的都不是我的活。
赶在死线之前做完了。
周三的那个电子取证准备挺久结果没上...感觉挺亏的，这周就不想准备了。

周六半夜近11点搞完了论文，觉得终于解放了，周日疯狂放纵自己，结果到了今天发现自己还是沉不下气。
周日看了个电影，周四周六各一个面试，周四随便问了几个问题就结束了，周六的弄了好久，问了个把uint32或操作从0变1的操作次数期望，然后写一个链表，问大文件的排序。问了问意见，觉得我链表写的真的惨，然后细节什么都不好。
其实我不怎么会链表，认知停留在课上教学的程度上，毕竟stl都写好了...回头可以查查？
现在我大概就是面试了3个不过了。搞得我很慌很怕。柏柏说不善表达是一方面，不善吹嘘也是一方面。我觉得还是自己实力这边的问题大一些。
但是沉不下心来啊。从开学时就这样了。我也不知道怎么调整。
我想着要不写一天日记？赶了一周的论文，游戏都没怎么碰，虽然浪费了很多时间在看小说上，但是看小说打炉石其实都是心中焦虑的外显

4月了啊。

4月新番还好。又能看到one老师作品了。灵能真的棒棒。不知道一拳能不能给出点惊喜。1月没怎么看（只看了jojo灵能）挺遗憾的，感觉还是有不少有意思的番的。
看了海市蜃楼，还是偏向现实主义的。剧本挺好的，女主的智商大概是硬伤。蝴蝶效应，跳跃时间线，我第一时间联想到的当然是石头门，第二时间...是生化奇兵无限的那张时间线图。大家虽然方法不同，比如靠超能力、靠雷暴、靠时间机...总之跳到了另一个世界线里。在引人入胜方面做的可以，比如女主毅然跳楼的时候很爽（慢动作跳楼秀啊），放歌割人的时候很难受。还有几个让人感兴趣的点，女主的所有行为与过往似乎和书中所写一模一样，很值得推敲。是男主已经跑过这个时间线后让人（告诉过去？）写出来的还是这老太太自己写的女主照着书的轨迹脉络走？如何写的？有多少重复？这些问题就可以分化到现实魔幻等许多方面；奇妙的时间穿梭看起来只能在特定的条件下执行，实际上却是想啥时候开就啥时候开，自由的很，那么是不是可以通过一定的方式循环在这25年间，又能在这期间做些什么？摄像机前两个人一定是不同世界线？那么是否可以在一个世界线内窥知到多个世界线的内容？其实感觉上，结尾的男孩就是被两个不同世界线警告然后跳到第三个世界线的。那样的感觉就好像R&M里一群Rick可以自由的穿梭来穿梭去，号称来自地球空间C-137（我竟然就看了好几集的第一季，S1E10，顺便，Wubba lubba dub dub），但是这方面的话大概玩的已经很深了。

跑题了，大概还有些东西可以写，不过...
很晚啦，那我睡了。晚安晚安。

Entered on [2019-04-01 Mon 23:33]  
Ended on [2019-04-02 Tue 03:12]
*** 2019-04-17 Wednesday
**** 很不妙
我的状态很不对，很不对。
现在做题必须熬到晚上才能做，想集中写篇日记都是妄想。
总之就是很不对。
果然需要学习一些放空的东西。

另外似乎我需要锻炼身体以及多做一些活动。我一直以来困惑的胳膊上伸——已经持续了很久一段时间的，只要睡觉似乎睡醒的时候胳膊都会在头上面，无论我睡觉前多么想让它在我的身侧——的原因终于搞清楚了，是疲劳。
是「判断颈肩部劳损，肩周炎的一个指征。由于颈肩部软组织过于近战，睡觉时只有把手举高，才能缓解肌肉紧张血液循环减慢造成的入睡困难。」

所以虽然我决定先行睡去，补足精神。
现在真的是，浑浑噩噩，不知自己在做什么。
最近是有不少事发生，「下次」记咯。
从未有过的焦虑，从未如此想放飞自我，从未像现在这般无力。

Entered on [2019-04-17 Wed 23:00]  
Ended on [2019-04-17 Wed 23:05]
** 2019-06 June
*** 2019-06-18 Tuesday
**** 啊，好久不来写日记了

放飞自我。

然后被年级大会拉回现实。

每次开这样的大会我都会心慌发怵。
不能说是被点醒，总觉得自己处在一种逃避的过程中。从四月份就开始了。四月份弄完大创，然后弄java、弄安全实验、弄网络编程、弄机器学习。把自己埋起来，处于忙碌之中，这样就似乎能够不去面对自己的问题、自己的失败。

蓝桥杯。令人窒息的蓝桥杯（5.25，这样一听似乎还挺近的，那么我的五月都在做什么呢），居然一等奖退役。和我同住的是个18级的，很强，是大佬。
北京也没太多好逛的。这次听了睿神的建议去国图跑了一圈，基本上踏足了所有国图的位置。
唯一比较有印象的点在我大概在天将昏未昏之时坐在火车站旁边的一家店里发呆。想着自己是不是能去参照一下众生万象。


纸醉金迷，每天上午开开心心写代码，中午肝手游睡觉，起床打坦克，吃饭打ff，上周的生活真的是神仙生活。就压力很小、过的很舒服的一周。





我大概是不能正确评估自己的能力的人。
交钱交证的都是坑。
以良好的心态面对挫折和拒绝。


Entered on [2019-06-18 Tue 13:40]  
Ended on [2019-06-18 Tue 19:41]
** 2019-09 September
*** 2019-09-11 Wednesday
**** 许久不见
今日bgm：Zero eclipse
今日bgm其二：お願いマッスル
今日bgm其三：Call your name<Gv>

本来是第二首无限循环的，但是写代码果然还是听泽野舒服，就第一首单曲了一天，一周内254/323次？第三首没什么好说的，又一个Gemie的版本，反正就是好听。

啊，不对。好久不见。

最近基本上是每天都有笔试，然后面试基本上没开始或者笔试还没过。
只是今天突然有个面试，问了五六个问题（知识性的那种），深深感到无力，到处都是盲区，什么都不会。
所以现在问题严重了起来，我有三个方向的东西要去学或者说去做：操作系统/网络方向的知识体系，出现在几个面试和大量笔试选择中；leetcode刷题，就是针对那些只有编程题的笔试；最后又出现了新的东西：c++/算法中一些比较深或者隐蔽的知识体系。

就很麻烦。
笔试过了是很开心啦。不过面试过不了就很难受。
所以我觉得这一周里如果有面试就稍微记一下题目当作白给送命，先整好笔试的那两个东西。
这种东西如果我不写下来的话，我就会不停不停的去想，最后我会陷入两种极端，一种是

舟游出了占星+赤魔的星极，戳中了设定上的感官点。

最近泡在ulk里，战职生产也都不升了，金蝶也不做了，pvp也鸽了，狩猎也不打了，24人本视频过了，也就还做日随跟蛮族了。
我觉得ulk做的还好。真心话。

每天笔试都是蛮自信的，我觉得这挺好，因为做了那么多，没几个很难的编程题...但是面试挺容易炸的。

不说了，睡觉。

Entered on [2019-09-11 Wed 00:35]  
Ended on [2019-09-11 Wed 01:19]
*** 2019-09-28 Saturday
**** 我来了！
今日bgm：shØut-Tielle/Gemie
今日bgm其二:pretenders(Live)-Tielle
是怎么听都听不腻的歌呢，无限单曲，可惜shØUT版权下了，没有统计次数的记录了。

在经历了连续三天规范作息——早上早起学习，中午出门去面试地点，面试之后下午回来稍事歇息，补完当日份的面试总结和感想，看些面经后可以稍微打两小时游戏睡觉——之后，我昨天终于除了投了几家新的公司之外就一直在歇息的状态中。算是放纵了一天。昨天晚上可能因为喝了牛奶睡的有些晚，就一直偏头疼，甚至还反应到了梦境中。当然最后直接就醒了。

三天的面试感觉一次比一次要好一些，不过面试官的问题总跟我看到的面经迥异，弄得我有些糊涂。另外我面试结束之后的很长一段时间里，尤其是HR面之后，会反复回想起当时的问题，重新斟酌回答，有时候甚至会自言自语起来。就是说自己在即时上没有什么天赋，很多东西，不只是对某个问题的看法，像许多刷的算法题在自己跳出来之前会陷进某一种想法里，不能很好的表达出来。
一方面是天赋的问题，更多的我觉得可能是相对的锻炼还是匮乏了些。我是很适合中立的、陈述或者说是复述别人的观点，因为本质上那是另一种模仿。又或者我依然处于一种汲水的状态，内部的压力差还不足以使我形成许多完整的成型的看法。

其实也是我初次现场面试，自己未免很多时候过于紧张，比起如果你给我一个笔试的题而言，思路都不甚清晰。有的是在酒店里的小会议室里一桌一桌一对一的面试，有的（说的就是网易）则是会议室用来集体写份小代码，然后分别去面试官的房间中在房间中面试。


许愿offer吧，两个开奖到概率都不大，只能干等。
其实笔试的时候体会到的还少一些，顶多就是操作系统、计算机网络、数据库或者linux操作不会，但是选择可以瞎蒙啊，很多时候比对比对都能找到正解，实在不行还能在编程题上弥补回来，可是面试就不一样了，问到你多线程你会就是会不会就是凉，问几个不会几个哪还有的机会？再一看面经，啊这个我不知道，这个我不会，这个不记得。就能深刻体会到自己与那些准备半年选手之间的差距。
其实这个差距在于对未来的预判。我大三金牌之后就有些膨胀了，以为就会很好找实习。虽然面试死了，但确实都是死在实在的题上，当时没往这方面考虑，虽然知道基础很烂但是还是更在意自己的编程问题，于是做了些剑指。
当时为什么没去了解秋招来着。
只知道错过了大概要等到秋招才能找工作了，但是却没有一个对秋招对概念，只是说我秋招对时候去投，然后呢，之后的就没多想想了。
我想可能跟自己眼高手低也有蛮大关系的。
常常就说后悔当时怎样怎样，比如高中没搞oi，现在又可以加上没提前了解秋招。母上那天说的那个很有道理，哪怕意识到了也一定要重复犯很多次才慢慢的会改过来。

就这样吧，当是抒发一下自己这几周的积郁，不论是对未来的担忧，对当前知识储备不够的焦急，对没有offer的痛苦，积压了有一段时间了。只是一直碍于有笔试面试没有太多的时间过来吐露。
现在其实也还蛮紧张的，还是要多看面经啊。
不过有个头疼的理由可以继续划一天，我去睡午觉了。



最后，机核网牛逼疯了。

ENTERED ON [2019-09-28 SAT 12:32]  
ENDED ON [2019-09-28 Sat 13:20]
*** 2019-09-30 Monday
**** control通啦
今日bgm：take control！
今日bgm其二：The Poet & The Muse
今天bgm就放两首来自remedy两期大作的歌，主推当然是应和主题的control啦！烟灰缸迷宫真的太nb了。alan wake里印象深的尤其是带词的曲子其实不多了，只记得两位疯人当时狂欢的时候很爽，不过当时音乐应该是衬托；只有在烟灰缸这里，你前面的种种积闷烦躁会在这一首歌中完全爆发出来，完全不违和反而搭配迷宫的变换有一种别样的爽快感。而且是打一个措手不及，阿提怎么就平时都在听这个嘛。

remedy可以，的的确确是打完了就会有一种「新怪谈」就是这样的感觉，很棒。很有scp的感觉，而且不是说我去描绘几个scp的具象去构建的世界体系。

其实起手进控制局FBC的时候两种既视感就已经重合了起来：收集文档、文档上被涂了黑条的部分就已经在Alan wake和scp中联系了起来。主要是收集手稿在Alan wake里是相助理解剧情的关键，这里的文档则是构建整个世界观和新怪谈基调的基石。

说实话游戏性上不过如此（狠狠吐槽），打到最后我枪甚至没开全，升满了等抓握也用的不很多，不单单是因为手柄打枪我还不太行，粉碎那手感除了刚造出来用了用基本上完全吃灰，旋转近距打自爆嘶啸还成，远了就瞄边，穿刺的蓄力就大大限制了使用环境，然后点满了抓取之后枪就是在没能量之后等恢复的时候用来补伤害（划）用的，同化基本上没啥用，制造混乱当当肉盾（当然我到最后都只有1级...），盾不能救我（盾里又不能打枪不能抓取甚至会被人打穿）。刷刷刷的机制还不错，警报后期虽多但是完全不管，全凭怪抬，就是回报机制有点低了，加技能跟刷的没关系，自己能造的怪掉的也不少，只有武器可以做，转了半天开了半天箱子结果烂手里了还是蛮蛋疼的。

boss战机制有点蛋疼，不过体验非常好（指场景布置等等）。比如冰箱战印象就很深刻，霉菌那一战压迫感极强。后面一门心思做主线了，好多东西还没去收容（控制），大概还有蛮多有趣的东西可以挑战的。

啊，说了这么多，其实是想指出一点，我非常同意「所有过程都为情景——叙事需求为先」的这种蛮偏颇的说法，不是说在正面去描写我亘古之屋或者是控制局的形态、作用、各种结构，而是从不论主线支线、散落在各处的文档、hotline、多媒体、整个亘古之屋的设计甚至材料名，以及remedy从Alan wake就展现出来的对明暗光调的掌控感等等这些要素中一点一点让玩家自己体会出来的。随着剧情的推进，你会了解整个亘古之屋的一些特性，了解达林博士，了解特伦奇，了解控制局的日常。
但非常怪的一点在于它又不能算浸入式体验的游戏，因为游戏里时常会有那种离心不适的感觉，比如某些非常难以言明的给人极大荒诞与干瘪感的美其名曰小学堂的玩偶戏材料，诡异到精污的层次；比如女主多的发指且十分冷静的内心独白（而在扯到自己十几年不见的弟弟的时候这种冷静就会消退，叫人非常...不爽），让人很难有一种代入感而是有一种第三人称的观察感甚至说是乖离感，这点其实和Alan wake一样，同时有一种作为玩家且作为主角的诡异感觉，而且他们都从很多个角度来提醒，比如Alan wake里有电视机和收音机，而且会让你去在走主线流程的过程中，就算你知道那个地点在哪，你也会先绕一个大圈，找找有没有暖水瓶或者手稿（这里也一样），control里面更脱离的一点在于你和主角的频道并不相通。如果说Alan wake你能体会到Alan那种无助、那种绝望中的一丝希望、那种四面楚歌的恐怖，你们是处在同一个频道的，但jesse不是。jesse有的时候「像」是在跟北极星交谈，有的时候你听起来似乎就是北极星在说话（但从最后的体验来看似乎北极星从没有说过话，只是太客观冷静给人但错觉），但是几乎都是处于一种对现状极为接受的状态中，而玩家则不同，玩家代入的时候就会由几个疑问而产生「微妙的不适」，比如从一开始的我jesse为什么来？真的只是因为一个十几年不见的弟弟？到后面的达林去哪了？为什么发共鸣器不公开？迪伦受了什么样的苦？为什么会恨二老？为什么表现的如此特殊？为什么北极星不救他？而且这种不适只会随着剧情的发展越来越明显，疑惑越来越多，你迫切的想知道想了解事实的真相，但是女主显然不。jesse除了希卓炸了的时候崩溃了和不正常的急着找弟弟其他时候都非常淡定冷静，对大部分东西漠不关心。劳资凭什么当这个局长而且所有人理所当然？劳资一早就知道阿提有东西，但是有什么东西？你好歹多跟这大哥说说话啊急的不行。按照稽核大佬的理论，这算一种新怪谈的特性——可以名状却哪里不对非常诡异，巧妙的故作玄虚。
刚才说的多了，其实这之外还是有很多东西的，像阿提的存在、亘古屋里莫名其妙的分级（我一局长上来啥级别没有真的菜死了）和失控入侵、一些地图之外的区域、偌大的控制局控制各种分界阈域各类奇人异士大手为什么一个嘶啸就能整成这样等等，但是总体而言大部分都可以归结到刚才那一条结论里，就是玩家不能很好的融入到角色和游戏现实之中，在游戏中似乎逻辑通顺不无道理义正言辞但是在玩家看来就非常的不和谐。种种不和谐加上一些非常反人类的建筑层次设计就让人心生烦躁，这种烦躁与痛苦就是让人使劲推主线的动力，但只可惜越推越迷，甚至最后戛然而止，只是在堆怪然后演出。但是这些可能就是remedy在「控制」的点，他控制你的情绪，这点在烟灰缸迷宫特别鲜明的凸显出来。整个游戏的最高潮就在这里了，而这种高潮的释放依赖于玩家没有沉迷在角色里面，依赖于玩家之前无论是靠建筑的曲折不认路甚至因此多打了非常多怪的体验（游戏体验上的）、对太多事情不清不明的疑惑、整个控制局与失控的背离（剧情上的）、靠大量视觉冲击、红蓝相错、光影交织（视觉体验上的）所有种种所积累的情绪在一个时间点爆发。而且那种尽在掌控之中感觉就像是...这一切就该如此，主角也这样认为，这一切如此荒诞但我觉得这就是对的。
也许这就是新怪谈吧。
结尾亦是如此，你解决了嘶啸的源头。你现在是局长了。你现在很了解形势了。但是你越是了解，越是探寻，越是觉得自己知之甚少。整个亘古之屋越发神秘，控制局也不见得就是你想象中的样子，各种突破收容（就这么用吧）的东西依旧在与你的理性背离，你依旧充满疑惑，甚至越来越多。
——也许这就是新怪谈吧。
就是说这游戏好就好在营造了一种非常难以描述的体验，这种体验会让你与新怪谈之间的距离猛然拉近，极好的平衡（控制了）了理性和非理性的内容。让你在逻辑关系中跳脱出来，能够让许多人都能感受到这种（而且是靠着在非常多的方面用力使得这个人数达到了「许多」的层次，包括我在内）很复杂的基于新怪谈的独特魅力。

这里还要提到的就是两部作品非常奇异的关联。你站着听工作人员闲聊的时候会发现nightspring居然和FBC有关系，而且亮瀑镇已经被收录为奇异事件，然后DLC可能还会继续拓展两个世界的联系——连海报的样式都重叠了，真是...让人欣喜若狂。我还是非常偏爱于这种自我的援引、看似自娱自乐却内里自成体系，使双方都更有趣更生动更真实，一如完美的真空一般，特别让人兴奋。

写的有些多，不过体验不错（指游戏和日记）。
很多思路深受稽核的影响，稽核里还提到了一些比如建筑学，那种理性的四四方方直角三角金字塔都代表的控制与失控的对比等等确实说的极好。
control这个名字。

Entered on [2019-09-30 Mon 19:21]  
Ended on [2019-10-01 Tue 01:47]
** 2019-10 October
*** 2019-10-03 Thursday
**** 来补一下
今日bgm：老实说，没有

一号大概的学了一下，二号完全没学，看了看番，打了各种游戏，睡足了觉。

补一些关于control的游戏体验。
首先就是通关之后没有了主线其实很难再抓住人了，其实最大的阻碍还是说我在寻找各种异常的途中会遭遇一波一波的敌人，如果说这种遭遇还可以有像主线那样的宣泄途径的话，我还可以接受，但是支线很长，而且并不能让你释放，只会补完各种材料，有一种收集上的满足。
游戏初始的体验堪称惊艳。你走进这栋看起来十分规整但是偌大的空间空无一人的大楼。种种散落在各处的资料表明这不是一个简单的大楼，而如果你熟悉这种涂了黑框的文本的话，你会会心一笑，知道这些把戏的目的是什么。游戏初是没有战斗的，或者说你手无寸铁，身无分文，不知道如何战斗所以有着避免战斗的倾向会多去感受周围的空间——所以可以全神贯注于墙上的壁画、画像、布置陈设、明暗分布等等，这对于之后的体验还是蛮重要的。第一印象绝对特别好（毕竟没有开始战斗），然后阿提就出现了。操着一口莫名其妙的口音，说着莫名其妙的话，然后大家似乎都理解了然而又有哪里不对，这里就像机核说的，「疯狂的障碍就产生了。不理解的是玩家，那个世界是完全孤立成熟自成体系的，这种诡异在那是合逻辑的但是玩家体验不了的」然后之前你看到摆在几任局长创立者之间中特立独行的阿提的那副画像裂开，打开一个通道。这时候你发现你回到了之前你走过的一条走廊，所有布置陈设完全一致，甚至包括走廊唯一通路的位置，但你回不去了，你单线程的走进了环内——控制局的内部。这就是序章的体验，我觉得做的极好。

给我印象最深的几个新怪谈或者说scp式的冲击设计是拉灯绳、海景旅馆、失落信件局（和里面的邮件所构建的体系）。
失落信件局会去收集世界各地的奇异事件的信件（报告），无论真假。这个设定特别「真实」，而且非常发散，信息可真可假来源各异，这就有了无限的空间。类似的，scp里也有一个这样的机构。我觉得这种设计特别的棒，你能身在其外的感受到那种灵感的爆发，或是身处其中的体验到所描绘的异常——尽管它的解释也许非常的脱线，但是有似乎有那么些道理。
拉灯绳的第一次体验真的是爆炸了。冷暖色调的调换，场景布置，这种演出，其实我先想到的是层层恐惧。但我想说的不是remedy在塑造场景演出上的独到之处，而是关于仪式的这个概念。在中心研究区，有一个办公室里就在研究这些。摆满了各种类似招财猫的物件，散落的文档说明着仪式充斥在人们的生活中，有些有固定的形式（拉三次开关），有些则没有，比如强迫症、焦虑症是执行行为仪式的（数据删除），他们要做的就是验证某些仪式与真实之间的关联，以及某些看起来非常平常的事情（照镜子）背后的深层含义。特别cool。
海景旅馆是另一则充满了故事性的东西。尤其是你倒数第二次借助海景旅馆来移动时，它不合常理的出现在了主管的位置上，一下子呼应到了许多东西。我觉得这里虽然有很多可以挖掘的点，但它太像一个scp的构想了。

所以来说说scp。

重新拾起scp是听了机核之后的事情。四十二讲到2998，并说会对「圆榫打不进方孔」有一个异常强烈的印象和快感，于是我去看了。
看了之后其实确实会有一种「如此恢弘、如此悲壮」的感觉，但是那种感觉非常模糊。它是随着你想象和推理的过程，逐步加深，你会明白这个过程，你会明白scp的意义，你会明白太阳底下没有新鲜事。
但是为什么是「圆榫打不进方孔」？只要这点仍在困扰我，我就不能完全的体验到那种快感，就好像...算了这比喻不做了。
这就牵扯到了SCP-001。

于是来到今天对另外两个话题：关于逆模因部和scp的架构。

scp的架构——一个维基式的平台，允许各种形式文档的贡献，只要评分够好——即被多数人认同，那么它就可以归档进正式的一篇文档中。

首先是「一无二随」。「一无二随,即“一设无，二设随意”的简写,指那些在一次设定中没有明确说明或暗示不明显瞎脑补，在二设中可以随意发挥的原则」。「一无二随」的「限制」使得人们可以自由的发挥，并交叉引用。很多时候很多快感来自于这种交叉引用（比如圆榫打不进方孔:P）。这种互相援引（正式归档的援引基本都是优秀的援引）使得各自都更加鲜明、更加生动、更加具体，更具魅力。很多设定出现过多次，你甚至对某些概念比如特勤队、模因检测、o5习以为常。

然后是写作技巧。SCP的文档多种多样，有一些以故事作为表达的重心，一般作为辅助描绘某些SCP或者是去建立人物形象，串起时间线世界线，勾勒出某些特勤队的日常和作用等等。
有一些会大量出现「数据删除」或是黑格，这种当然也很需要技巧的技巧留给人们足够多的想象空间，比写全所有内容更让人信服、理解、恍然乃至毛骨悚然。
有一些则利用互联网（或者说数据库查阅）的这一特性，设置各种障碍或者迭代，使得文档本身具有一种类似哈扎尔辞典或者忒修斯之船（很遗憾后者我没有看过只是久闻盛名）的性质和阅读体验，并且在这上面下一番功夫就有会有类似2998式的体验——很多内容隐藏在我一次又一次的迭代中，隐藏在我阅读权限一级比一级高的区别之中，当你探究出现这些区别和迭代原因，你就突然明白了文档的重心。这跟数据删除其实差不多，是一种表现的手法。但正是这些手法，造就了SCP有趣并得以传承发扬的今天。
还有许多，这里不再提因为于我而言可能没那么突出明显，或者过于高明以至于我无法察觉。至于那些模因抹杀触媒之类或是许多自我闭环、自洽的机制，我以为就跟博尔赫斯的那种胡乱吹逼的感觉是一样的，用四十二描述新怪谈的话来说，「巧妙的故弄玄虚」的一个方法而已。

---

问题是圆榫打不进方孔是什么？
这时候的我就像模因感染的人一样狂热的想要去了解这个真相——这个救世的真相本身似乎它像一剂强力的安眠药能使我夜间安稳的入睡，我想知道那些基金会的杀手锏，那些机械降神等级的重启计划。
我顺着这句话找到了SCP-001的一个构想。因为某些原因，SCP-001被分为许多不同的文档，也许是混淆视听，也许是什么别的但那些现在都不重要。我找到了它。
它就在一个表格中，孤零零的，那种只靠自己填充一块表格空间却因为字体不得不空出偌大空白的感觉，让我非常的绞痛——这又是的吧？不管是为了混淆视听、不与人所知还是什么别的，明明其他条目都有详细的描述。所幸它所在的条目还是指向了两个SCP，毕竟这个表格是为了描述两个可以互相抵消异常效应的Keter异常项目，那么是哪两个呢？
SCP-579
SCP-055
我顺着链接爬过去，查找二者之间的关联或者是二者的某些描述，但是很遗憾。
579的条目里充满了令人窒息的数据删除。我不知道是什么人书写的这篇文档或者为什么要写它，但里面充斥着有如恶作剧般的事实——这篇文档基本上什么都没有告诉我。它只是说这个东西异常重要，我们把它放在时空混乱的site-62c中，一旦出现什么变动立刻planA应急，超过10分钟没有恢复就planB直接摧毁site-62的入口...这里似乎有那么一点东西流露出来：似乎它的突破收容是无可描述的，我们是逆向的保护，为了防止它造成更大的破坏而根本就不是为了收容它？基于这个理解，加上一些充满了失败的收容过程的时间线，加上数不胜数的数据删除，我可以大概的描绘出一个，与现实格格不入甚至与对它的描述都会伤害或刺激到它的，危害可能无比巨大的物件。更多更详细的可能要研读推敲它很久才能发掘出来：它充满了理性和客观，它的逻辑也没有紊乱，但是它就是不去描述这个SCP本身，反而只给出了一些收容与站点被破坏的记录，以及应急的处理方式。但我没有这个时间。我觉得口干舌燥，紧迫感越来越强。于是我去找055的记录。
055的描述很简单：任何关于SCP-055的信息，无论外观、本质、行为和起源都是自我屏蔽的。它是自我保守秘密的，它是一个逆模因。对了，一份报告显示它不是圆的。
逆模因。这是什么？
我费尽心思，终于一路沿着一些痕迹找到了逆模因部的中心站。这里很奇怪，只有几个故事。逆模因站的主页上这样写道：
「逆模因是一種具自我屏蔽特性的概念；一種透過其本身的性質，以阻止或防止他人將其傳播的概念。

非異常的逆模因是真實存在的。 想想你的一些不會跟其他人分享的資訊，像密碼，禁忌，還有黑歷史等等。再想一些你就算努力嘗試也很難分享出去的資訊：複雜的公式，極無聊的文字片段，夢境，還有大段大段的隨機數字……

但是異常的逆模因卻是另一回事了。你要如何收容一個你無法記錄或記憶的實體？如何去和無法觸及，而且偽裝完美的敵人，在你甚至不知道自己正和它開仗的情況下進行爭鬥？

歡迎來到逆模因部。

不，這不是你第一天上工。」

这个想法真的太太太绝了，牛逼疯了：我要如何在一场深陷而不能自知的战斗，不，是战争中，同一个无法记录，不能想起的存在对抗？
我认认真真的读完每一个故事。除了机动队O-w处在一我无法理解的时空之中，其他的都非常...棒。「我一生里，你在何处」的那种初见的惊艳和「你最后一个第一天」的震撼史诗感，以及从憎恨之红往后的那些事情似乎真的在拨乱我的神经。
逆模因部原来有几千人，现在只剩下几十人，而这一切发生的悄无声息，甚至我们都不能想起他们的存在，就像我们不记得我是不是第一天上班，就像我每天像逆模因部的成员一样写着日记。也好，这证明我不是这的人。

等等。
圆榫打不进方孔。

我有些明白了。我是逆模因部的人吗？最好不是。那不是一场能够胜利的战争。比起三体那种简单的对峙来说，这里更恐怖、更残忍、也更安静。
不，我没有服过药物，我从来没有。这种自欺欺人是SCP最为惯用的手法，我见得多了，这不会令我恐惧。

另外提一句，我阅读了憎恨之红事件的报告，就情势上来看，这跟control的如出一辙。我不知道他们中有没有什么联系，但是我实在是太累也太困了。
我需要一场梦境来使我充实，我需要一些模因根植在我的脑海中。
我需要睡觉。

Entered on [2019-10-03 Thu 09:54]  
Ended on [2019-10-04 Fri 02:36]
