
* 2017
** 2017-03 March
*** 2017-03-02 Thursday
**** 哈哈哈哈
自己改了下org-capture的格式，现在可以把日记啥的分开写了（于是日记彻彻底底的成为了流水账了），新增了acm，other（主要不知道空闲了会玩啥，哪来的空闲呢。）


Entered on [2017-03-02 Thu 12:01]  
Ended on [2017-03-02 Thu 12:01]

**** 不停修正org中
一时忘了本来想干啥了。

Entered on [2017-03-02 Thu 12:14]  

Ended on [2017-03-02 Thu 12:14]
*** 2017-03-15 Wednesday
**** 记org
原先的学习方向有问题。
只是记快捷键的话是对于emacs而言的（因为当时需要的是操作整个编辑器）而对于需要现实使用的org这样是很滑稽的，因为学起来又痛苦又慢。
明明手上有手册随便一查就好了嘛。
要记的是功能和如何综合去利用他们。
比如ToDo，tag
原来用了两天都没怎么有进展今天一会就把手册看完了= =（虽然没太仔细吧）

ToDo可以用咯。（todo有多种形式，还有标记列表划分子任务优先级甚至还tm能跟踪habit，无话可说）



Entered on [2017-03-15 Wed 15:05]  

Ended on [2017-03-15 Wed 15:05]
**** - -
才发现（也许是我还有没发掘的）capture只能加todo不能找以前的状态啊啊啊
其实也没啥= =
才发现大神说org和emacs和vim是一个层级的东西，虽说有夸誉之嫌，不过，说的挺好。


Entered on [2017-03-15 Wed 16:09]  
Ended on [2017-03-15 Wed 16:09]
**** 我又把最后那个改回来了。
git显示的问题，可以靠其他方式解决嘛

Entered on [2017-03-15 Wed 16:11]  
Ended on [2017-03-15 Wed 16:11]
**** 淦
没找到解决之法。
英语一大片一大片没心思看，短期是改不了这个快捷键了。

Entered on [2017-03-15 Wed 16:47]  
Ended on
**** yasnippet!
稳如poi
这个东西真的好强哦！
淦tm的定制。
这东西从长计议，不急不急。
还有自动拼写补全。我感觉我需要一些2333。

Entered on [2017-03-15 Wed 20:48]  

Ended on [2017-03-15 Wed 20:50]
*** 2017-03-26 Sunday
**** yas真乃神器
今天重新整yas，我感觉是个模版就能扔进去，私人订制系列。
有点好用

Entered on [2017-03-26 Sun 11:57]  
Ended on [2017-03-26 Sun 11:58]

